// AUTO-GENERATED by scripts/gen_nascar_feeder_markets.py. Do not hand-edit.
import type { MarketDriver } from '../../types/marketTypes';

export const driverMarket1991NASCAR: MarketDriver[] = [
  {
    "id": "driver-market-nascar-1991-robert-pressley",
    "name": "Robert Pressley",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 78,
      "braking": 77,
      "straights": 80,
      "tractionAcceleration": 78,
      "elevationBlindCorners": 76,
      "technical": 78,
      "overtakingRacecraft": 79,
      "surfaceGripBumpiness": 78,
      "riskManagement": 77,
      "enduranceConsistency": 78
    },
    "overall": 78,
    "potential": 86,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 73,
    "salary": 3.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 3, 31 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-joe-nemechek",
    "name": "Joe Nemechek",
    "age": 28,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 76,
      "braking": 75,
      "straights": 78,
      "tractionAcceleration": 76,
      "elevationBlindCorners": 74,
      "technical": 76,
      "overtakingRacecraft": 77,
      "surfaceGripBumpiness": 76,
      "riskManagement": 75,
      "enduranceConsistency": 76
    },
    "overall": 76,
    "potential": 84,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 71,
    "salary": 3.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 6, 31 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-todd-bodine",
    "name": "Todd Bodine",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 77,
      "braking": 76,
      "straights": 79,
      "tractionAcceleration": 77,
      "elevationBlindCorners": 75,
      "technical": 77,
      "overtakingRacecraft": 78,
      "surfaceGripBumpiness": 77,
      "riskManagement": 76,
      "enduranceConsistency": 77
    },
    "overall": 77,
    "potential": 85,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 72,
    "salary": 3.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 7, 31 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-tommy-houston",
    "name": "Tommy Houston",
    "age": 46,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 75,
      "braking": 74,
      "straights": 77,
      "tractionAcceleration": 75,
      "elevationBlindCorners": 73,
      "technical": 75,
      "overtakingRacecraft": 76,
      "surfaceGripBumpiness": 75,
      "riskManagement": 74,
      "enduranceConsistency": 75
    },
    "overall": 75,
    "potential": 83,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 70,
    "salary": 3.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 8, 31 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-tom-peck",
    "name": "Tom Peck",
    "age": 38,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 75,
      "braking": 74,
      "straights": 77,
      "tractionAcceleration": 75,
      "elevationBlindCorners": 73,
      "technical": 75,
      "overtakingRacecraft": 76,
      "surfaceGripBumpiness": 75,
      "riskManagement": 74,
      "enduranceConsistency": 75
    },
    "overall": 75,
    "potential": 83,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 70,
    "salary": 3.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 9, 31 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-steve-grissom",
    "name": "Steve Grissom",
    "age": 28,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 76,
      "braking": 75,
      "straights": 78,
      "tractionAcceleration": 76,
      "elevationBlindCorners": 74,
      "technical": 76,
      "overtakingRacecraft": 77,
      "surfaceGripBumpiness": 76,
      "riskManagement": 75,
      "enduranceConsistency": 76
    },
    "overall": 76,
    "potential": 84,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 71,
    "salary": 3.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 10, 31 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-jeff-gordon",
    "name": "Jeff Gordon",
    "age": 20,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 74,
      "braking": 73,
      "straights": 76,
      "tractionAcceleration": 74,
      "elevationBlindCorners": 72,
      "technical": 74,
      "overtakingRacecraft": 75,
      "surfaceGripBumpiness": 74,
      "riskManagement": 73,
      "enduranceConsistency": 74
    },
    "overall": 74,
    "potential": 82,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 69,
    "salary": 3.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 11, 30 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jeff-burton",
    "name": "Jeff Burton",
    "age": 24,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 76,
      "braking": 75,
      "straights": 78,
      "tractionAcceleration": 76,
      "elevationBlindCorners": 74,
      "technical": 76,
      "overtakingRacecraft": 77,
      "surfaceGripBumpiness": 76,
      "riskManagement": 75,
      "enduranceConsistency": 76
    },
    "overall": 76,
    "potential": 84,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 71,
    "salary": 3.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 12, 31 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-david-green",
    "name": "David Green",
    "age": 33,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 75,
      "braking": 74,
      "straights": 77,
      "tractionAcceleration": 75,
      "elevationBlindCorners": 73,
      "technical": 75,
      "overtakingRacecraft": 76,
      "surfaceGripBumpiness": 75,
      "riskManagement": 74,
      "enduranceConsistency": 75
    },
    "overall": 75,
    "potential": 83,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 70,
    "salary": 3.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 13, 29 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-bobby-dotter",
    "name": "Bobby Dotter",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 73,
      "braking": 72,
      "straights": 75,
      "tractionAcceleration": 73,
      "elevationBlindCorners": 71,
      "technical": 73,
      "overtakingRacecraft": 74,
      "surfaceGripBumpiness": 73,
      "riskManagement": 72,
      "enduranceConsistency": 73
    },
    "overall": 73,
    "potential": 81,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 68,
    "salary": 3.65,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 14, 31 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-tracy-leslie",
    "name": "Tracy Leslie",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 73,
      "braking": 72,
      "straights": 75,
      "tractionAcceleration": 73,
      "elevationBlindCorners": 71,
      "technical": 73,
      "overtakingRacecraft": 74,
      "surfaceGripBumpiness": 73,
      "riskManagement": 72,
      "enduranceConsistency": 73
    },
    "overall": 73,
    "potential": 81,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 68,
    "salary": 3.65,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 15, 30 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-butch-miller",
    "name": "Butch Miller",
    "age": 39,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 74,
      "braking": 73,
      "straights": 76,
      "tractionAcceleration": 74,
      "elevationBlindCorners": 72,
      "technical": 74,
      "overtakingRacecraft": 75,
      "surfaceGripBumpiness": 74,
      "riskManagement": 73,
      "enduranceConsistency": 74
    },
    "overall": 74,
    "potential": 82,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 69,
    "salary": 3.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 16, 28 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-dave-rezendes",
    "name": "Dave Rezendes",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 72,
      "braking": 71,
      "straights": 74,
      "tractionAcceleration": 72,
      "elevationBlindCorners": 70,
      "technical": 72,
      "overtakingRacecraft": 73,
      "surfaceGripBumpiness": 72,
      "riskManagement": 71,
      "enduranceConsistency": 72
    },
    "overall": 72,
    "potential": 80,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 67,
    "salary": 3.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 17, 31 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-ward-burton",
    "name": "Ward Burton",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 72,
      "braking": 71,
      "straights": 74,
      "tractionAcceleration": 72,
      "elevationBlindCorners": 70,
      "technical": 72,
      "overtakingRacecraft": 73,
      "surfaceGripBumpiness": 72,
      "riskManagement": 71,
      "enduranceConsistency": 72
    },
    "overall": 72,
    "potential": 80,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 67,
    "salary": 3.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 18, 29 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-ed-berrier",
    "name": "Ed Berrier",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 72,
      "braking": 71,
      "straights": 74,
      "tractionAcceleration": 72,
      "elevationBlindCorners": 70,
      "technical": 72,
      "overtakingRacecraft": 73,
      "surfaceGripBumpiness": 72,
      "riskManagement": 71,
      "enduranceConsistency": 72
    },
    "overall": 72,
    "potential": 80,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 67,
    "salary": 3.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 19, 29 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-elton-sawyer",
    "name": "Elton Sawyer",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 70,
      "braking": 69,
      "straights": 72,
      "tractionAcceleration": 70,
      "elevationBlindCorners": 68,
      "technical": 70,
      "overtakingRacecraft": 71,
      "surfaceGripBumpiness": 70,
      "riskManagement": 69,
      "enduranceConsistency": 70
    },
    "overall": 70,
    "potential": 78,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 65,
    "salary": 3.5,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 20, 24 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-troy-beebe",
    "name": "Troy Beebe",
    "age": 29,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 69,
      "braking": 68,
      "straights": 71,
      "tractionAcceleration": 69,
      "elevationBlindCorners": 67,
      "technical": 69,
      "overtakingRacecraft": 70,
      "surfaceGripBumpiness": 69,
      "riskManagement": 68,
      "enduranceConsistency": 69
    },
    "overall": 69,
    "potential": 77,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 64,
    "salary": 3.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 22, 23 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-cecil-eunice",
    "name": "Cecil Eunice",
    "age": 37,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 68,
      "braking": 67,
      "straights": 70,
      "tractionAcceleration": 68,
      "elevationBlindCorners": 66,
      "technical": 68,
      "overtakingRacecraft": 69,
      "surfaceGripBumpiness": 68,
      "riskManagement": 67,
      "enduranceConsistency": 68
    },
    "overall": 68,
    "potential": 76,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 63,
    "salary": 3.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 24, 20 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-richard-lasater",
    "name": "Richard Lasater",
    "age": 26,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 68,
      "braking": 67,
      "straights": 70,
      "tractionAcceleration": 68,
      "elevationBlindCorners": 66,
      "technical": 68,
      "overtakingRacecraft": 69,
      "surfaceGripBumpiness": 68,
      "riskManagement": 67,
      "enduranceConsistency": 68
    },
    "overall": 68,
    "potential": 76,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 63,
    "salary": 3.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 25, 21 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-ed-ferree",
    "name": "Ed Ferree",
    "age": 39,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 67,
      "braking": 66,
      "straights": 69,
      "tractionAcceleration": 67,
      "elevationBlindCorners": 65,
      "technical": 67,
      "overtakingRacecraft": 68,
      "surfaceGripBumpiness": 67,
      "riskManagement": 66,
      "enduranceConsistency": 67
    },
    "overall": 67,
    "potential": 75,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 62,
    "salary": 3.35,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 26, 20 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jeff-green",
    "name": "Jeff Green",
    "age": 29,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 65,
      "braking": 64,
      "straights": 67,
      "tractionAcceleration": 65,
      "elevationBlindCorners": 63,
      "technical": 65,
      "overtakingRacecraft": 66,
      "surfaceGripBumpiness": 65,
      "riskManagement": 64,
      "enduranceConsistency": 65
    },
    "overall": 65,
    "potential": 73,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 60,
    "salary": 3.25,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 29, 14 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-jack-ingram",
    "name": "Jack Ingram",
    "age": 55,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 62,
      "braking": 61,
      "straights": 64,
      "tractionAcceleration": 62,
      "elevationBlindCorners": 60,
      "technical": 62,
      "overtakingRacecraft": 63,
      "surfaceGripBumpiness": 62,
      "riskManagement": 61,
      "enduranceConsistency": 62
    },
    "overall": 62,
    "potential": 70,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 57,
    "salary": 3.1,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 36, 12 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jim-bown",
    "name": "Jim Bown",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 60,
      "braking": 59,
      "straights": 62,
      "tractionAcceleration": 60,
      "elevationBlindCorners": 58,
      "technical": 60,
      "overtakingRacecraft": 61,
      "surfaceGripBumpiness": 60,
      "riskManagement": 59,
      "enduranceConsistency": 60
    },
    "overall": 60,
    "potential": 68,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 55,
    "salary": 3.0,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 41, 8 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-jack-sprague",
    "name": "Jack Sprague",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 59,
      "braking": 58,
      "straights": 61,
      "tractionAcceleration": 59,
      "elevationBlindCorners": 57,
      "technical": 59,
      "overtakingRacecraft": 60,
      "surfaceGripBumpiness": 59,
      "riskManagement": 58,
      "enduranceConsistency": 59
    },
    "overall": 59,
    "potential": 67,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 54,
    "salary": 2.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 43, 7 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-joe-bessey",
    "name": "Joe Bessey",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 59,
      "braking": 58,
      "straights": 61,
      "tractionAcceleration": 59,
      "elevationBlindCorners": 57,
      "technical": 59,
      "overtakingRacecraft": 60,
      "surfaceGripBumpiness": 59,
      "riskManagement": 58,
      "enduranceConsistency": 59
    },
    "overall": 59,
    "potential": 67,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 54,
    "salary": 2.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 44, 8 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-mike-mclaughlin",
    "name": "Mike McLaughlin",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 59,
      "braking": 58,
      "straights": 61,
      "tractionAcceleration": 59,
      "elevationBlindCorners": 57,
      "technical": 59,
      "overtakingRacecraft": 60,
      "surfaceGripBumpiness": 59,
      "riskManagement": 58,
      "enduranceConsistency": 59
    },
    "overall": 59,
    "potential": 67,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 54,
    "salary": 2.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 45, 8 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-phil-parsons",
    "name": "Phil Parsons",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 58,
      "braking": 57,
      "straights": 60,
      "tractionAcceleration": 58,
      "elevationBlindCorners": 56,
      "technical": 58,
      "overtakingRacecraft": 59,
      "surfaceGripBumpiness": 58,
      "riskManagement": 57,
      "enduranceConsistency": 58
    },
    "overall": 58,
    "potential": 66,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 53,
    "salary": 2.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 46, 6 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jamie-aube",
    "name": "Jamie Aube",
    "age": 38,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 57,
      "braking": 56,
      "straights": 59,
      "tractionAcceleration": 57,
      "elevationBlindCorners": 55,
      "technical": 57,
      "overtakingRacecraft": 58,
      "surfaceGripBumpiness": 57,
      "riskManagement": 56,
      "enduranceConsistency": 57
    },
    "overall": 57,
    "potential": 65,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 52,
    "salary": 2.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 47, 6 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-jay-fogleman",
    "name": "Jay Fogleman",
    "age": 25,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 56,
      "braking": 55,
      "straights": 58,
      "tractionAcceleration": 56,
      "elevationBlindCorners": 54,
      "technical": 56,
      "overtakingRacecraft": 57,
      "surfaceGripBumpiness": 56,
      "riskManagement": 55,
      "enduranceConsistency": 56
    },
    "overall": 56,
    "potential": 64,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 51,
    "salary": 2.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 49, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-patty-moise",
    "name": "Patty Moise",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 56,
      "braking": 55,
      "straights": 58,
      "tractionAcceleration": 56,
      "elevationBlindCorners": 54,
      "technical": 56,
      "overtakingRacecraft": 57,
      "surfaceGripBumpiness": 56,
      "riskManagement": 55,
      "enduranceConsistency": 56
    },
    "overall": 56,
    "potential": 64,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 51,
    "salary": 2.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 50, 5 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-davey-johnson",
    "name": "Davey Johnson",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 56,
      "braking": 55,
      "straights": 58,
      "tractionAcceleration": 56,
      "elevationBlindCorners": 54,
      "technical": 56,
      "overtakingRacecraft": 57,
      "surfaceGripBumpiness": 56,
      "riskManagement": 55,
      "enduranceConsistency": 56
    },
    "overall": 56,
    "potential": 64,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 51,
    "salary": 2.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 51, 6 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jeff-barry",
    "name": "Jeff Barry",
    "age": 24,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 55,
      "braking": 54,
      "straights": 57,
      "tractionAcceleration": 55,
      "elevationBlindCorners": 53,
      "technical": 55,
      "overtakingRacecraft": 56,
      "surfaceGripBumpiness": 55,
      "riskManagement": 54,
      "enduranceConsistency": 55
    },
    "overall": 55,
    "potential": 63,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 50,
    "salary": 2.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 53, 5 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-shawna-robinson",
    "name": "Shawna Robinson",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 55,
      "braking": 54,
      "straights": 57,
      "tractionAcceleration": 55,
      "elevationBlindCorners": 53,
      "technical": 55,
      "overtakingRacecraft": 56,
      "surfaceGripBumpiness": 55,
      "riskManagement": 54,
      "enduranceConsistency": 55
    },
    "overall": 55,
    "potential": 63,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 50,
    "salary": 2.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 54, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-lonnie-rush-jr",
    "name": "Lonnie Rush, Jr.",
    "age": 25,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 55,
      "braking": 54,
      "straights": 57,
      "tractionAcceleration": 55,
      "elevationBlindCorners": 53,
      "technical": 55,
      "overtakingRacecraft": 56,
      "surfaceGripBumpiness": 55,
      "riskManagement": 54,
      "enduranceConsistency": 55
    },
    "overall": 55,
    "potential": 63,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 50,
    "salary": 2.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 55, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-ken-bouchard",
    "name": "Ken Bouchard",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 55,
      "braking": 54,
      "straights": 57,
      "tractionAcceleration": 55,
      "elevationBlindCorners": 53,
      "technical": 55,
      "overtakingRacecraft": 56,
      "surfaceGripBumpiness": 55,
      "riskManagement": 54,
      "enduranceConsistency": 55
    },
    "overall": 55,
    "potential": 63,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 50,
    "salary": 2.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 56, 5 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-tony-hirschman",
    "name": "Tony Hirschman",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 54,
      "braking": 53,
      "straights": 56,
      "tractionAcceleration": 54,
      "elevationBlindCorners": 52,
      "technical": 54,
      "overtakingRacecraft": 55,
      "surfaceGripBumpiness": 54,
      "riskManagement": 53,
      "enduranceConsistency": 54
    },
    "overall": 54,
    "potential": 62,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 49,
    "salary": 2.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 58, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-curtis-markham",
    "name": "Curtis Markham",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 53,
      "braking": 52,
      "straights": 55,
      "tractionAcceleration": 53,
      "elevationBlindCorners": 51,
      "technical": 53,
      "overtakingRacecraft": 54,
      "surfaceGripBumpiness": 53,
      "riskManagement": 52,
      "enduranceConsistency": 53
    },
    "overall": 53,
    "potential": 61,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 48,
    "salary": 2.65,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 59, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-clifford-allison",
    "name": "Clifford Allison",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 53,
      "braking": 52,
      "straights": 55,
      "tractionAcceleration": 53,
      "elevationBlindCorners": 51,
      "technical": 53,
      "overtakingRacecraft": 54,
      "surfaceGripBumpiness": 53,
      "riskManagement": 52,
      "enduranceConsistency": 53
    },
    "overall": 53,
    "potential": 61,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 48,
    "salary": 2.65,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 61, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-mike-rowe",
    "name": "Mike Rowe",
    "age": 41,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 52,
      "braking": 51,
      "straights": 54,
      "tractionAcceleration": 52,
      "elevationBlindCorners": 50,
      "technical": 52,
      "overtakingRacecraft": 53,
      "surfaceGripBumpiness": 52,
      "riskManagement": 51,
      "enduranceConsistency": 52
    },
    "overall": 52,
    "potential": 60,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 47,
    "salary": 2.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 62, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-barney-mcrae",
    "name": "Barney McRae",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 52,
      "braking": 51,
      "straights": 54,
      "tractionAcceleration": 52,
      "elevationBlindCorners": 50,
      "technical": 52,
      "overtakingRacecraft": 53,
      "surfaceGripBumpiness": 52,
      "riskManagement": 51,
      "enduranceConsistency": 52
    },
    "overall": 52,
    "potential": 60,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 47,
    "salary": 2.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 63, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-dick-mccabe",
    "name": "Dick McCabe",
    "age": 44,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 52,
      "braking": 51,
      "straights": 54,
      "tractionAcceleration": 52,
      "elevationBlindCorners": 50,
      "technical": 52,
      "overtakingRacecraft": 53,
      "surfaceGripBumpiness": 52,
      "riskManagement": 51,
      "enduranceConsistency": 52
    },
    "overall": 52,
    "potential": 60,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 47,
    "salary": 2.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 64, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-stub-fadden",
    "name": "Stub Fadden",
    "age": 58,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 51,
      "braking": 50,
      "straights": 53,
      "tractionAcceleration": 51,
      "elevationBlindCorners": 49,
      "technical": 51,
      "overtakingRacecraft": 52,
      "surfaceGripBumpiness": 51,
      "riskManagement": 50,
      "enduranceConsistency": 51
    },
    "overall": 51,
    "potential": 59,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 46,
    "salary": 2.55,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 66, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-kelly-moore",
    "name": "Kelly Moore",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 51,
      "braking": 50,
      "straights": 53,
      "tractionAcceleration": 51,
      "elevationBlindCorners": 49,
      "technical": 51,
      "overtakingRacecraft": 52,
      "surfaceGripBumpiness": 51,
      "riskManagement": 50,
      "enduranceConsistency": 51
    },
    "overall": 51,
    "potential": 59,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 46,
    "salary": 2.55,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 67, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-joey-kourafas",
    "name": "Joey Kourafas",
    "age": 38,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 51,
      "braking": 50,
      "straights": 53,
      "tractionAcceleration": 51,
      "elevationBlindCorners": 49,
      "technical": 51,
      "overtakingRacecraft": 52,
      "surfaceGripBumpiness": 51,
      "riskManagement": 50,
      "enduranceConsistency": 51
    },
    "overall": 51,
    "potential": 59,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 46,
    "salary": 2.55,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 68, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-dale-shaw",
    "name": "Dale Shaw",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 51,
      "braking": 50,
      "straights": 53,
      "tractionAcceleration": 51,
      "elevationBlindCorners": 49,
      "technical": 51,
      "overtakingRacecraft": 52,
      "surfaceGripBumpiness": 51,
      "riskManagement": 50,
      "enduranceConsistency": 51
    },
    "overall": 51,
    "potential": 59,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 46,
    "salary": 2.55,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 69, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-hal-goodson",
    "name": "Hal Goodson",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 49,
      "braking": 48,
      "straights": 51,
      "tractionAcceleration": 49,
      "elevationBlindCorners": 47,
      "technical": 49,
      "overtakingRacecraft": 50,
      "surfaceGripBumpiness": 49,
      "riskManagement": 48,
      "enduranceConsistency": 49
    },
    "overall": 49,
    "potential": 57,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 44,
    "salary": 2.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 73, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-robert-powell",
    "name": "Robert Powell",
    "age": 26,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 49,
      "braking": 48,
      "straights": 51,
      "tractionAcceleration": 49,
      "elevationBlindCorners": 47,
      "technical": 49,
      "overtakingRacecraft": 50,
      "surfaceGripBumpiness": 49,
      "riskManagement": 48,
      "enduranceConsistency": 49
    },
    "overall": 49,
    "potential": 57,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 44,
    "salary": 2.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 74, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-billy-standridge",
    "name": "Billy Standridge",
    "age": 38,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 48,
      "braking": 47,
      "straights": 50,
      "tractionAcceleration": 48,
      "elevationBlindCorners": 46,
      "technical": 48,
      "overtakingRacecraft": 49,
      "surfaceGripBumpiness": 48,
      "riskManagement": 47,
      "enduranceConsistency": 48
    },
    "overall": 48,
    "potential": 56,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 43,
    "salary": 2.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 75, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-peter-daniels",
    "name": "Peter Daniels",
    "age": 33,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 48,
      "braking": 47,
      "straights": 50,
      "tractionAcceleration": 48,
      "elevationBlindCorners": 46,
      "technical": 48,
      "overtakingRacecraft": 49,
      "surfaceGripBumpiness": 48,
      "riskManagement": 47,
      "enduranceConsistency": 48
    },
    "overall": 48,
    "potential": 56,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 43,
    "salary": 2.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 76, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-robert-huffman",
    "name": "Robert Huffman",
    "age": 23,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 48,
      "braking": 47,
      "straights": 50,
      "tractionAcceleration": 48,
      "elevationBlindCorners": 46,
      "technical": 48,
      "overtakingRacecraft": 49,
      "surfaceGripBumpiness": 48,
      "riskManagement": 47,
      "enduranceConsistency": 48
    },
    "overall": 48,
    "potential": 56,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 43,
    "salary": 2.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 77, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-bob-brunell",
    "name": "Bob Brunell",
    "age": 53,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 48,
      "braking": 47,
      "straights": 50,
      "tractionAcceleration": 48,
      "elevationBlindCorners": 46,
      "technical": 48,
      "overtakingRacecraft": 49,
      "surfaceGripBumpiness": 48,
      "riskManagement": 47,
      "enduranceConsistency": 48
    },
    "overall": 48,
    "potential": 56,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 43,
    "salary": 2.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 78, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-bobby-gada",
    "name": "Bobby Gada",
    "age": 51,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 47,
      "braking": 46,
      "straights": 49,
      "tractionAcceleration": 47,
      "elevationBlindCorners": 45,
      "technical": 47,
      "overtakingRacecraft": 48,
      "surfaceGripBumpiness": 47,
      "riskManagement": 46,
      "enduranceConsistency": 47
    },
    "overall": 47,
    "potential": 55,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 42,
    "salary": 2.35,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 79, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-billy-clark",
    "name": "Billy Clark",
    "age": 45,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 47,
      "braking": 46,
      "straights": 49,
      "tractionAcceleration": 47,
      "elevationBlindCorners": 45,
      "technical": 47,
      "overtakingRacecraft": 48,
      "surfaceGripBumpiness": 47,
      "riskManagement": 46,
      "enduranceConsistency": 47
    },
    "overall": 47,
    "potential": 55,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 42,
    "salary": 2.35,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 80, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-dave-dion",
    "name": "Dave Dion",
    "age": 48,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 46,
      "braking": 45,
      "straights": 48,
      "tractionAcceleration": 46,
      "elevationBlindCorners": 44,
      "technical": 46,
      "overtakingRacecraft": 47,
      "surfaceGripBumpiness": 46,
      "riskManagement": 45,
      "enduranceConsistency": 46
    },
    "overall": 46,
    "potential": 54,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 41,
    "salary": 2.3,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 82, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-mike-swaim",
    "name": "Mike Swaim",
    "age": 39,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 46,
      "braking": 45,
      "straights": 48,
      "tractionAcceleration": 46,
      "elevationBlindCorners": 44,
      "technical": 46,
      "overtakingRacecraft": 47,
      "surfaceGripBumpiness": 46,
      "riskManagement": 45,
      "enduranceConsistency": 46
    },
    "overall": 46,
    "potential": 54,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 41,
    "salary": 2.3,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 83, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-randy-macdonald",
    "name": "Randy MacDonald",
    "age": 29,
    "nationality": "Canada",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 45,
      "braking": 44,
      "straights": 47,
      "tractionAcceleration": 45,
      "elevationBlindCorners": 43,
      "technical": 45,
      "overtakingRacecraft": 46,
      "surfaceGripBumpiness": 45,
      "riskManagement": 44,
      "enduranceConsistency": 45
    },
    "overall": 45,
    "potential": 53,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 40,
    "salary": 2.25,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 85, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-joe-thurman",
    "name": "Joe Thurman",
    "age": 53,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 45,
      "braking": 44,
      "straights": 47,
      "tractionAcceleration": 45,
      "elevationBlindCorners": 43,
      "technical": 45,
      "overtakingRacecraft": 46,
      "surfaceGripBumpiness": 45,
      "riskManagement": 44,
      "enduranceConsistency": 45
    },
    "overall": 45,
    "potential": 53,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 40,
    "salary": 2.25,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 87, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-l-d-ottinger",
    "name": "L.D. Ottinger",
    "age": 53,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 44,
      "braking": 43,
      "straights": 46,
      "tractionAcceleration": 44,
      "elevationBlindCorners": 42,
      "technical": 44,
      "overtakingRacecraft": 45,
      "surfaceGripBumpiness": 44,
      "riskManagement": 43,
      "enduranceConsistency": 44
    },
    "overall": 44,
    "potential": 52,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 39,
    "salary": 2.2,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 89, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jeff-spraker",
    "name": "Jeff Spraker",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 44,
      "braking": 43,
      "straights": 46,
      "tractionAcceleration": 44,
      "elevationBlindCorners": 42,
      "technical": 44,
      "overtakingRacecraft": 45,
      "surfaceGripBumpiness": 44,
      "riskManagement": 43,
      "enduranceConsistency": 44
    },
    "overall": 44,
    "potential": 52,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 39,
    "salary": 2.2,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 90, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-john-linville",
    "name": "John Linville",
    "age": 48,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 43,
      "braking": 42,
      "straights": 45,
      "tractionAcceleration": 43,
      "elevationBlindCorners": 41,
      "technical": 43,
      "overtakingRacecraft": 44,
      "surfaceGripBumpiness": 43,
      "riskManagement": 42,
      "enduranceConsistency": 43
    },
    "overall": 43,
    "potential": 51,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 38,
    "salary": 2.15,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 92, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-mike-porter",
    "name": "Mike Porter",
    "age": 50,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 43,
      "braking": 42,
      "straights": 45,
      "tractionAcceleration": 43,
      "elevationBlindCorners": 41,
      "technical": 43,
      "overtakingRacecraft": 44,
      "surfaceGripBumpiness": 43,
      "riskManagement": 42,
      "enduranceConsistency": 43
    },
    "overall": 43,
    "potential": 51,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 38,
    "salary": 2.15,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 93, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-doug-didero",
    "name": "Doug Didero",
    "age": 31,
    "nationality": "Canada",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 42,
      "braking": 41,
      "straights": 44,
      "tractionAcceleration": 42,
      "elevationBlindCorners": 40,
      "technical": 42,
      "overtakingRacecraft": 43,
      "surfaceGripBumpiness": 42,
      "riskManagement": 41,
      "enduranceConsistency": 42
    },
    "overall": 42,
    "potential": 50,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 37,
    "salary": 2.1,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 95, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-frank-fleming",
    "name": "Frank Fleming",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 41,
      "braking": 40,
      "straights": 43,
      "tractionAcceleration": 41,
      "elevationBlindCorners": 39,
      "technical": 41,
      "overtakingRacecraft": 42,
      "surfaceGripBumpiness": 41,
      "riskManagement": 40,
      "enduranceConsistency": 41
    },
    "overall": 41,
    "potential": 49,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 36,
    "salary": 2.05,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 99, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-larry-brolsma",
    "name": "Larry Brolsma",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 41,
      "braking": 40,
      "straights": 43,
      "tractionAcceleration": 41,
      "elevationBlindCorners": 39,
      "technical": 41,
      "overtakingRacecraft": 42,
      "surfaceGripBumpiness": 41,
      "riskManagement": 40,
      "enduranceConsistency": 41
    },
    "overall": 41,
    "potential": 49,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 36,
    "salary": 2.05,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 101, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-gary-neice",
    "name": "Gary Neice",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 40,
      "braking": 39,
      "straights": 42,
      "tractionAcceleration": 40,
      "elevationBlindCorners": 38,
      "technical": 40,
      "overtakingRacecraft": 41,
      "surfaceGripBumpiness": 40,
      "riskManagement": 39,
      "enduranceConsistency": 40
    },
    "overall": 40,
    "potential": 48,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 2.0,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 103, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-jason-keller",
    "name": "Jason Keller",
    "age": 21,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 40,
      "braking": 39,
      "straights": 42,
      "tractionAcceleration": 40,
      "elevationBlindCorners": 38,
      "technical": 40,
      "overtakingRacecraft": 41,
      "surfaceGripBumpiness": 40,
      "riskManagement": 39,
      "enduranceConsistency": 40
    },
    "overall": 40,
    "potential": 48,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 2.0,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 104, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-randy-porter",
    "name": "Randy Porter",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 106, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-mike-weeden",
    "name": "Mike Weeden",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 107, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-tim-bender",
    "name": "Tim Bender",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 108, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-dennis-setzer",
    "name": "Dennis Setzer",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 38,
      "braking": 37,
      "straights": 40,
      "tractionAcceleration": 38,
      "elevationBlindCorners": 36,
      "technical": 38,
      "overtakingRacecraft": 39,
      "surfaceGripBumpiness": 38,
      "riskManagement": 37,
      "enduranceConsistency": 38
    },
    "overall": 38,
    "potential": 46,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 109, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1991-jamie-tomaino",
    "name": "Jamie Tomaino",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 38,
      "braking": 37,
      "straights": 40,
      "tractionAcceleration": 38,
      "elevationBlindCorners": 36,
      "technical": 38,
      "overtakingRacecraft": 39,
      "surfaceGripBumpiness": 38,
      "riskManagement": 37,
      "enduranceConsistency": 38
    },
    "overall": 38,
    "potential": 46,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 110, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1991-glenn-sullivan",
    "name": "Glenn Sullivan",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 38,
      "braking": 37,
      "straights": 40,
      "tractionAcceleration": 38,
      "elevationBlindCorners": 36,
      "technical": 38,
      "overtakingRacecraft": 39,
      "surfaceGripBumpiness": 38,
      "riskManagement": 37,
      "enduranceConsistency": 38
    },
    "overall": 38,
    "potential": 46,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 111, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1991 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  }
] as const satisfies MarketDriver[];
