// AUTO-GENERATED by scripts/gen_nascar_feeder_markets.py. Do not hand-edit.
import type { MarketDriver } from '../../types/marketTypes';

export const driverMarket1994NASCAR: MarketDriver[] = [
  {
    "id": "driver-market-nascar-1994-david-green",
    "name": "David Green",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 78,
      "braking": 77,
      "straights": 80,
      "tractionAcceleration": 78,
      "elevationBlindCorners": 76,
      "technical": 78,
      "overtakingRacecraft": 79,
      "surfaceGripBumpiness": 78,
      "riskManagement": 77,
      "enduranceConsistency": 78
    },
    "overall": 78,
    "potential": 86,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 73,
    "salary": 3.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 1, 28 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-ricky-craven",
    "name": "Ricky Craven",
    "age": 28,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 80,
      "braking": 79,
      "straights": 82,
      "tractionAcceleration": 80,
      "elevationBlindCorners": 78,
      "technical": 80,
      "overtakingRacecraft": 81,
      "surfaceGripBumpiness": 80,
      "riskManagement": 79,
      "enduranceConsistency": 80
    },
    "overall": 80,
    "potential": 88,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 75,
    "salary": 4.0,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 2, 28 starts, 2 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-hermie-sadler",
    "name": "Hermie Sadler",
    "age": 25,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 77,
      "braking": 76,
      "straights": 79,
      "tractionAcceleration": 77,
      "elevationBlindCorners": 75,
      "technical": 77,
      "overtakingRacecraft": 78,
      "surfaceGripBumpiness": 77,
      "riskManagement": 76,
      "enduranceConsistency": 77
    },
    "overall": 77,
    "potential": 85,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 72,
    "salary": 3.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 5, 28 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-johnny-benson-jr",
    "name": "Johnny Benson, Jr.",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 77,
      "braking": 76,
      "straights": 79,
      "tractionAcceleration": 77,
      "elevationBlindCorners": 75,
      "technical": 77,
      "overtakingRacecraft": 78,
      "surfaceGripBumpiness": 77,
      "riskManagement": 76,
      "enduranceConsistency": 77
    },
    "overall": 77,
    "potential": 85,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 72,
    "salary": 3.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 6, 28 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-bobby-dotter",
    "name": "Bobby Dotter",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 75,
      "braking": 74,
      "straights": 77,
      "tractionAcceleration": 75,
      "elevationBlindCorners": 73,
      "technical": 75,
      "overtakingRacecraft": 76,
      "surfaceGripBumpiness": 75,
      "riskManagement": 74,
      "enduranceConsistency": 75
    },
    "overall": 75,
    "potential": 83,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 70,
    "salary": 3.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 7, 28 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-larry-pearson",
    "name": "Larry Pearson",
    "age": 41,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 74,
      "braking": 73,
      "straights": 76,
      "tractionAcceleration": 74,
      "elevationBlindCorners": 72,
      "technical": 74,
      "overtakingRacecraft": 75,
      "surfaceGripBumpiness": 74,
      "riskManagement": 73,
      "enduranceConsistency": 74
    },
    "overall": 74,
    "potential": 82,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 69,
    "salary": 3.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 8, 27 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-dennis-setzer",
    "name": "Dennis Setzer",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 78,
      "braking": 77,
      "straights": 80,
      "tractionAcceleration": 78,
      "elevationBlindCorners": 76,
      "technical": 78,
      "overtakingRacecraft": 79,
      "surfaceGripBumpiness": 78,
      "riskManagement": 77,
      "enduranceConsistency": 78
    },
    "overall": 78,
    "potential": 86,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 73,
    "salary": 3.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 9, 28 starts, 2 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-tracy-leslie",
    "name": "Tracy Leslie",
    "age": 37,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 74,
      "braking": 73,
      "straights": 76,
      "tractionAcceleration": 74,
      "elevationBlindCorners": 72,
      "technical": 74,
      "overtakingRacecraft": 75,
      "surfaceGripBumpiness": 74,
      "riskManagement": 73,
      "enduranceConsistency": 74
    },
    "overall": 74,
    "potential": 82,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 69,
    "salary": 3.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 11, 28 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-elton-sawyer",
    "name": "Elton Sawyer",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 74,
      "braking": 73,
      "straights": 76,
      "tractionAcceleration": 74,
      "elevationBlindCorners": 72,
      "technical": 74,
      "overtakingRacecraft": 75,
      "surfaceGripBumpiness": 74,
      "riskManagement": 73,
      "enduranceConsistency": 74
    },
    "overall": 74,
    "potential": 82,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 69,
    "salary": 3.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 14, 26 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-jim-bown",
    "name": "Jim Bown",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 72,
      "braking": 71,
      "straights": 74,
      "tractionAcceleration": 72,
      "elevationBlindCorners": 70,
      "technical": 72,
      "overtakingRacecraft": 73,
      "surfaceGripBumpiness": 72,
      "riskManagement": 71,
      "enduranceConsistency": 72
    },
    "overall": 72,
    "potential": 80,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 67,
    "salary": 3.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 15, 28 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-jason-keller",
    "name": "Jason Keller",
    "age": 24,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 72,
      "braking": 71,
      "straights": 74,
      "tractionAcceleration": 72,
      "elevationBlindCorners": 70,
      "technical": 72,
      "overtakingRacecraft": 73,
      "surfaceGripBumpiness": 72,
      "riskManagement": 71,
      "enduranceConsistency": 72
    },
    "overall": 72,
    "potential": 80,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 67,
    "salary": 3.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 17, 27 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-rodney-combs",
    "name": "Rodney Combs",
    "age": 44,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 69,
      "braking": 68,
      "straights": 71,
      "tractionAcceleration": 69,
      "elevationBlindCorners": 67,
      "technical": 69,
      "overtakingRacecraft": 70,
      "surfaceGripBumpiness": 69,
      "riskManagement": 68,
      "enduranceConsistency": 69
    },
    "overall": 69,
    "potential": 77,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 64,
    "salary": 3.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 21, 23 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-dave-rezendes",
    "name": "Dave Rezendes",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 69,
      "braking": 68,
      "straights": 71,
      "tractionAcceleration": 69,
      "elevationBlindCorners": 67,
      "technical": 69,
      "overtakingRacecraft": 70,
      "surfaceGripBumpiness": 69,
      "riskManagement": 68,
      "enduranceConsistency": 69
    },
    "overall": 69,
    "potential": 77,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 64,
    "salary": 3.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 22, 22 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-kevin-lepage",
    "name": "Kevin Lepage",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 68,
      "braking": 67,
      "straights": 70,
      "tractionAcceleration": 68,
      "elevationBlindCorners": 66,
      "technical": 68,
      "overtakingRacecraft": 69,
      "surfaceGripBumpiness": 68,
      "riskManagement": 67,
      "enduranceConsistency": 68
    },
    "overall": 68,
    "potential": 76,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 63,
    "salary": 3.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 24, 21 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-stevie-reeves",
    "name": "Stevie Reeves",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 67,
      "braking": 66,
      "straights": 69,
      "tractionAcceleration": 67,
      "elevationBlindCorners": 65,
      "technical": 67,
      "overtakingRacecraft": 68,
      "surfaceGripBumpiness": 67,
      "riskManagement": 66,
      "enduranceConsistency": 67
    },
    "overall": 67,
    "potential": 75,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 62,
    "salary": 3.35,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 26, 20 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-doug-heveron",
    "name": "Doug Heveron",
    "age": 33,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 67,
      "braking": 66,
      "straights": 69,
      "tractionAcceleration": 67,
      "elevationBlindCorners": 65,
      "technical": 67,
      "overtakingRacecraft": 68,
      "surfaceGripBumpiness": 67,
      "riskManagement": 66,
      "enduranceConsistency": 67
    },
    "overall": 67,
    "potential": 75,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 62,
    "salary": 3.35,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 27, 21 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-tommy-houston",
    "name": "Tommy Houston",
    "age": 49,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 66,
      "braking": 65,
      "straights": 68,
      "tractionAcceleration": 66,
      "elevationBlindCorners": 64,
      "technical": 66,
      "overtakingRacecraft": 67,
      "surfaceGripBumpiness": 66,
      "riskManagement": 65,
      "enduranceConsistency": 66
    },
    "overall": 66,
    "potential": 74,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 61,
    "salary": 3.3,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 28, 18 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-roy-payne",
    "name": "Roy Payne",
    "age": 37,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 66,
      "braking": 65,
      "straights": 68,
      "tractionAcceleration": 66,
      "elevationBlindCorners": 64,
      "technical": 66,
      "overtakingRacecraft": 67,
      "surfaceGripBumpiness": 66,
      "riskManagement": 65,
      "enduranceConsistency": 66
    },
    "overall": 66,
    "potential": 74,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 61,
    "salary": 3.3,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 29, 20 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-randy-porter",
    "name": "Randy Porter",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 65,
      "braking": 64,
      "straights": 67,
      "tractionAcceleration": 65,
      "elevationBlindCorners": 63,
      "technical": 65,
      "overtakingRacecraft": 66,
      "surfaceGripBumpiness": 65,
      "riskManagement": 64,
      "enduranceConsistency": 65
    },
    "overall": 65,
    "potential": 73,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 60,
    "salary": 3.25,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 30, 17 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-dirk-stephens",
    "name": "Dirk Stephens",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 64,
      "braking": 63,
      "straights": 66,
      "tractionAcceleration": 64,
      "elevationBlindCorners": 62,
      "technical": 64,
      "overtakingRacecraft": 65,
      "surfaceGripBumpiness": 64,
      "riskManagement": 63,
      "enduranceConsistency": 64
    },
    "overall": 64,
    "potential": 72,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 59,
    "salary": 3.2,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 31, 15 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-johnny-rumley",
    "name": "Johnny Rumley",
    "age": 37,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 63,
      "braking": 62,
      "straights": 65,
      "tractionAcceleration": 63,
      "elevationBlindCorners": 61,
      "technical": 63,
      "overtakingRacecraft": 64,
      "surfaceGripBumpiness": 63,
      "riskManagement": 62,
      "enduranceConsistency": 63
    },
    "overall": 63,
    "potential": 71,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 58,
    "salary": 3.15,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 33, 13 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-joe-bessey",
    "name": "Joe Bessey",
    "age": 33,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 61,
      "braking": 60,
      "straights": 63,
      "tractionAcceleration": 61,
      "elevationBlindCorners": 59,
      "technical": 61,
      "overtakingRacecraft": 62,
      "surfaceGripBumpiness": 61,
      "riskManagement": 60,
      "enduranceConsistency": 61
    },
    "overall": 61,
    "potential": 69,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 56,
    "salary": 3.05,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 37, 11 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-tom-peck",
    "name": "Tom Peck",
    "age": 41,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 61,
      "braking": 60,
      "straights": 63,
      "tractionAcceleration": 61,
      "elevationBlindCorners": 59,
      "technical": 61,
      "overtakingRacecraft": 62,
      "surfaceGripBumpiness": 61,
      "riskManagement": 60,
      "enduranceConsistency": 61
    },
    "overall": 61,
    "potential": 69,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 56,
    "salary": 3.05,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 39, 11 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-mike-garvey",
    "name": "Mike Garvey",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 60,
      "braking": 59,
      "straights": 62,
      "tractionAcceleration": 60,
      "elevationBlindCorners": 58,
      "technical": 60,
      "overtakingRacecraft": 61,
      "surfaceGripBumpiness": 60,
      "riskManagement": 59,
      "enduranceConsistency": 60
    },
    "overall": 60,
    "potential": 68,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 55,
    "salary": 3.0,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 42, 12 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-tommy-ellis",
    "name": "Tommy Ellis",
    "age": 47,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 58,
      "braking": 57,
      "straights": 60,
      "tractionAcceleration": 58,
      "elevationBlindCorners": 56,
      "technical": 58,
      "overtakingRacecraft": 59,
      "surfaceGripBumpiness": 58,
      "riskManagement": 57,
      "enduranceConsistency": 58
    },
    "overall": 58,
    "potential": 66,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 53,
    "salary": 2.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 46, 9 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-shawna-robinson",
    "name": "Shawna Robinson",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 58,
      "braking": 57,
      "straights": 60,
      "tractionAcceleration": 58,
      "elevationBlindCorners": 56,
      "technical": 58,
      "overtakingRacecraft": 59,
      "surfaceGripBumpiness": 58,
      "riskManagement": 57,
      "enduranceConsistency": 58
    },
    "overall": 58,
    "potential": 66,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 53,
    "salary": 2.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 47, 9 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-robbie-reiser",
    "name": "Robbie Reiser",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 58,
      "braking": 57,
      "straights": 60,
      "tractionAcceleration": 58,
      "elevationBlindCorners": 56,
      "technical": 58,
      "overtakingRacecraft": 59,
      "surfaceGripBumpiness": 58,
      "riskManagement": 57,
      "enduranceConsistency": 58
    },
    "overall": 58,
    "potential": 66,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 53,
    "salary": 2.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 48, 9 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-nathan-buttke",
    "name": "Nathan Buttke",
    "age": 19,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 57,
      "braking": 56,
      "straights": 59,
      "tractionAcceleration": 57,
      "elevationBlindCorners": 55,
      "technical": 57,
      "overtakingRacecraft": 58,
      "surfaceGripBumpiness": 57,
      "riskManagement": 56,
      "enduranceConsistency": 57
    },
    "overall": 57,
    "potential": 65,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 52,
    "salary": 2.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 49, 8 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-ronald-cooper",
    "name": "Ronald Cooper",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 57,
      "braking": 56,
      "straights": 59,
      "tractionAcceleration": 57,
      "elevationBlindCorners": 55,
      "technical": 57,
      "overtakingRacecraft": 58,
      "surfaceGripBumpiness": 57,
      "riskManagement": 56,
      "enduranceConsistency": 57
    },
    "overall": 57,
    "potential": 65,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 52,
    "salary": 2.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 50, 7 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-patty-moise",
    "name": "Patty Moise",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 56,
      "braking": 55,
      "straights": 58,
      "tractionAcceleration": 56,
      "elevationBlindCorners": 54,
      "technical": 56,
      "overtakingRacecraft": 57,
      "surfaceGripBumpiness": 56,
      "riskManagement": 55,
      "enduranceConsistency": 56
    },
    "overall": 56,
    "potential": 64,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 51,
    "salary": 2.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 52, 6 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-chad-chaffin",
    "name": "Chad Chaffin",
    "age": 26,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 55,
      "braking": 54,
      "straights": 57,
      "tractionAcceleration": 55,
      "elevationBlindCorners": 53,
      "technical": 55,
      "overtakingRacecraft": 56,
      "surfaceGripBumpiness": 55,
      "riskManagement": 54,
      "enduranceConsistency": 55
    },
    "overall": 55,
    "potential": 63,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 50,
    "salary": 2.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 54, 7 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-michael-ritch",
    "name": "Michael Ritch",
    "age": 21,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 54,
      "braking": 53,
      "straights": 56,
      "tractionAcceleration": 54,
      "elevationBlindCorners": 52,
      "technical": 54,
      "overtakingRacecraft": 55,
      "surfaceGripBumpiness": 54,
      "riskManagement": 53,
      "enduranceConsistency": 54
    },
    "overall": 54,
    "potential": 62,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 49,
    "salary": 2.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 55, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-richard-lasater",
    "name": "Richard Lasater",
    "age": 29,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 54,
      "braking": 53,
      "straights": 56,
      "tractionAcceleration": 54,
      "elevationBlindCorners": 52,
      "technical": 54,
      "overtakingRacecraft": 55,
      "surfaceGripBumpiness": 54,
      "riskManagement": 53,
      "enduranceConsistency": 54
    },
    "overall": 54,
    "potential": 62,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 49,
    "salary": 2.7,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 57, 6 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-david-bonnett",
    "name": "David Bonnett",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 52,
      "braking": 51,
      "straights": 54,
      "tractionAcceleration": 52,
      "elevationBlindCorners": 50,
      "technical": 52,
      "overtakingRacecraft": 53,
      "surfaceGripBumpiness": 52,
      "riskManagement": 51,
      "enduranceConsistency": 52
    },
    "overall": 52,
    "potential": 60,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 47,
    "salary": 2.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 63, 4 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-mike-stefanik",
    "name": "Mike Stefanik",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 52,
      "braking": 51,
      "straights": 54,
      "tractionAcceleration": 52,
      "elevationBlindCorners": 50,
      "technical": 52,
      "overtakingRacecraft": 53,
      "surfaceGripBumpiness": 52,
      "riskManagement": 51,
      "enduranceConsistency": 52
    },
    "overall": 52,
    "potential": 60,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 47,
    "salary": 2.6,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 65, 5 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-dale-shaw",
    "name": "Dale Shaw",
    "age": 30,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 50,
      "braking": 49,
      "straights": 52,
      "tractionAcceleration": 50,
      "elevationBlindCorners": 48,
      "technical": 50,
      "overtakingRacecraft": 51,
      "surfaceGripBumpiness": 50,
      "riskManagement": 49,
      "enduranceConsistency": 50
    },
    "overall": 50,
    "potential": 58,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 45,
    "salary": 2.5,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 67, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-dale-fischlein",
    "name": "Dale Fischlein",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 50,
      "braking": 49,
      "straights": 52,
      "tractionAcceleration": 50,
      "elevationBlindCorners": 48,
      "technical": 50,
      "overtakingRacecraft": 51,
      "surfaceGripBumpiness": 50,
      "riskManagement": 49,
      "enduranceConsistency": 50
    },
    "overall": 50,
    "potential": 58,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 45,
    "salary": 2.5,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 68, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-chris-diamond",
    "name": "Chris Diamond",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 50,
      "braking": 49,
      "straights": 52,
      "tractionAcceleration": 50,
      "elevationBlindCorners": 48,
      "technical": 50,
      "overtakingRacecraft": 51,
      "surfaceGripBumpiness": 50,
      "riskManagement": 49,
      "enduranceConsistency": 50
    },
    "overall": 50,
    "potential": 58,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 45,
    "salary": 2.5,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 70, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-ed-berrier",
    "name": "Ed Berrier",
    "age": 33,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 49,
      "braking": 48,
      "straights": 51,
      "tractionAcceleration": 49,
      "elevationBlindCorners": 47,
      "technical": 49,
      "overtakingRacecraft": 50,
      "surfaceGripBumpiness": 49,
      "riskManagement": 48,
      "enduranceConsistency": 49
    },
    "overall": 49,
    "potential": 57,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 44,
    "salary": 2.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 71, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-martin-truex",
    "name": "Martin Truex",
    "age": 46,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 49,
      "braking": 48,
      "straights": 51,
      "tractionAcceleration": 49,
      "elevationBlindCorners": 47,
      "technical": 49,
      "overtakingRacecraft": 50,
      "surfaceGripBumpiness": 49,
      "riskManagement": 48,
      "enduranceConsistency": 49
    },
    "overall": 49,
    "potential": 57,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 44,
    "salary": 2.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 72, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-kelly-moore",
    "name": "Kelly Moore",
    "age": 35,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 49,
      "braking": 48,
      "straights": 51,
      "tractionAcceleration": 49,
      "elevationBlindCorners": 47,
      "technical": 49,
      "overtakingRacecraft": 50,
      "surfaceGripBumpiness": 49,
      "riskManagement": 48,
      "enduranceConsistency": 49
    },
    "overall": 49,
    "potential": 57,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 44,
    "salary": 2.45,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 73, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-stanton-barrett",
    "name": "Stanton Barrett",
    "age": 22,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 48,
      "braking": 47,
      "straights": 50,
      "tractionAcceleration": 48,
      "elevationBlindCorners": 46,
      "technical": 48,
      "overtakingRacecraft": 49,
      "surfaceGripBumpiness": 48,
      "riskManagement": 47,
      "enduranceConsistency": 48
    },
    "overall": 48,
    "potential": 56,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 43,
    "salary": 2.4,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 77, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-jack-baldwin",
    "name": "Jack Baldwin",
    "age": 46,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 47,
      "braking": 46,
      "straights": 49,
      "tractionAcceleration": 47,
      "elevationBlindCorners": 45,
      "technical": 47,
      "overtakingRacecraft": 48,
      "surfaceGripBumpiness": 47,
      "riskManagement": 46,
      "enduranceConsistency": 47
    },
    "overall": 47,
    "potential": 55,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 42,
    "salary": 2.35,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 78, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-andy-santerre",
    "name": "Andy Santerre",
    "age": 26,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 46,
      "braking": 45,
      "straights": 48,
      "tractionAcceleration": 46,
      "elevationBlindCorners": 44,
      "technical": 46,
      "overtakingRacecraft": 47,
      "surfaceGripBumpiness": 46,
      "riskManagement": 45,
      "enduranceConsistency": 46
    },
    "overall": 46,
    "potential": 54,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 41,
    "salary": 2.3,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 82, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-tim-bender",
    "name": "Tim Bender",
    "age": 37,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 46,
      "braking": 45,
      "straights": 48,
      "tractionAcceleration": 46,
      "elevationBlindCorners": 44,
      "technical": 46,
      "overtakingRacecraft": 47,
      "surfaceGripBumpiness": 46,
      "riskManagement": 45,
      "enduranceConsistency": 46
    },
    "overall": 46,
    "potential": 54,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 41,
    "salary": 2.3,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 83, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-robbie-crouch",
    "name": "Robbie Crouch",
    "age": 42,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 45,
      "braking": 44,
      "straights": 47,
      "tractionAcceleration": 45,
      "elevationBlindCorners": 43,
      "technical": 45,
      "overtakingRacecraft": 46,
      "surfaceGripBumpiness": 45,
      "riskManagement": 44,
      "enduranceConsistency": 45
    },
    "overall": 45,
    "potential": 53,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 40,
    "salary": 2.25,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 84, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-brian-ross",
    "name": "Brian Ross",
    "age": 50,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 45,
      "braking": 44,
      "straights": 47,
      "tractionAcceleration": 45,
      "elevationBlindCorners": 43,
      "technical": 45,
      "overtakingRacecraft": 46,
      "surfaceGripBumpiness": 45,
      "riskManagement": 44,
      "enduranceConsistency": 45
    },
    "overall": 45,
    "potential": 53,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 40,
    "salary": 2.25,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 85, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-andy-petree",
    "name": "Andy Petree",
    "age": 36,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 44,
      "braking": 43,
      "straights": 46,
      "tractionAcceleration": 44,
      "elevationBlindCorners": 42,
      "technical": 44,
      "overtakingRacecraft": 45,
      "surfaceGripBumpiness": 44,
      "riskManagement": 43,
      "enduranceConsistency": 44
    },
    "overall": 44,
    "potential": 52,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 39,
    "salary": 2.2,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 86, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-tom-rosati",
    "name": "Tom Rosati",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 44,
      "braking": 43,
      "straights": 46,
      "tractionAcceleration": 44,
      "elevationBlindCorners": 42,
      "technical": 44,
      "overtakingRacecraft": 45,
      "surfaceGripBumpiness": 44,
      "riskManagement": 43,
      "enduranceConsistency": 44
    },
    "overall": 44,
    "potential": 52,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 39,
    "salary": 2.2,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 89, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-andy-hillenburg",
    "name": "Andy Hillenburg",
    "age": 31,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 43,
      "braking": 42,
      "straights": 45,
      "tractionAcceleration": 43,
      "elevationBlindCorners": 41,
      "technical": 43,
      "overtakingRacecraft": 44,
      "surfaceGripBumpiness": 43,
      "riskManagement": 42,
      "enduranceConsistency": 43
    },
    "overall": 43,
    "potential": 51,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 38,
    "salary": 2.15,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 90, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-jamie-aube",
    "name": "Jamie Aube",
    "age": 41,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 43,
      "braking": 42,
      "straights": 45,
      "tractionAcceleration": 43,
      "elevationBlindCorners": 41,
      "technical": 43,
      "overtakingRacecraft": 44,
      "surfaceGripBumpiness": 43,
      "riskManagement": 42,
      "enduranceConsistency": 43
    },
    "overall": 43,
    "potential": 51,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 38,
    "salary": 2.15,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 91, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-johnny-chapman",
    "name": "Johnny Chapman",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 43,
      "braking": 42,
      "straights": 45,
      "tractionAcceleration": 43,
      "elevationBlindCorners": 41,
      "technical": 43,
      "overtakingRacecraft": 44,
      "surfaceGripBumpiness": 43,
      "riskManagement": 42,
      "enduranceConsistency": 43
    },
    "overall": 43,
    "potential": 51,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 38,
    "salary": 2.15,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 92, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-ashton-lewis",
    "name": "Ashton Lewis",
    "age": 22,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 42,
      "braking": 41,
      "straights": 44,
      "tractionAcceleration": 42,
      "elevationBlindCorners": 40,
      "technical": 42,
      "overtakingRacecraft": 43,
      "surfaceGripBumpiness": 42,
      "riskManagement": 41,
      "enduranceConsistency": 42
    },
    "overall": 42,
    "potential": 50,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 37,
    "salary": 2.1,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 93, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-bobby-dragon",
    "name": "Bobby Dragon",
    "age": 48,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 42,
      "braking": 41,
      "straights": 44,
      "tractionAcceleration": 42,
      "elevationBlindCorners": 40,
      "technical": 42,
      "overtakingRacecraft": 43,
      "surfaceGripBumpiness": 42,
      "riskManagement": 41,
      "enduranceConsistency": 42
    },
    "overall": 42,
    "potential": 50,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 37,
    "salary": 2.1,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 94, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-pete-silva",
    "name": "Pete Silva",
    "age": 46,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 42,
      "braking": 41,
      "straights": 44,
      "tractionAcceleration": 42,
      "elevationBlindCorners": 40,
      "technical": 42,
      "overtakingRacecraft": 43,
      "surfaceGripBumpiness": 42,
      "riskManagement": 41,
      "enduranceConsistency": 42
    },
    "overall": 42,
    "potential": 50,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 37,
    "salary": 2.1,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 95, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-david-hyder",
    "name": "David Hyder",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 41,
      "braking": 40,
      "straights": 43,
      "tractionAcceleration": 41,
      "elevationBlindCorners": 39,
      "technical": 41,
      "overtakingRacecraft": 42,
      "surfaceGripBumpiness": 41,
      "riskManagement": 40,
      "enduranceConsistency": 41
    },
    "overall": 41,
    "potential": 49,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 36,
    "salary": 2.05,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 97, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-jimmy-kitchens",
    "name": "Jimmy Kitchens",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 41,
      "braking": 40,
      "straights": 43,
      "tractionAcceleration": 41,
      "elevationBlindCorners": 39,
      "technical": 41,
      "overtakingRacecraft": 42,
      "surfaceGripBumpiness": 41,
      "riskManagement": 40,
      "enduranceConsistency": 41
    },
    "overall": 41,
    "potential": 49,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 36,
    "salary": 2.05,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 99, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-jeff-barry",
    "name": "Jeff Barry",
    "age": 27,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 40,
      "braking": 39,
      "straights": 42,
      "tractionAcceleration": 40,
      "elevationBlindCorners": 38,
      "technical": 40,
      "overtakingRacecraft": 41,
      "surfaceGripBumpiness": 40,
      "riskManagement": 39,
      "enduranceConsistency": 40
    },
    "overall": 40,
    "potential": 48,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 2.0,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 102, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-john-nemechek",
    "name": "John Nemechek",
    "age": 24,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 103, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-bob-brevak",
    "name": "Bob Brevak",
    "age": 47,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 104, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-david-blankenship",
    "name": "David Blankenship",
    "age": 37,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 105, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-robert-powell",
    "name": "Robert Powell",
    "age": 29,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 39,
      "braking": 38,
      "straights": 41,
      "tractionAcceleration": 39,
      "elevationBlindCorners": 37,
      "technical": 39,
      "overtakingRacecraft": 40,
      "surfaceGripBumpiness": 39,
      "riskManagement": 38,
      "enduranceConsistency": 39
    },
    "overall": 39,
    "potential": 47,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.95,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 106, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-ed-ferree",
    "name": "Ed Ferree",
    "age": 42,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 38,
      "braking": 37,
      "straights": 40,
      "tractionAcceleration": 38,
      "elevationBlindCorners": 36,
      "technical": 38,
      "overtakingRacecraft": 39,
      "surfaceGripBumpiness": 38,
      "riskManagement": 37,
      "enduranceConsistency": 38
    },
    "overall": 38,
    "potential": 46,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 107, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-troy-beebe",
    "name": "Troy Beebe",
    "age": 32,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 38,
      "braking": 37,
      "straights": 40,
      "tractionAcceleration": 38,
      "elevationBlindCorners": 36,
      "technical": 38,
      "overtakingRacecraft": 39,
      "surfaceGripBumpiness": 38,
      "riskManagement": 37,
      "enduranceConsistency": 38
    },
    "overall": 38,
    "potential": 46,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.9,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 109, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "driver-market-nascar-1994-jabe-jones",
    "name": "Jabe Jones",
    "age": 34,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 37,
      "braking": 36,
      "straights": 39,
      "tractionAcceleration": 37,
      "elevationBlindCorners": 35,
      "technical": 37,
      "overtakingRacecraft": 38,
      "surfaceGripBumpiness": 37,
      "riskManagement": 36,
      "enduranceConsistency": 37
    },
    "overall": 37,
    "potential": 45,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 110, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-jay-fogleman",
    "name": "Jay Fogleman",
    "age": 28,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 37,
      "braking": 36,
      "straights": 39,
      "tractionAcceleration": 37,
      "elevationBlindCorners": 35,
      "technical": 37,
      "overtakingRacecraft": 38,
      "surfaceGripBumpiness": 37,
      "riskManagement": 36,
      "enduranceConsistency": 37
    },
    "overall": 37,
    "potential": 45,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 111, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-dick-mccabe",
    "name": "Dick McCabe",
    "age": 47,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 37,
      "braking": 36,
      "straights": 39,
      "tractionAcceleration": 37,
      "elevationBlindCorners": 35,
      "technical": 37,
      "overtakingRacecraft": 38,
      "surfaceGripBumpiness": 37,
      "riskManagement": 36,
      "enduranceConsistency": 37
    },
    "overall": 37,
    "potential": 45,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.85,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 112, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-tom-bolles",
    "name": "Tom Bolles",
    "age": 33,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 36,
      "braking": 35,
      "straights": 38,
      "tractionAcceleration": 36,
      "elevationBlindCorners": 34,
      "technical": 36,
      "overtakingRacecraft": 37,
      "surfaceGripBumpiness": 36,
      "riskManagement": 35,
      "enduranceConsistency": 36
    },
    "overall": 36,
    "potential": 44,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 113, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-stub-fadden",
    "name": "Stub Fadden",
    "age": 61,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 36,
      "braking": 35,
      "straights": 38,
      "tractionAcceleration": 36,
      "elevationBlindCorners": 34,
      "technical": 36,
      "overtakingRacecraft": 37,
      "surfaceGripBumpiness": 36,
      "riskManagement": 35,
      "enduranceConsistency": 36
    },
    "overall": 36,
    "potential": 44,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 115, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-toby-tobias-jr",
    "name": "Toby Tobias, Jr.",
    "age": 28,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 36,
      "braking": 35,
      "straights": 38,
      "tractionAcceleration": 36,
      "elevationBlindCorners": 34,
      "technical": 36,
      "overtakingRacecraft": 37,
      "surfaceGripBumpiness": 36,
      "riskManagement": 35,
      "enduranceConsistency": 36
    },
    "overall": 36,
    "potential": 44,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.8,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 116, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  },
  {
    "id": "driver-market-nascar-1994-john-alexander",
    "name": "John Alexander",
    "age": 40,
    "nationality": "USA",
    "context": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Driver Market",
    "marketStatus": "Available",
    "primaryRole": "Driver",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "immediateF1Eligible": true,
    "skills": {
      "cornering": 35,
      "braking": 34,
      "straights": 37,
      "tractionAcceleration": 35,
      "elevationBlindCorners": 33,
      "technical": 35,
      "overtakingRacecraft": 36,
      "surfaceGripBumpiness": 35,
      "riskManagement": 34,
      "enduranceConsistency": 35
    },
    "overall": 35,
    "potential": 43,
    "potentialDelta": 8,
    "developmentRate": 50,
    "f1Readiness": 35,
    "salary": 1.75,
    "sponsorValue": 0,
    "buyoutCost": 0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Race / reserve driver",
    "notes": "Xfinity/Busch standings: rank 117, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1994 Identity: https://www.race-database.com/driver/series.php?series_id=11"
  }
] as const satisfies MarketDriver[];
