// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  MarketDriver,
} from '../../types/marketTypes';

export const driverMarket2002NASCAR: MarketDriver[] = [
  {
    "id": "driver-nascar-2002-dennis-setzer",
    "name": "Dennis Setzer",
    "age": 30,
    "nationality": "United States",
    "context": "NASCAR",
    "marketPool": "NASCAR",
    "marketStatus": "Free Agent",
    "primaryRole": "Driver",
    "immediateF1Eligible": false,
    "skills": {
      "cornering": 17,
      "braking": 18,
      "straights": 16,
      "tractionAcceleration": 16,
      "elevationBlindCorners": 15,
      "technical": 19,
      "overtakingRacecraft": 21,
      "surfaceGripBumpiness": 17,
      "riskManagement": 20,
      "enduranceConsistency": 18
    },
    "overall": 18,
    "potential": 28,
    "potentialDelta": 10,
    "developmentRate": 50,
    "f1Readiness": 0,
    "salary": 0.18,
    "sponsorValue": 0.09,
    "buyoutCost": 0.0,
    "negotiationDifficulty": "Medium",
    "suggestedUse": "Stand-in / reserve",
    "notes": ""
  }
] as const satisfies MarketDriver[];

