// AUTO-GENERATED by scripts/gen_nascar_feeder_markets.py. Do not hand-edit.
import type { YouthProspect } from '../../types/marketTypes';

export const youthProspects2013NASCAR: YouthProspect[] = [
  {
    "id": "youth-nascar-2013-erik-jones",
    "name": "Erik Jones",
    "age": 17,
    "birthYear": 1996,
    "nationality": "USA",
    "currentLevel": "Truck",
    "marketPool": "Shared Motorsport Youth Market",
    "marketStatus": "Academy Prospect",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "academyEligibleNow": true,
    "earliestFullAcademyYear": 2013,
    "skills": {
      "cornering": 61,
      "braking": 60,
      "straights": 63,
      "tractionAcceleration": 61,
      "elevationBlindCorners": 59,
      "technical": 61,
      "overtakingRacecraft": 62,
      "surfaceGripBumpiness": 61,
      "riskManagement": 58,
      "enduranceConsistency": 59
    },
    "overall": 61,
    "potential": 79,
    "potentialDelta": 18,
    "developmentRate": 65,
    "yearsUntilF1Ready": 1,
    "signingCost": 0.12,
    "yearlyAcademyCost": 0.08,
    "riskLevel": "Medium",
    "suggestedPath": "NASCAR development ladder",
    "notes": "Truck standings: rank 29, 5 starts, 1 wins. Source: https://www.race-database.com/standings/standings.php?series_id=12&year=2013 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "youth-nascar-2013-brandon-jones",
    "name": "Brandon Jones",
    "age": 16,
    "birthYear": 1997,
    "nationality": "USA",
    "currentLevel": "Truck",
    "marketPool": "Shared Motorsport Youth Market",
    "marketStatus": "Academy Prospect",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "academyEligibleNow": true,
    "earliestFullAcademyYear": 2013,
    "skills": {
      "cornering": 56,
      "braking": 55,
      "straights": 58,
      "tractionAcceleration": 56,
      "elevationBlindCorners": 54,
      "technical": 56,
      "overtakingRacecraft": 57,
      "surfaceGripBumpiness": 56,
      "riskManagement": 53,
      "enduranceConsistency": 54
    },
    "overall": 56,
    "potential": 74,
    "potentialDelta": 18,
    "developmentRate": 65,
    "yearsUntilF1Ready": 2,
    "signingCost": 0.12,
    "yearlyAcademyCost": 0.08,
    "riskLevel": "Medium",
    "suggestedPath": "NASCAR development ladder",
    "notes": "Truck standings: rank 41, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=12&year=2013 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "youth-nascar-2013-john-hunter-nemechek",
    "name": "John Hunter Nemechek",
    "age": 16,
    "birthYear": 1997,
    "nationality": "USA",
    "currentLevel": "Truck",
    "marketPool": "Shared Motorsport Youth Market",
    "marketStatus": "Academy Prospect",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "academyEligibleNow": true,
    "earliestFullAcademyYear": 2013,
    "skills": {
      "cornering": 55,
      "braking": 54,
      "straights": 57,
      "tractionAcceleration": 55,
      "elevationBlindCorners": 53,
      "technical": 55,
      "overtakingRacecraft": 56,
      "surfaceGripBumpiness": 55,
      "riskManagement": 52,
      "enduranceConsistency": 53
    },
    "overall": 55,
    "potential": 73,
    "potentialDelta": 18,
    "developmentRate": 65,
    "yearsUntilF1Ready": 2,
    "signingCost": 0.11,
    "yearlyAcademyCost": 0.08,
    "riskLevel": "Medium",
    "suggestedPath": "NASCAR development ladder",
    "notes": "Truck standings: rank 45, 2 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=12&year=2013 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "youth-nascar-2013-alex-guenette",
    "name": "Alex Guenette",
    "age": 17,
    "birthYear": 1996,
    "nationality": "Canada",
    "currentLevel": "Truck",
    "marketPool": "Shared Motorsport Youth Market",
    "marketStatus": "Academy Prospect",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "academyEligibleNow": true,
    "earliestFullAcademyYear": 2013,
    "skills": {
      "cornering": 51,
      "braking": 50,
      "straights": 53,
      "tractionAcceleration": 51,
      "elevationBlindCorners": 49,
      "technical": 51,
      "overtakingRacecraft": 52,
      "surfaceGripBumpiness": 51,
      "riskManagement": 48,
      "enduranceConsistency": 49
    },
    "overall": 51,
    "potential": 69,
    "potentialDelta": 18,
    "developmentRate": 65,
    "yearsUntilF1Ready": 1,
    "signingCost": 0.11,
    "yearlyAcademyCost": 0.07,
    "riskLevel": "Medium",
    "suggestedPath": "NASCAR development ladder",
    "notes": "Truck standings: rank 70, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=12&year=2013 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  },
  {
    "id": "youth-nascar-2013-tyler-reddick",
    "name": "Tyler Reddick",
    "age": 17,
    "birthYear": 1996,
    "nationality": "USA",
    "currentLevel": "Truck",
    "marketPool": "Shared Motorsport Youth Market",
    "marketStatus": "Academy Prospect",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "academyEligibleNow": true,
    "earliestFullAcademyYear": 2013,
    "skills": {
      "cornering": 50,
      "braking": 49,
      "straights": 52,
      "tractionAcceleration": 50,
      "elevationBlindCorners": 48,
      "technical": 50,
      "overtakingRacecraft": 51,
      "surfaceGripBumpiness": 50,
      "riskManagement": 47,
      "enduranceConsistency": 48
    },
    "overall": 50,
    "potential": 68,
    "potentialDelta": 18,
    "developmentRate": 65,
    "yearsUntilF1Ready": 1,
    "signingCost": 0.11,
    "yearlyAcademyCost": 0.07,
    "riskLevel": "Medium",
    "suggestedPath": "NASCAR development ladder",
    "notes": "Truck standings: rank 77, 1 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=12&year=2013 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  }
] as const satisfies YouthProspect[];
