// AUTO-GENERATED by scripts/gen_nascar_feeder_markets.py. Do not hand-edit.
import type { YouthProspect } from '../../types/marketTypes';

export const youthProspects1992NASCAR: YouthProspect[] = [
  {
    "id": "youth-nascar-1992-nathan-buttke",
    "name": "Nathan Buttke",
    "age": 17,
    "birthYear": 1975,
    "nationality": "USA",
    "currentLevel": "Xfinity/Busch",
    "marketPool": "Shared Motorsport Youth Market",
    "marketStatus": "Academy Prospect",
    "seriesPreferences": [
      {
        "series": "NASCAR",
        "weight": 100
      }
    ],
    "academyEligibleNow": true,
    "earliestFullAcademyYear": 1992,
    "skills": {
      "cornering": 48,
      "braking": 47,
      "straights": 50,
      "tractionAcceleration": 48,
      "elevationBlindCorners": 46,
      "technical": 48,
      "overtakingRacecraft": 49,
      "surfaceGripBumpiness": 48,
      "riskManagement": 45,
      "enduranceConsistency": 46
    },
    "overall": 48,
    "potential": 66,
    "potentialDelta": 18,
    "developmentRate": 65,
    "yearsUntilF1Ready": 1,
    "signingCost": 0.11,
    "yearlyAcademyCost": 0.07,
    "riskLevel": "Medium",
    "suggestedPath": "NASCAR development ladder",
    "notes": "Xfinity/Busch standings: rank 61, 3 starts, 0 wins. Source: https://www.race-database.com/standings/standings.php?series_id=11&year=1992 Identity: https://www.race-database.com/driver/series.php?series_id=12"
  }
] as const satisfies YouthProspect[];
