// Practice sessions & setup feedback (Living Universe Phase 1 — types only).
//
// Practice is a real weekend phase: the player assigns a program to each driver
// per session, the sim runs it, and it returns directional feedback plus
// accumulated "knowledge" that improves setup confidence, tyre/reliability
// estimates and strategy accuracy — without ever revealing the perfect setup.

import type { CarSetup } from './setupTypes';

// The kinds of practice sessions a weekend can contain. The exact set depends on
// the era/series (e.g. modern F1 has FP1-FP3; older eras add a warmup).
export type PracticeSessionKind =
  | 'Practice1'
  | 'Practice2'
  | 'Practice3'
  | 'Warmup'
  | 'QualifyingPrep'
  | 'RaceSimulation';

// A program the player can run for a driver in a practice session. Each biases
// what kind of knowledge/feedback the session produces.
export type PracticeProgram =
  | 'SetupExploration'
  | 'QualifyingSimulation'
  | 'RacePaceRun'
  | 'TireWearAnalysis'
  | 'ReliabilityShakedown'
  | 'FuelLoadTest'
  | 'BrakeTemperatureTest'
  | 'WetWeatherPreparation'
  | 'DriverConfidenceRun';

// Severity/tone of a feedback line, for UI emphasis.
export type FeedbackSentiment = 'Positive' | 'Neutral' | 'Concern' | 'Warning';

// What an individual feedback line is about, so the UI can group/iconify it.
export type FeedbackTopic =
  | 'Aero'
  | 'Balance'
  | 'Tires'
  | 'Brakes'
  | 'Engine'
  | 'RideHeight'
  | 'Confidence'
  | 'LongRunPace'
  | 'Degradation'
  | 'Fuel'
  | 'Reliability';

// A single directional feedback line generated by a practice run.
export type PracticeFeedbackItem = {
  id: string;
  driverId: string;
  topic: FeedbackTopic;
  sentiment: FeedbackSentiment;
  message: string;
};

// The per-driver assignment for one session.
export type PracticeAssignment = {
  driverId: string;
  program: PracticeProgram;
  lapsPlanned: number;
};

// The outcome of running one driver's program in a session.
export type PracticeRunResult = {
  driverId: string;
  program: PracticeProgram;
  lapsCompleted: number;
  bestLapSec?: number;
  incident: boolean; // a spin/off/minor damage occurred
  feedback: PracticeFeedbackItem[];
  // Knowledge deltas contributed by this run (0-1 contributions).
  setupKnowledgeGain: number;
  tireKnowledgeGain: number;
  reliabilityKnowledgeGain: number;
  confidenceGain: number;
};

// One session within the weekend, with assignments and (once run) results.
export type PracticeSession = {
  id: string;
  raceId: string;
  kind: PracticeSessionKind;
  assignments: PracticeAssignment[];
  results?: PracticeRunResult[];
  completed: boolean;
};

// Accumulated, per-driver weekend knowledge built up across practice sessions.
// All values are 0-1 (0 = no information, 1 = fully understood). These feed
// setup confidence, tyre-wear/strategy estimates and qualifying expectations.
export type WeekendKnowledge = {
  raceId: string;
  setupKnowledge: Record<string, number>; // driverId -> 0-1
  tireKnowledge: Record<string, number>; // driverId -> 0-1
  reliabilityKnowledge: Record<string, number>; // driverId -> 0-1
  // Per-driver confidence nudges accrued in practice (-1..+1), applied on top of
  // the driver's base confidence for quali/race.
  confidenceDelta: Record<string, number>;
};

// The full practice state for a weekend, persisted on the active race weekend.
export type WeekendPractice = {
  raceId: string;
  sessions: PracticeSession[];
  knowledge: WeekendKnowledge;
  // Practice laps consumed so far this weekend (against the weekend lap budget).
  lapsUsed?: number;
  // The setup family each driver actually ran in practice — the baseline the
  // Car Setup Workshop compares the final setup against for driver comfort.
  practicedSetupByDriver?: Record<string, CarSetup>;
  // The full history of setups run per driver across the weekend's sessions.
  practicedSetupHistory?: Record<string, CarSetup[]>;
  // Practice laps banked per driver (for setup familiarity).
  practiceLapsByDriver?: Record<string, number>;
};
