// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Team,
} from '../../types/gameTypes';

export const teams2019NASCAR: Team[] = [
  {
    "id": "t-2019-nascar-beard-motorsports",
    "name": "Beard Motorsports",
    "shortName": "",
    "carId": "car-2019-nascar-beard-motorsports",
    "driverIds": [
      "d-2019-nascar-brendan-gaughan"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 1,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-chip-ganassi-racing",
    "name": "Chip Ganassi Racing",
    "shortName": "",
    "carId": "car-2019-nascar-chip-ganassi-racing",
    "driverIds": [
      "d-2019-nascar-kurt-busch",
      "d-2019-nascar-kyle-larson"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 2,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-front-row-motorsports-team-1-team-1",
    "name": "Front Row Motorsports Team 1 team 1",
    "shortName": "",
    "carId": "car-2019-nascar-front-row-motorsports-team-1-team-1",
    "driverIds": [
      "d-2019-nascar-michael-mcdowell",
      "d-2019-nascar-matt-tifft"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 3,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-front-row-motorsports-team-1-team-2",
    "name": "Front Row Motorsports Team 1 team 2",
    "shortName": "",
    "carId": "car-2019-nascar-front-row-motorsports-team-1-team-2",
    "driverIds": [
      "d-2019-nascar-matt-crafton",
      "d-2019-nascar-john-hunter-nemechek"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 4,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-front-row-motorsports-team-2",
    "name": "Front Row Motorsports Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-front-row-motorsports-team-2",
    "driverIds": [
      "d-2019-nascar-david-ragan"
    ],
    "budget": 50,
    "reputation": 68,
    "raceOperations": 68,
    "morale": 65,
    "expectedStanding": 5,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-gaunt-brothers-racing",
    "name": "Gaunt Brothers Racing",
    "shortName": "",
    "carId": "car-2019-nascar-gaunt-brothers-racing",
    "driverIds": [
      "d-2019-nascar-parker-kligerman",
      "d-2019-nascar-drew-herring"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 6,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-germain-racing",
    "name": "Germain Racing",
    "shortName": "",
    "carId": "car-2019-nascar-germain-racing",
    "driverIds": [
      "d-2019-nascar-ty-dillon",
      "d-2019-nascar-casey-mears"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 7,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-go-fas-racing",
    "name": "Go Fas Racing",
    "shortName": "",
    "carId": "car-2019-nascar-go-fas-racing",
    "driverIds": [
      "d-2019-nascar-corey-lajoie"
    ],
    "budget": 50,
    "reputation": 69,
    "raceOperations": 69,
    "morale": 65,
    "expectedStanding": 8,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-hendrick-motorsports-team-1",
    "name": "Hendrick Motorsports Team 1",
    "shortName": "",
    "carId": "car-2019-nascar-hendrick-motorsports-team-1",
    "driverIds": [
      "d-2019-nascar-chase-elliott",
      "d-2019-nascar-william-byron"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 9,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-hendrick-motorsports-team-2",
    "name": "Hendrick Motorsports Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-hendrick-motorsports-team-2",
    "driverIds": [
      "d-2019-nascar-jimmie-johnson",
      "d-2019-nascar-alex-bowman"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 10,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-jtg-daugherty-racing",
    "name": "JTG Daugherty Racing",
    "shortName": "",
    "carId": "car-2019-nascar-jtg-daugherty-racing",
    "driverIds": [
      "d-2019-nascar-chris-buescher",
      "d-2019-nascar-ryan-preece"
    ],
    "budget": 50,
    "reputation": 76,
    "raceOperations": 76,
    "morale": 65,
    "expectedStanding": 11,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-joe-gibbs-racing-team-1",
    "name": "Joe Gibbs Racing Team 1",
    "shortName": "",
    "carId": "car-2019-nascar-joe-gibbs-racing-team-1",
    "driverIds": [
      "d-2019-nascar-denny-hamlin",
      "d-2019-nascar-kyle-busch"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 12,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-joe-gibbs-racing-team-2",
    "name": "Joe Gibbs Racing Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-joe-gibbs-racing-team-2",
    "driverIds": [
      "d-2019-nascar-martin-truex-jr",
      "d-2019-nascar-erik-jones"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 13,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-leavine-family-racing",
    "name": "Leavine Family Racing",
    "shortName": "",
    "carId": "car-2019-nascar-leavine-family-racing",
    "driverIds": [
      "d-2019-nascar-matt-dibenedetto"
    ],
    "budget": 50,
    "reputation": 77,
    "raceOperations": 77,
    "morale": 65,
    "expectedStanding": 14,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-mbm-motorsports-team-1",
    "name": "MBM Motorsports team 1",
    "shortName": "",
    "carId": "car-2019-nascar-mbm-motorsports-team-1",
    "driverIds": [
      "d-2019-nascar-joey-gase",
      "d-2019-nascar-brian-keselowski"
    ],
    "budget": 50,
    "reputation": 39,
    "raceOperations": 39,
    "morale": 65,
    "expectedStanding": 15,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-mbm-motorsports-team-2",
    "name": "MBM Motorsports team 2",
    "shortName": "",
    "carId": "car-2019-nascar-mbm-motorsports-team-2",
    "driverIds": [
      "d-2019-nascar-timmy-hill"
    ],
    "budget": 50,
    "reputation": 39,
    "raceOperations": 39,
    "morale": 65,
    "expectedStanding": 16,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-petty-ware-racing-team-1",
    "name": "Petty Ware Racing team 1",
    "shortName": "",
    "carId": "car-2019-nascar-petty-ware-racing-team-1",
    "driverIds": [
      "d-2019-nascar-b-j-mcleod",
      "d-2019-nascar-cody-ware"
    ],
    "budget": 50,
    "reputation": 57,
    "raceOperations": 57,
    "morale": 65,
    "expectedStanding": 17,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-petty-ware-racing-team-2",
    "name": "Petty Ware Racing team 2",
    "shortName": "",
    "carId": "car-2019-nascar-petty-ware-racing-team-2",
    "driverIds": [
      "d-2019-nascar-gray-gaulding",
      "d-2019-nascar-jeb-burton"
    ],
    "budget": 50,
    "reputation": 57,
    "raceOperations": 57,
    "morale": 65,
    "expectedStanding": 18,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-petty-ware-racing-team-3",
    "name": "Petty Ware Racing team 3",
    "shortName": "",
    "carId": "car-2019-nascar-petty-ware-racing-team-3",
    "driverIds": [
      "d-2019-nascar-bayley-currey",
      "d-2019-nascar-kyle-weatherman"
    ],
    "budget": 50,
    "reputation": 57,
    "raceOperations": 57,
    "morale": 65,
    "expectedStanding": 19,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-petty-ware-racing-team-4",
    "name": "Petty Ware Racing team 4",
    "shortName": "",
    "carId": "car-2019-nascar-petty-ware-racing-team-4",
    "driverIds": [
      "d-2019-nascar-j-j-yeley",
      "d-2019-nascar-andy-seuss"
    ],
    "budget": 50,
    "reputation": 57,
    "raceOperations": 57,
    "morale": 65,
    "expectedStanding": 20,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-petty-ware-racing-team-5",
    "name": "Petty Ware Racing team 5",
    "shortName": "",
    "carId": "car-2019-nascar-petty-ware-racing-team-5",
    "driverIds": [
      "d-2019-nascar-austin-theriault",
      "d-2019-nascar-josh-bilicki"
    ],
    "budget": 50,
    "reputation": 57,
    "raceOperations": 57,
    "morale": 65,
    "expectedStanding": 21,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-petty-ware-racing-team-6",
    "name": "Petty Ware Racing team 6",
    "shortName": "",
    "carId": "car-2019-nascar-petty-ware-racing-team-6",
    "driverIds": [
      "d-2019-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 57,
    "raceOperations": 57,
    "morale": 65,
    "expectedStanding": 22,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-premium-motorsports-team-1-team-1",
    "name": "Premium Motorsports Team 1 team 1",
    "shortName": "",
    "carId": "car-2019-nascar-premium-motorsports-team-1-team-1",
    "driverIds": [
      "d-2019-nascar-ross-chastain",
      "d-2019-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 56,
    "raceOperations": 56,
    "morale": 65,
    "expectedStanding": 23,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-premium-motorsports-team-1-team-2",
    "name": "Premium Motorsports Team 1 team 2",
    "shortName": "",
    "carId": "car-2019-nascar-premium-motorsports-team-1-team-2",
    "driverIds": [
      "d-2019-nascar-quin-houff",
      "d-2019-nascar-joe-nemechek"
    ],
    "budget": 50,
    "reputation": 56,
    "raceOperations": 56,
    "morale": 65,
    "expectedStanding": 24,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-premium-motorsports-team-2-team-1",
    "name": "Premium Motorsports Team 2 team 1",
    "shortName": "",
    "carId": "car-2019-nascar-premium-motorsports-team-2-team-1",
    "driverIds": [
      "d-2019-nascar-reed-sorenson",
      "d-2019-nascar-ross-chastain"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 25,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-premium-motorsports-team-2-team-2",
    "name": "Premium Motorsports Team 2 team 2",
    "shortName": "",
    "carId": "car-2019-nascar-premium-motorsports-team-2-team-2",
    "driverIds": [
      "d-2019-nascar-quin-houff",
      "d-2019-nascar-joe-nemechek"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 26,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-premium-motorsports-team-2-team-3",
    "name": "Premium Motorsports Team 2 team 3",
    "shortName": "",
    "carId": "car-2019-nascar-premium-motorsports-team-2-team-3",
    "driverIds": [
      "d-2019-nascar-ryan-sieg"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 27,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-richard-childress-racing-team-1",
    "name": "Richard Childress Racing Team 1",
    "shortName": "",
    "carId": "car-2019-nascar-richard-childress-racing-team-1",
    "driverIds": [
      "d-2019-nascar-austin-dillon",
      "d-2019-nascar-daniel-hemric"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 28,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-richard-childress-racing-team-2",
    "name": "Richard Childress Racing Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-richard-childress-racing-team-2",
    "driverIds": [
      "d-2019-nascar-tyler-reddick"
    ],
    "budget": 50,
    "reputation": 54,
    "raceOperations": 54,
    "morale": 65,
    "expectedStanding": 29,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-richard-petty-motorsports",
    "name": "Richard Petty Motorsports",
    "shortName": "",
    "carId": "car-2019-nascar-richard-petty-motorsports",
    "driverIds": [
      "d-2019-nascar-bubba-wallace"
    ],
    "budget": 50,
    "reputation": 71,
    "raceOperations": 71,
    "morale": 65,
    "expectedStanding": 30,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-1",
    "name": "Rick Ware Racing Team 1 team 1",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-1",
    "driverIds": [
      "d-2019-nascar-cody-ware",
      "d-2019-nascar-b-j-mcleod"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 31,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-2",
    "name": "Rick Ware Racing Team 1 team 2",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-2",
    "driverIds": [
      "d-2019-nascar-bayley-currey",
      "d-2019-nascar-jeb-burton"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 32,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-3",
    "name": "Rick Ware Racing Team 1 team 3",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-3",
    "driverIds": [
      "d-2019-nascar-stanton-barrett",
      "d-2019-nascar-j-j-yeley"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 33,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-4",
    "name": "Rick Ware Racing Team 1 team 4",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-4",
    "driverIds": [
      "d-2019-nascar-josh-bilicki",
      "d-2019-nascar-austin-theriault"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 34,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-5",
    "name": "Rick Ware Racing Team 1 team 5",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-5",
    "driverIds": [
      "d-2019-nascar-kyle-weatherman",
      "d-2019-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 35,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-6",
    "name": "Rick Ware Racing Team 1 team 6",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-6",
    "driverIds": [
      "d-2019-nascar-spencer-boyd",
      "d-2019-nascar-b-j-mcleod"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 36,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-7",
    "name": "Rick Ware Racing Team 1 team 7",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-7",
    "driverIds": [
      "d-2019-nascar-josh-bilicki",
      "d-2019-nascar-joey-gase"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 37,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-1-team-8",
    "name": "Rick Ware Racing Team 1 team 8",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-1-team-8",
    "driverIds": [
      "d-2019-nascar-spencer-boyd",
      "d-2019-nascar-j-j-yeley"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 38,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-rick-ware-racing-team-2",
    "name": "Rick Ware Racing Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-rick-ware-racing-team-2",
    "driverIds": [
      "d-2019-nascar-jeff-spraker",
      "d-2019-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 41,
    "raceOperations": 41,
    "morale": 65,
    "expectedStanding": 39,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-roush-fenway-racing",
    "name": "Roush Fenway Racing",
    "shortName": "",
    "carId": "car-2019-nascar-roush-fenway-racing",
    "driverIds": [
      "d-2019-nascar-ryan-newman",
      "d-2019-nascar-ricky-stenhouse-jr"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 40,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-spire-motorsports-team-1",
    "name": "Spire Motorsports team 1",
    "shortName": "",
    "carId": "car-2019-nascar-spire-motorsports-team-1",
    "driverIds": [
      "d-2019-nascar-jamie-mcmurray",
      "d-2019-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 61,
    "raceOperations": 61,
    "morale": 65,
    "expectedStanding": 41,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-spire-motorsports-team-2",
    "name": "Spire Motorsports team 2",
    "shortName": "",
    "carId": "car-2019-nascar-spire-motorsports-team-2",
    "driverIds": [
      "d-2019-nascar-reed-sorenson",
      "d-2019-nascar-quin-houff"
    ],
    "budget": 50,
    "reputation": 61,
    "raceOperations": 61,
    "morale": 65,
    "expectedStanding": 42,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-spire-motorsports-team-3",
    "name": "Spire Motorsports team 3",
    "shortName": "",
    "carId": "car-2019-nascar-spire-motorsports-team-3",
    "driverIds": [
      "d-2019-nascar-d-j-kennington",
      "d-2019-nascar-justin-haley"
    ],
    "budget": 50,
    "reputation": 61,
    "raceOperations": 61,
    "morale": 65,
    "expectedStanding": 43,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-spire-motorsports-team-4",
    "name": "Spire Motorsports team 4",
    "shortName": "",
    "carId": "car-2019-nascar-spire-motorsports-team-4",
    "driverIds": [
      "d-2019-nascar-blake-jones",
      "d-2019-nascar-timmy-hill"
    ],
    "budget": 50,
    "reputation": 61,
    "raceOperations": 61,
    "morale": 65,
    "expectedStanding": 44,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-starcom-racing",
    "name": "StarCom Racing",
    "shortName": "",
    "carId": "car-2019-nascar-starcom-racing",
    "driverIds": [
      "d-2019-nascar-landon-cassill"
    ],
    "budget": 50,
    "reputation": 52,
    "raceOperations": 52,
    "morale": 65,
    "expectedStanding": 45,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-stewart-haas-racing-team-1",
    "name": "Stewart-Haas Racing Team 1",
    "shortName": "",
    "carId": "car-2019-nascar-stewart-haas-racing-team-1",
    "driverIds": [
      "d-2019-nascar-kevin-harvick",
      "d-2019-nascar-aric-almirola"
    ],
    "budget": 50,
    "reputation": 92,
    "raceOperations": 92,
    "morale": 65,
    "expectedStanding": 46,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-stewart-haas-racing-team-2",
    "name": "Stewart-Haas Racing Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-stewart-haas-racing-team-2",
    "driverIds": [
      "d-2019-nascar-clint-bowyer",
      "d-2019-nascar-daniel-suarez"
    ],
    "budget": 50,
    "reputation": 87,
    "raceOperations": 87,
    "morale": 65,
    "expectedStanding": 47,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-team-penske-team-1",
    "name": "Team Penske Team 1",
    "shortName": "",
    "carId": "car-2019-nascar-team-penske-team-1",
    "driverIds": [
      "d-2019-nascar-brad-keselowski",
      "d-2019-nascar-ryan-blaney"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 48,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-team-penske-team-2",
    "name": "Team Penske Team 2",
    "shortName": "",
    "carId": "car-2019-nascar-team-penske-team-2",
    "driverIds": [
      "d-2019-nascar-joey-logano"
    ],
    "budget": 50,
    "reputation": 95,
    "raceOperations": 95,
    "morale": 65,
    "expectedStanding": 49,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-tommy-baldwin-racing",
    "name": "Tommy Baldwin Racing",
    "shortName": "",
    "carId": "car-2019-nascar-tommy-baldwin-racing",
    "driverIds": [
      "d-2019-nascar-ryan-truex"
    ],
    "budget": 50,
    "reputation": 30,
    "raceOperations": 30,
    "morale": 65,
    "expectedStanding": 50,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-wood-brothers-racing",
    "name": "Wood Brothers Racing",
    "shortName": "",
    "carId": "car-2019-nascar-wood-brothers-racing",
    "driverIds": [
      "d-2019-nascar-paul-menard"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 51,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2019-nascar-xci-racing",
    "name": "XCI Racing",
    "shortName": "",
    "carId": "car-2019-nascar-xci-racing",
    "driverIds": [
      "d-2019-nascar-jeffrey-earnhardt"
    ],
    "budget": 50,
    "reputation": 47,
    "raceOperations": 47,
    "morale": 65,
    "expectedStanding": 52,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  }
] as const satisfies Team[];

