// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Team,
} from '../../types/gameTypes';

export const teams2023NASCAR: Team[] = [
  {
    "id": "t-2023-nascar-23xi-racing-team-1",
    "name": "23XI Racing Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-23xi-racing-team-1",
    "driverIds": [
      "d-2023-nascar-bubba-wallace",
      "d-2023-nascar-tyler-reddick"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 1,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-23xi-racing-team-2",
    "name": "23XI Racing Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-23xi-racing-team-2",
    "driverIds": [
      "d-2023-nascar-travis-pastrana",
      "d-2023-nascar-kamui-kobayashi"
    ],
    "budget": 50,
    "reputation": 52,
    "raceOperations": 52,
    "morale": 65,
    "expectedStanding": 2,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-beard-motorsports",
    "name": "Beard Motorsports",
    "shortName": "",
    "carId": "car-2023-nascar-beard-motorsports",
    "driverIds": [
      "d-2023-nascar-austin-hill"
    ],
    "budget": 50,
    "reputation": 43,
    "raceOperations": 43,
    "morale": 65,
    "expectedStanding": 3,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-front-row-motorsports-team-1-team-1",
    "name": "Front Row Motorsports Team 1 team 1",
    "shortName": "",
    "carId": "car-2023-nascar-front-row-motorsports-team-1-team-1",
    "driverIds": [
      "d-2023-nascar-michael-mcdowell",
      "d-2023-nascar-todd-gilliland"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 4,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-front-row-motorsports-team-1-team-2",
    "name": "Front Row Motorsports Team 1 team 2",
    "shortName": "",
    "carId": "car-2023-nascar-front-row-motorsports-team-1-team-2",
    "driverIds": [
      "d-2023-nascar-zane-smith"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 5,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-front-row-motorsports-team-2-team-1",
    "name": "Front Row Motorsports Team 2 team 1",
    "shortName": "",
    "carId": "car-2023-nascar-front-row-motorsports-team-2-team-1",
    "driverIds": [
      "d-2023-nascar-zane-smith",
      "d-2023-nascar-todd-gilliland"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 6,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-front-row-motorsports-team-2-team-2",
    "name": "Front Row Motorsports Team 2 team 2",
    "shortName": "",
    "carId": "car-2023-nascar-front-row-motorsports-team-2-team-2",
    "driverIds": [
      "d-2023-nascar-riley-herbst"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 7,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-hendrick-motorsports-team-1-team-1",
    "name": "Hendrick Motorsports Team 1 team 1",
    "shortName": "",
    "carId": "car-2023-nascar-hendrick-motorsports-team-1-team-1",
    "driverIds": [
      "d-2023-nascar-kyle-larson",
      "d-2023-nascar-chase-elliott"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 8,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-hendrick-motorsports-team-1-team-2",
    "name": "Hendrick Motorsports Team 1 team 2",
    "shortName": "",
    "carId": "car-2023-nascar-hendrick-motorsports-team-1-team-2",
    "driverIds": [
      "d-2023-nascar-josh-berry",
      "d-2023-nascar-jordan-taylor"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 9,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-hendrick-motorsports-team-1-team-3",
    "name": "Hendrick Motorsports Team 1 team 3",
    "shortName": "",
    "carId": "car-2023-nascar-hendrick-motorsports-team-1-team-3",
    "driverIds": [
      "d-2023-nascar-corey-lajoie"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 10,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-hendrick-motorsports-team-2-team-1",
    "name": "Hendrick Motorsports Team 2 team 1",
    "shortName": "",
    "carId": "car-2023-nascar-hendrick-motorsports-team-2-team-1",
    "driverIds": [
      "d-2023-nascar-william-byron",
      "d-2023-nascar-alex-bowman"
    ],
    "budget": 50,
    "reputation": 92,
    "raceOperations": 92,
    "morale": 65,
    "expectedStanding": 11,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-hendrick-motorsports-team-2-team-2",
    "name": "Hendrick Motorsports Team 2 team 2",
    "shortName": "",
    "carId": "car-2023-nascar-hendrick-motorsports-team-2-team-2",
    "driverIds": [
      "d-2023-nascar-josh-berry"
    ],
    "budget": 50,
    "reputation": 92,
    "raceOperations": 92,
    "morale": 65,
    "expectedStanding": 12,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-jtg-daugherty-racing",
    "name": "JTG Daugherty Racing",
    "shortName": "",
    "carId": "car-2023-nascar-jtg-daugherty-racing",
    "driverIds": [
      "d-2023-nascar-ricky-stenhouse-jr"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 13,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-joe-gibbs-racing-team-1",
    "name": "Joe Gibbs Racing Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-joe-gibbs-racing-team-1",
    "driverIds": [
      "d-2023-nascar-denny-hamlin",
      "d-2023-nascar-martin-truex-jr"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 14,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-joe-gibbs-racing-team-2",
    "name": "Joe Gibbs Racing Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-joe-gibbs-racing-team-2",
    "driverIds": [
      "d-2023-nascar-christopher-bell",
      "d-2023-nascar-ty-gibbs"
    ],
    "budget": 50,
    "reputation": 92,
    "raceOperations": 92,
    "morale": 65,
    "expectedStanding": 15,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-kaulig-racing-team-1",
    "name": "Kaulig Racing Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-kaulig-racing-team-1",
    "driverIds": [
      "d-2023-nascar-a-j-allmendinger",
      "d-2023-nascar-justin-haley"
    ],
    "budget": 50,
    "reputation": 73,
    "raceOperations": 73,
    "morale": 65,
    "expectedStanding": 16,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-kaulig-racing-team-2",
    "name": "Kaulig Racing Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-kaulig-racing-team-2",
    "driverIds": [
      "d-2023-nascar-chandler-smith",
      "d-2023-nascar-jonathan-davenport"
    ],
    "budget": 50,
    "reputation": 50,
    "raceOperations": 50,
    "morale": 65,
    "expectedStanding": 17,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-legacy-motor-club-team-1-team-1",
    "name": "Legacy Motor Club Team 1 team 1",
    "shortName": "",
    "carId": "car-2023-nascar-legacy-motor-club-team-1-team-1",
    "driverIds": [
      "d-2023-nascar-noah-gragson",
      "d-2023-nascar-grant-enfinger"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 18,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-legacy-motor-club-team-1-team-2",
    "name": "Legacy Motor Club Team 1 team 2",
    "shortName": "",
    "carId": "car-2023-nascar-legacy-motor-club-team-1-team-2",
    "driverIds": [
      "d-2023-nascar-josh-berry",
      "d-2023-nascar-mike-rockenfeller"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 19,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-legacy-motor-club-team-1-team-3",
    "name": "Legacy Motor Club Team 1 team 3",
    "shortName": "",
    "carId": "car-2023-nascar-legacy-motor-club-team-1-team-3",
    "driverIds": [
      "d-2023-nascar-carson-hocevar",
      "d-2023-nascar-john-hunter-nemechek"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 20,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-legacy-motor-club-team-1-team-4",
    "name": "Legacy Motor Club Team 1 team 4",
    "shortName": "",
    "carId": "car-2023-nascar-legacy-motor-club-team-1-team-4",
    "driverIds": [
      "d-2023-nascar-erik-jones"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 21,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-legacy-motor-club-team-2",
    "name": "Legacy Motor Club Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-legacy-motor-club-team-2",
    "driverIds": [
      "d-2023-nascar-jimmie-johnson"
    ],
    "budget": 50,
    "reputation": 53,
    "raceOperations": 53,
    "morale": 65,
    "expectedStanding": 22,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-live-fast-motorsports-team-1",
    "name": "Live Fast Motorsports team 1",
    "shortName": "",
    "carId": "car-2023-nascar-live-fast-motorsports-team-1",
    "driverIds": [
      "d-2023-nascar-b-j-mcleod",
      "d-2023-nascar-josh-bilicki"
    ],
    "budget": 50,
    "reputation": 43,
    "raceOperations": 43,
    "morale": 65,
    "expectedStanding": 23,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-live-fast-motorsports-team-2",
    "name": "Live Fast Motorsports team 2",
    "shortName": "",
    "carId": "car-2023-nascar-live-fast-motorsports-team-2",
    "driverIds": [
      "d-2023-nascar-anthony-alfredo",
      "d-2023-nascar-sheldon-creed"
    ],
    "budget": 50,
    "reputation": 43,
    "raceOperations": 43,
    "morale": 65,
    "expectedStanding": 24,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rfk-racing",
    "name": "RFK Racing",
    "shortName": "",
    "carId": "car-2023-nascar-rfk-racing",
    "driverIds": [
      "d-2023-nascar-brad-keselowski",
      "d-2023-nascar-chris-buescher"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 25,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-richard-childress-racing-team-1",
    "name": "Richard Childress Racing Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-richard-childress-racing-team-1",
    "driverIds": [
      "d-2023-nascar-austin-dillon",
      "d-2023-nascar-kyle-busch"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 26,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-richard-childress-racing-team-2",
    "name": "Richard Childress Racing Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-richard-childress-racing-team-2",
    "driverIds": [
      "d-2023-nascar-brodie-kostecki"
    ],
    "budget": 50,
    "reputation": 54,
    "raceOperations": 54,
    "morale": 65,
    "expectedStanding": 27,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-1",
    "name": "Rick Ware Racing team 1",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-1",
    "driverIds": [
      "d-2023-nascar-riley-herbst",
      "d-2023-nascar-j-j-yeley"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 28,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-2",
    "name": "Rick Ware Racing team 2",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-2",
    "driverIds": [
      "d-2023-nascar-todd-gilliland",
      "d-2023-nascar-jenson-button"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 29,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-3",
    "name": "Rick Ware Racing team 3",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-3",
    "driverIds": [
      "d-2023-nascar-brennan-poole",
      "d-2023-nascar-gray-gaulding"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 30,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-4",
    "name": "Rick Ware Racing team 4",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-4",
    "driverIds": [
      "d-2023-nascar-andy-lally",
      "d-2023-nascar-ryan-newman"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 31,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-5",
    "name": "Rick Ware Racing team 5",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-5",
    "driverIds": [
      "d-2023-nascar-cody-ware",
      "d-2023-nascar-matt-crafton"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 32,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-6",
    "name": "Rick Ware Racing team 6",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-6",
    "driverIds": [
      "d-2023-nascar-zane-smith",
      "d-2023-nascar-j-j-yeley"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 33,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-7",
    "name": "Rick Ware Racing team 7",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-7",
    "driverIds": [
      "d-2023-nascar-ryan-newman",
      "d-2023-nascar-todd-gilliland"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 34,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-rick-ware-racing-team-8",
    "name": "Rick Ware Racing team 8",
    "shortName": "",
    "carId": "car-2023-nascar-rick-ware-racing-team-8",
    "driverIds": [
      "d-2023-nascar-andy-lally",
      "d-2023-nascar-cole-custer"
    ],
    "budget": 50,
    "reputation": 66,
    "raceOperations": 66,
    "morale": 65,
    "expectedStanding": 35,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-spire-motorsports-team-1",
    "name": "Spire Motorsports team 1",
    "shortName": "",
    "carId": "car-2023-nascar-spire-motorsports-team-1",
    "driverIds": [
      "d-2023-nascar-corey-lajoie",
      "d-2023-nascar-carson-hocevar"
    ],
    "budget": 50,
    "reputation": 69,
    "raceOperations": 69,
    "morale": 65,
    "expectedStanding": 36,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-spire-motorsports-team-2",
    "name": "Spire Motorsports team 2",
    "shortName": "",
    "carId": "car-2023-nascar-spire-motorsports-team-2",
    "driverIds": [
      "d-2023-nascar-ty-dillon"
    ],
    "budget": 50,
    "reputation": 69,
    "raceOperations": 69,
    "morale": 65,
    "expectedStanding": 37,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-stewart-haas-racing-team-1",
    "name": "Stewart-Haas Racing Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-stewart-haas-racing-team-1",
    "driverIds": [
      "d-2023-nascar-kevin-harvick",
      "d-2023-nascar-aric-almirola"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 38,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-stewart-haas-racing-team-2",
    "name": "Stewart-Haas Racing Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-stewart-haas-racing-team-2",
    "driverIds": [
      "d-2023-nascar-chase-briscoe",
      "d-2023-nascar-ryan-preece"
    ],
    "budget": 50,
    "reputation": 71,
    "raceOperations": 71,
    "morale": 65,
    "expectedStanding": 39,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-team-penske-team-1",
    "name": "Team Penske Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-team-penske-team-1",
    "driverIds": [
      "d-2023-nascar-austin-cindric",
      "d-2023-nascar-ryan-blaney"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 40,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-team-penske-team-2",
    "name": "Team Penske Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-team-penske-team-2",
    "driverIds": [
      "d-2023-nascar-joey-logano"
    ],
    "budget": 50,
    "reputation": 83,
    "raceOperations": 83,
    "morale": 65,
    "expectedStanding": 41,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-the-money-team-racing",
    "name": "The Money Team Racing",
    "shortName": "",
    "carId": "car-2023-nascar-the-money-team-racing",
    "driverIds": [
      "d-2023-nascar-conor-daly"
    ],
    "budget": 50,
    "reputation": 43,
    "raceOperations": 43,
    "morale": 65,
    "expectedStanding": 42,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-trackhouse-racing-team-1",
    "name": "Trackhouse Racing Team 1",
    "shortName": "",
    "carId": "car-2023-nascar-trackhouse-racing-team-1",
    "driverIds": [
      "d-2023-nascar-ross-chastain",
      "d-2023-nascar-daniel-suarez"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 43,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-trackhouse-racing-team-2",
    "name": "Trackhouse Racing Team 2",
    "shortName": "",
    "carId": "car-2023-nascar-trackhouse-racing-team-2",
    "driverIds": [
      "d-2023-nascar-kimi-raikkonen",
      "d-2023-nascar-shane-van-gisbergen"
    ],
    "budget": 50,
    "reputation": 53,
    "raceOperations": 53,
    "morale": 65,
    "expectedStanding": 44,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2023-nascar-wood-brothers-racing",
    "name": "Wood Brothers Racing",
    "shortName": "",
    "carId": "car-2023-nascar-wood-brothers-racing",
    "driverIds": [
      "d-2023-nascar-harrison-burton"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 45,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  }
] as const satisfies Team[];

