// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Team,
} from '../../types/gameTypes';

export const teams1994NASCAR: Team[] = [
  {
    "id": "t-1994-nascar-a-g-dillard-motorsports",
    "name": "A. G. Dillard Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-a-g-dillard-motorsports",
    "driverIds": [
      "d-1994-nascar-ward-burton"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 1,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-active-motorsports",
    "name": "Active Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-active-motorsports",
    "driverIds": [
      "d-1994-nascar-dick-trickle"
    ],
    "budget": 50,
    "reputation": 83,
    "raceOperations": 83,
    "morale": 65,
    "expectedStanding": 2,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-bahari-racing",
    "name": "Bahari Racing",
    "shortName": "",
    "carId": "car-1994-nascar-bahari-racing",
    "driverIds": [
      "d-1994-nascar-michael-waltrip"
    ],
    "budget": 50,
    "reputation": 96,
    "raceOperations": 96,
    "morale": 65,
    "expectedStanding": 3,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-bill-davis-racing",
    "name": "Bill Davis Racing",
    "shortName": "",
    "carId": "car-1994-nascar-bill-davis-racing",
    "driverIds": [
      "d-1994-nascar-bobby-labonte"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 4,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-bobby-allison-motorsports-team-1",
    "name": "Bobby Allison Motorsports team 1",
    "shortName": "",
    "carId": "car-1994-nascar-bobby-allison-motorsports-team-1",
    "driverIds": [
      "d-1994-nascar-chuck-bown",
      "d-1994-nascar-tim-steele"
    ],
    "budget": 50,
    "reputation": 81,
    "raceOperations": 81,
    "morale": 65,
    "expectedStanding": 5,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-bobby-allison-motorsports-team-2",
    "name": "Bobby Allison Motorsports team 2",
    "shortName": "",
    "carId": "car-1994-nascar-bobby-allison-motorsports-team-2",
    "driverIds": [
      "d-1994-nascar-derrike-cope"
    ],
    "budget": 50,
    "reputation": 81,
    "raceOperations": 81,
    "morale": 65,
    "expectedStanding": 6,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-bud-moore-engineering",
    "name": "Bud Moore Engineering",
    "shortName": "",
    "carId": "car-1994-nascar-bud-moore-engineering",
    "driverIds": [
      "d-1994-nascar-lake-speed"
    ],
    "budget": 50,
    "reputation": 95,
    "raceOperations": 95,
    "morale": 65,
    "expectedStanding": 7,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-butch-mock-motorsports",
    "name": "Butch Mock Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-butch-mock-motorsports",
    "driverIds": [
      "d-1994-nascar-todd-bodine"
    ],
    "budget": 50,
    "reputation": 89,
    "raceOperations": 89,
    "morale": 65,
    "expectedStanding": 8,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-cale-yarborough-motorsports",
    "name": "Cale Yarborough Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-cale-yarborough-motorsports",
    "driverIds": [
      "d-1994-nascar-derrike-cope",
      "d-1994-nascar-jeremy-mayfield"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 9,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-darrell-waltrip-motorsports",
    "name": "Darrell Waltrip Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-darrell-waltrip-motorsports",
    "driverIds": [
      "d-1994-nascar-darrell-waltrip"
    ],
    "budget": 50,
    "reputation": 95,
    "raceOperations": 95,
    "morale": 65,
    "expectedStanding": 10,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-diamond-ridge-motorsports",
    "name": "Diamond Ridge Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-diamond-ridge-motorsports",
    "driverIds": [
      "d-1994-nascar-steve-grissom"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 11,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-donlavey-racing",
    "name": "Donlavey Racing",
    "shortName": "",
    "carId": "car-1994-nascar-donlavey-racing",
    "driverIds": [
      "d-1994-nascar-bobby-hillin-jr",
      "d-1994-nascar-mike-wallace"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 12,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-geoff-bodine-racing",
    "name": "Geoff Bodine Racing",
    "shortName": "",
    "carId": "car-1994-nascar-geoff-bodine-racing",
    "driverIds": [
      "d-1994-nascar-geoff-bodine"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 13,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-hendrick-motorsports-team-1",
    "name": "Hendrick Motorsports Team 1",
    "shortName": "",
    "carId": "car-1994-nascar-hendrick-motorsports-team-1",
    "driverIds": [
      "d-1994-nascar-terry-labonte",
      "d-1994-nascar-jeff-gordon"
    ],
    "budget": 50,
    "reputation": 97,
    "raceOperations": 97,
    "morale": 65,
    "expectedStanding": 14,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-hendrick-motorsports-team-2",
    "name": "Hendrick Motorsports Team 2",
    "shortName": "",
    "carId": "car-1994-nascar-hendrick-motorsports-team-2",
    "driverIds": [
      "d-1994-nascar-ken-schrader"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 15,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-joe-gibbs-racing",
    "name": "Joe Gibbs Racing",
    "shortName": "",
    "carId": "car-1994-nascar-joe-gibbs-racing",
    "driverIds": [
      "d-1994-nascar-dale-jarrett"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 16,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-junior-johnson-associates-team-1-team-1",
    "name": "Junior Johnson & Associates Team 1 team 1",
    "shortName": "",
    "carId": "car-1994-nascar-junior-johnson-associates-team-1-team-1",
    "driverIds": [
      "d-1994-nascar-bill-elliott",
      "d-1994-nascar-jimmy-spencer"
    ],
    "budget": 50,
    "reputation": 87,
    "raceOperations": 87,
    "morale": 65,
    "expectedStanding": 17,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-junior-johnson-associates-team-1-team-2",
    "name": "Junior Johnson & Associates Team 1 team 2",
    "shortName": "",
    "carId": "car-1994-nascar-junior-johnson-associates-team-1-team-2",
    "driverIds": [
      "d-1994-nascar-tommy-kendall"
    ],
    "budget": 50,
    "reputation": 87,
    "raceOperations": 87,
    "morale": 65,
    "expectedStanding": 18,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-king-racing",
    "name": "King Racing",
    "shortName": "",
    "carId": "car-1994-nascar-king-racing",
    "driverIds": [
      "d-1994-nascar-brett-bodine"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 19,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-larry-hedrick-motorsports",
    "name": "Larry Hedrick Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-larry-hedrick-motorsports",
    "driverIds": [
      "d-1994-nascar-joe-nemechek"
    ],
    "budget": 50,
    "reputation": 85,
    "raceOperations": 85,
    "morale": 65,
    "expectedStanding": 20,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-leo-jackson-motorsports",
    "name": "Leo Jackson Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-leo-jackson-motorsports",
    "driverIds": [
      "d-1994-nascar-harry-gant"
    ],
    "budget": 50,
    "reputation": 85,
    "raceOperations": 85,
    "morale": 65,
    "expectedStanding": 21,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-marcis-auto-racing",
    "name": "Marcis Auto Racing",
    "shortName": "",
    "carId": "car-1994-nascar-marcis-auto-racing",
    "driverIds": [
      "d-1994-nascar-dave-marcis"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 22,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-morgan-mcclure-motorsports",
    "name": "Morgan-McClure Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-morgan-mcclure-motorsports",
    "driverIds": [
      "d-1994-nascar-sterling-marlin"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 23,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-penske-racing",
    "name": "Penske Racing",
    "shortName": "",
    "carId": "car-1994-nascar-penske-racing",
    "driverIds": [
      "d-1994-nascar-rusty-wallace"
    ],
    "budget": 50,
    "reputation": 96,
    "raceOperations": 96,
    "morale": 65,
    "expectedStanding": 24,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-petty-enterprises",
    "name": "Petty Enterprises",
    "shortName": "",
    "carId": "car-1994-nascar-petty-enterprises",
    "driverIds": [
      "d-1994-nascar-wally-dallenbach-jr",
      "d-1994-nascar-john-andretti"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 25,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-precision-products-racing",
    "name": "Precision Products Racing",
    "shortName": "",
    "carId": "car-1994-nascar-precision-products-racing",
    "driverIds": [
      "d-1994-nascar-rick-mast"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 26,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-richard-childress-racing",
    "name": "Richard Childress Racing",
    "shortName": "",
    "carId": "car-1994-nascar-richard-childress-racing",
    "driverIds": [
      "d-1994-nascar-dale-earnhardt"
    ],
    "budget": 50,
    "reputation": 99,
    "raceOperations": 99,
    "morale": 65,
    "expectedStanding": 27,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-robert-yates-racing",
    "name": "Robert Yates Racing",
    "shortName": "",
    "carId": "car-1994-nascar-robert-yates-racing",
    "driverIds": [
      "d-1994-nascar-ernie-irvan",
      "d-1994-nascar-kenny-wallace"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 28,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-roush-racing-team-1",
    "name": "Roush Racing Team 1",
    "shortName": "",
    "carId": "car-1994-nascar-roush-racing-team-1",
    "driverIds": [
      "d-1994-nascar-mark-martin",
      "d-1994-nascar-ted-musgrave"
    ],
    "budget": 50,
    "reputation": 97,
    "raceOperations": 97,
    "morale": 65,
    "expectedStanding": 29,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-rudd-performance-motorsports",
    "name": "Rudd Performance Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-rudd-performance-motorsports",
    "driverIds": [
      "d-1994-nascar-ricky-rudd"
    ],
    "budget": 50,
    "reputation": 95,
    "raceOperations": 95,
    "morale": 65,
    "expectedStanding": 30,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-sabco-racing-team-1",
    "name": "SABCO Racing Team 1",
    "shortName": "",
    "carId": "car-1994-nascar-sabco-racing-team-1",
    "driverIds": [
      "d-1994-nascar-bobby-hamilton",
      "d-1994-nascar-kyle-petty"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 31,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-smokin-joe-s-racing",
    "name": "Smokin' Joe's Racing",
    "shortName": "",
    "carId": "car-1994-nascar-smokin-joe-s-racing",
    "driverIds": [
      "d-1994-nascar-hut-stricklin"
    ],
    "budget": 50,
    "reputation": 87,
    "raceOperations": 87,
    "morale": 65,
    "expectedStanding": 32,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-stavola-brothers-racing",
    "name": "Stavola Brothers Racing",
    "shortName": "",
    "carId": "car-1994-nascar-stavola-brothers-racing",
    "driverIds": [
      "d-1994-nascar-jeff-burton"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 33,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-tri-star-motorsports",
    "name": "Tri-Star Motorsports",
    "shortName": "",
    "carId": "car-1994-nascar-tri-star-motorsports",
    "driverIds": [
      "d-1994-nascar-loy-allen-jr"
    ],
    "budget": 50,
    "reputation": 76,
    "raceOperations": 76,
    "morale": 65,
    "expectedStanding": 34,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-u-s-racing",
    "name": "U.S. Racing",
    "shortName": "",
    "carId": "car-1994-nascar-u-s-racing",
    "driverIds": [
      "d-1994-nascar-greg-sacks"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 35,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1994-nascar-wood-brothers-racing",
    "name": "Wood Brothers Racing",
    "shortName": "",
    "carId": "car-1994-nascar-wood-brothers-racing",
    "driverIds": [
      "d-1994-nascar-morgan-shepherd"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 36,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  }
] as const satisfies Team[];

