// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Team,
} from '../../types/gameTypes';

export const teams2022NASCAR: Team[] = [
  {
    "id": "t-2022-nascar-23xi-racing-team-1",
    "name": "23XI Racing team 1",
    "shortName": "",
    "carId": "car-2022-nascar-23xi-racing-team-1",
    "driverIds": [
      "d-2022-nascar-bubba-wallace",
      "d-2022-nascar-ty-gibbs"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 1,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-23xi-racing-team-2",
    "name": "23XI Racing team 2",
    "shortName": "",
    "carId": "car-2022-nascar-23xi-racing-team-2",
    "driverIds": [
      "d-2022-nascar-daniel-hemric",
      "d-2022-nascar-kurt-busch"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 2,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-23xi-racing-team-3",
    "name": "23XI Racing team 3",
    "shortName": "",
    "carId": "car-2022-nascar-23xi-racing-team-3",
    "driverIds": [
      "d-2022-nascar-ty-gibbs",
      "d-2022-nascar-bubba-wallace"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 3,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-23xi-racing-team-4",
    "name": "23XI Racing team 4",
    "shortName": "",
    "carId": "car-2022-nascar-23xi-racing-team-4",
    "driverIds": [
      "d-2022-nascar-john-hunter-nemechek"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 4,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-beard-motorsports",
    "name": "Beard Motorsports",
    "shortName": "",
    "carId": "car-2022-nascar-beard-motorsports",
    "driverIds": [
      "d-2022-nascar-noah-gragson",
      "d-2022-nascar-justin-allgaier"
    ],
    "budget": 50,
    "reputation": 45,
    "raceOperations": 45,
    "morale": 65,
    "expectedStanding": 5,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-front-row-motorsports",
    "name": "Front Row Motorsports",
    "shortName": "",
    "carId": "car-2022-nascar-front-row-motorsports",
    "driverIds": [
      "d-2022-nascar-michael-mcdowell",
      "d-2022-nascar-todd-gilliland"
    ],
    "budget": 50,
    "reputation": 71,
    "raceOperations": 71,
    "morale": 65,
    "expectedStanding": 6,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-hendrick-motorsports-team-1",
    "name": "Hendrick Motorsports Team 1",
    "shortName": "",
    "carId": "car-2022-nascar-hendrick-motorsports-team-1",
    "driverIds": [
      "d-2022-nascar-kyle-larson",
      "d-2022-nascar-chase-elliott"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 7,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-hendrick-motorsports-team-2-team-1",
    "name": "Hendrick Motorsports Team 2 team 1",
    "shortName": "",
    "carId": "car-2022-nascar-hendrick-motorsports-team-2-team-1",
    "driverIds": [
      "d-2022-nascar-william-byron",
      "d-2022-nascar-alex-bowman"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 8,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-hendrick-motorsports-team-2-team-2",
    "name": "Hendrick Motorsports Team 2 team 2",
    "shortName": "",
    "carId": "car-2022-nascar-hendrick-motorsports-team-2-team-2",
    "driverIds": [
      "d-2022-nascar-noah-gragson"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 9,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-jtg-daugherty-racing",
    "name": "JTG Daugherty Racing",
    "shortName": "",
    "carId": "car-2022-nascar-jtg-daugherty-racing",
    "driverIds": [
      "d-2022-nascar-ricky-stenhouse-jr"
    ],
    "budget": 50,
    "reputation": 69,
    "raceOperations": 69,
    "morale": 65,
    "expectedStanding": 10,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-joe-gibbs-racing-team-1",
    "name": "Joe Gibbs Racing Team 1",
    "shortName": "",
    "carId": "car-2022-nascar-joe-gibbs-racing-team-1",
    "driverIds": [
      "d-2022-nascar-denny-hamlin",
      "d-2022-nascar-kyle-busch"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 11,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-joe-gibbs-racing-team-2",
    "name": "Joe Gibbs Racing Team 2",
    "shortName": "",
    "carId": "car-2022-nascar-joe-gibbs-racing-team-2",
    "driverIds": [
      "d-2022-nascar-martin-truex-jr",
      "d-2022-nascar-christopher-bell"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 12,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-kaulig-racing-team-1",
    "name": "Kaulig Racing team 1",
    "shortName": "",
    "carId": "car-2022-nascar-kaulig-racing-team-1",
    "driverIds": [
      "d-2022-nascar-daniel-hemric",
      "d-2022-nascar-a-j-allmendinger"
    ],
    "budget": 50,
    "reputation": 70,
    "raceOperations": 70,
    "morale": 65,
    "expectedStanding": 13,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-kaulig-racing-team-2",
    "name": "Kaulig Racing team 2",
    "shortName": "",
    "carId": "car-2022-nascar-kaulig-racing-team-2",
    "driverIds": [
      "d-2022-nascar-noah-gragson",
      "d-2022-nascar-justin-haley"
    ],
    "budget": 50,
    "reputation": 70,
    "raceOperations": 70,
    "morale": 65,
    "expectedStanding": 14,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-live-fast-motorsports-team-1",
    "name": "Live Fast Motorsports team 1",
    "shortName": "",
    "carId": "car-2022-nascar-live-fast-motorsports-team-1",
    "driverIds": [
      "d-2022-nascar-b-j-mcleod",
      "d-2022-nascar-andy-lally"
    ],
    "budget": 50,
    "reputation": 53,
    "raceOperations": 53,
    "morale": 65,
    "expectedStanding": 15,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-live-fast-motorsports-team-2",
    "name": "Live Fast Motorsports team 2",
    "shortName": "",
    "carId": "car-2022-nascar-live-fast-motorsports-team-2",
    "driverIds": [
      "d-2022-nascar-josh-williams",
      "d-2022-nascar-scott-heckert"
    ],
    "budget": 50,
    "reputation": 53,
    "raceOperations": 53,
    "morale": 65,
    "expectedStanding": 16,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-live-fast-motorsports-team-3",
    "name": "Live Fast Motorsports team 3",
    "shortName": "",
    "carId": "car-2022-nascar-live-fast-motorsports-team-3",
    "driverIds": [
      "d-2022-nascar-kyle-tilley"
    ],
    "budget": 50,
    "reputation": 53,
    "raceOperations": 53,
    "morale": 65,
    "expectedStanding": 17,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-mbm-motorsports-team-1",
    "name": "MBM Motorsports team 1",
    "shortName": "",
    "carId": "car-2022-nascar-mbm-motorsports-team-1",
    "driverIds": [
      "d-2022-nascar-j-j-yeley",
      "d-2022-nascar-timmy-hill"
    ],
    "budget": 50,
    "reputation": 52,
    "raceOperations": 52,
    "morale": 65,
    "expectedStanding": 18,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-mbm-motorsports-team-2",
    "name": "MBM Motorsports team 2",
    "shortName": "",
    "carId": "car-2022-nascar-mbm-motorsports-team-2",
    "driverIds": [
      "d-2022-nascar-boris-said"
    ],
    "budget": 50,
    "reputation": 52,
    "raceOperations": 52,
    "morale": 65,
    "expectedStanding": 19,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-petty-gms-motorsports",
    "name": "Petty GMS Motorsports",
    "shortName": "",
    "carId": "car-2022-nascar-petty-gms-motorsports",
    "driverIds": [
      "d-2022-nascar-ty-dillon"
    ],
    "budget": 50,
    "reputation": 65,
    "raceOperations": 65,
    "morale": 65,
    "expectedStanding": 20,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-rfk-racing-team-1",
    "name": "RFK Racing team 1",
    "shortName": "",
    "carId": "car-2022-nascar-rfk-racing-team-1",
    "driverIds": [
      "d-2022-nascar-brad-keselowski",
      "d-2022-nascar-chris-buescher"
    ],
    "budget": 50,
    "reputation": 74,
    "raceOperations": 74,
    "morale": 65,
    "expectedStanding": 21,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-rfk-racing-team-2",
    "name": "RFK Racing team 2",
    "shortName": "",
    "carId": "car-2022-nascar-rfk-racing-team-2",
    "driverIds": [
      "d-2022-nascar-zane-smith"
    ],
    "budget": 50,
    "reputation": 74,
    "raceOperations": 74,
    "morale": 65,
    "expectedStanding": 22,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-richard-childress-racing",
    "name": "Richard Childress Racing",
    "shortName": "",
    "carId": "car-2022-nascar-richard-childress-racing",
    "driverIds": [
      "d-2022-nascar-tyler-reddick",
      "d-2022-nascar-austin-hill"
    ],
    "budget": 50,
    "reputation": 76,
    "raceOperations": 76,
    "morale": 65,
    "expectedStanding": 23,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-richard-childress-racing-team-1",
    "name": "Richard Childress Racing Team 1",
    "shortName": "",
    "carId": "car-2022-nascar-richard-childress-racing-team-1",
    "driverIds": [
      "d-2022-nascar-erik-jones",
      "d-2022-nascar-austin-dillon"
    ],
    "budget": 50,
    "reputation": 85,
    "raceOperations": 85,
    "morale": 65,
    "expectedStanding": 24,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-richard-childress-racing-team-2",
    "name": "Richard Childress Racing Team 2",
    "shortName": "",
    "carId": "car-2022-nascar-richard-childress-racing-team-2",
    "driverIds": [
      "d-2022-nascar-greg-biffle"
    ],
    "budget": 50,
    "reputation": 58,
    "raceOperations": 58,
    "morale": 65,
    "expectedStanding": 25,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-rick-ware-racing-team-1",
    "name": "Rick Ware Racing team 1",
    "shortName": "",
    "carId": "car-2022-nascar-rick-ware-racing-team-1",
    "driverIds": [
      "d-2022-nascar-david-ragan",
      "d-2022-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 26,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-rick-ware-racing-team-2",
    "name": "Rick Ware Racing team 2",
    "shortName": "",
    "carId": "car-2022-nascar-rick-ware-racing-team-2",
    "driverIds": [
      "d-2022-nascar-joey-hand",
      "d-2022-nascar-j-j-yeley"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 27,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-rick-ware-racing-team-3",
    "name": "Rick Ware Racing team 3",
    "shortName": "",
    "carId": "car-2022-nascar-rick-ware-racing-team-3",
    "driverIds": [
      "d-2022-nascar-ryan-preece",
      "d-2022-nascar-parker-kligerman"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 28,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-rick-ware-racing-team-4",
    "name": "Rick Ware Racing team 4",
    "shortName": "",
    "carId": "car-2022-nascar-rick-ware-racing-team-4",
    "driverIds": [
      "d-2022-nascar-cody-ware",
      "d-2022-nascar-j-j-yeley"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 29,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-spire-motorsports-team-1",
    "name": "Spire Motorsports team 1",
    "shortName": "",
    "carId": "car-2022-nascar-spire-motorsports-team-1",
    "driverIds": [
      "d-2022-nascar-corey-lajoie",
      "d-2022-nascar-landon-cassill"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 30,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-spire-motorsports-team-2",
    "name": "Spire Motorsports team 2",
    "shortName": "",
    "carId": "car-2022-nascar-spire-motorsports-team-2",
    "driverIds": [
      "d-2022-nascar-josh-bilicki",
      "d-2022-nascar-justin-allgaier"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 31,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-spire-motorsports-team-3",
    "name": "Spire Motorsports team 3",
    "shortName": "",
    "carId": "car-2022-nascar-spire-motorsports-team-3",
    "driverIds": [
      "d-2022-nascar-mike-rockenfeller"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 32,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-stewart-haas-racing-team-1",
    "name": "Stewart-Haas Racing Team 1",
    "shortName": "",
    "carId": "car-2022-nascar-stewart-haas-racing-team-1",
    "driverIds": [
      "d-2022-nascar-kevin-harvick",
      "d-2022-nascar-aric-almirola"
    ],
    "budget": 50,
    "reputation": 81,
    "raceOperations": 81,
    "morale": 65,
    "expectedStanding": 33,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-stewart-haas-racing-team-2",
    "name": "Stewart-Haas Racing Team 2",
    "shortName": "",
    "carId": "car-2022-nascar-stewart-haas-racing-team-2",
    "driverIds": [
      "d-2022-nascar-chase-briscoe",
      "d-2022-nascar-cole-custer"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 34,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-team-hezeberg-team-1",
    "name": "Team Hezeberg team 1",
    "shortName": "",
    "carId": "car-2022-nascar-team-hezeberg-team-1",
    "driverIds": [
      "d-2022-nascar-jacques-villeneuve",
      "d-2022-nascar-loris-hezemans"
    ],
    "budget": 50,
    "reputation": 52,
    "raceOperations": 52,
    "morale": 65,
    "expectedStanding": 35,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-team-hezeberg-team-2",
    "name": "Team Hezeberg team 2",
    "shortName": "",
    "carId": "car-2022-nascar-team-hezeberg-team-2",
    "driverIds": [
      "d-2022-nascar-daniil-kvyat"
    ],
    "budget": 50,
    "reputation": 52,
    "raceOperations": 52,
    "morale": 65,
    "expectedStanding": 36,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-team-penske-team-1",
    "name": "Team Penske Team 1",
    "shortName": "",
    "carId": "car-2022-nascar-team-penske-team-1",
    "driverIds": [
      "d-2022-nascar-austin-cindric",
      "d-2022-nascar-ryan-blaney"
    ],
    "budget": 50,
    "reputation": 89,
    "raceOperations": 89,
    "morale": 65,
    "expectedStanding": 37,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-team-penske-team-2",
    "name": "Team Penske Team 2",
    "shortName": "",
    "carId": "car-2022-nascar-team-penske-team-2",
    "driverIds": [
      "d-2022-nascar-joey-logano"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 38,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-the-money-team-racing",
    "name": "The Money Team Racing",
    "shortName": "",
    "carId": "car-2022-nascar-the-money-team-racing",
    "driverIds": [
      "d-2022-nascar-kaz-grala",
      "d-2022-nascar-conor-daly"
    ],
    "budget": 50,
    "reputation": 50,
    "raceOperations": 50,
    "morale": 65,
    "expectedStanding": 39,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-trackhouse-racing-team-1",
    "name": "Trackhouse Racing Team 1",
    "shortName": "",
    "carId": "car-2022-nascar-trackhouse-racing-team-1",
    "driverIds": [
      "d-2022-nascar-ross-chastain",
      "d-2022-nascar-daniel-suarez"
    ],
    "budget": 50,
    "reputation": 95,
    "raceOperations": 95,
    "morale": 65,
    "expectedStanding": 40,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-trackhouse-racing-team-2",
    "name": "Trackhouse Racing Team 2",
    "shortName": "",
    "carId": "car-2022-nascar-trackhouse-racing-team-2",
    "driverIds": [
      "d-2022-nascar-kimi-raikkonen"
    ],
    "budget": 50,
    "reputation": 51,
    "raceOperations": 51,
    "morale": 65,
    "expectedStanding": 41,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2022-nascar-wood-brothers-racing",
    "name": "Wood Brothers Racing",
    "shortName": "",
    "carId": "car-2022-nascar-wood-brothers-racing",
    "driverIds": [
      "d-2022-nascar-harrison-burton"
    ],
    "budget": 50,
    "reputation": 68,
    "raceOperations": 68,
    "morale": 65,
    "expectedStanding": 42,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  }
] as const satisfies Team[];

