// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Team,
} from '../../types/gameTypes';

export const teams2021NASCAR: Team[] = [
  {
    "id": "t-2021-nascar-23xi-racing",
    "name": "23XI Racing",
    "shortName": "",
    "carId": "car-2021-nascar-23xi-racing",
    "driverIds": [
      "d-2021-nascar-bubba-wallace"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 1,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-b-j-mcleod-motorsports",
    "name": "B. J. McLeod Motorsports",
    "shortName": "",
    "carId": "car-2021-nascar-b-j-mcleod-motorsports",
    "driverIds": [
      "d-2021-nascar-matt-mills"
    ],
    "budget": 50,
    "reputation": 32,
    "raceOperations": 32,
    "morale": 65,
    "expectedStanding": 2,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-beard-motorsports",
    "name": "Beard Motorsports",
    "shortName": "",
    "carId": "car-2021-nascar-beard-motorsports",
    "driverIds": [
      "d-2021-nascar-noah-gragson"
    ],
    "budget": 50,
    "reputation": 30,
    "raceOperations": 30,
    "morale": 65,
    "expectedStanding": 3,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-chip-ganassi-racing",
    "name": "Chip Ganassi Racing",
    "shortName": "",
    "carId": "car-2021-nascar-chip-ganassi-racing",
    "driverIds": [
      "d-2021-nascar-kurt-busch",
      "d-2021-nascar-ross-chastain"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 4,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-front-row-motorsports-team-1",
    "name": "Front Row Motorsports Team 1",
    "shortName": "",
    "carId": "car-2021-nascar-front-row-motorsports-team-1",
    "driverIds": [
      "d-2021-nascar-michael-mcdowell",
      "d-2021-nascar-anthony-alfredo"
    ],
    "budget": 50,
    "reputation": 77,
    "raceOperations": 77,
    "morale": 65,
    "expectedStanding": 5,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-front-row-motorsports-team-2",
    "name": "Front Row Motorsports Team 2",
    "shortName": "",
    "carId": "car-2021-nascar-front-row-motorsports-team-2",
    "driverIds": [
      "d-2021-nascar-david-ragan"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 6,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-gaunt-brothers-racing-team-1",
    "name": "Gaunt Brothers Racing team 1",
    "shortName": "",
    "carId": "car-2021-nascar-gaunt-brothers-racing-team-1",
    "driverIds": [
      "d-2021-nascar-ty-dillon",
      "d-2021-nascar-harrison-burton"
    ],
    "budget": 50,
    "reputation": 49,
    "raceOperations": 49,
    "morale": 65,
    "expectedStanding": 7,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-gaunt-brothers-racing-team-2",
    "name": "Gaunt Brothers Racing team 2",
    "shortName": "",
    "carId": "car-2021-nascar-gaunt-brothers-racing-team-2",
    "driverIds": [
      "d-2021-nascar-landon-cassill",
      "d-2021-nascar-parker-kligerman"
    ],
    "budget": 50,
    "reputation": 49,
    "raceOperations": 49,
    "morale": 65,
    "expectedStanding": 8,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-hendrick-motorsports-team-1",
    "name": "Hendrick Motorsports Team 1",
    "shortName": "",
    "carId": "car-2021-nascar-hendrick-motorsports-team-1",
    "driverIds": [
      "d-2021-nascar-kyle-larson",
      "d-2021-nascar-chase-elliott"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 9,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-hendrick-motorsports-team-2",
    "name": "Hendrick Motorsports Team 2",
    "shortName": "",
    "carId": "car-2021-nascar-hendrick-motorsports-team-2",
    "driverIds": [
      "d-2021-nascar-william-byron",
      "d-2021-nascar-alex-bowman"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 10,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-jtg-daugherty-racing",
    "name": "JTG Daugherty Racing",
    "shortName": "",
    "carId": "car-2021-nascar-jtg-daugherty-racing",
    "driverIds": [
      "d-2021-nascar-ricky-stenhouse-jr",
      "d-2021-nascar-ryan-preece"
    ],
    "budget": 50,
    "reputation": 76,
    "raceOperations": 76,
    "morale": 65,
    "expectedStanding": 11,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-joe-gibbs-racing-team-1",
    "name": "Joe Gibbs Racing Team 1",
    "shortName": "",
    "carId": "car-2021-nascar-joe-gibbs-racing-team-1",
    "driverIds": [
      "d-2021-nascar-denny-hamlin",
      "d-2021-nascar-kyle-busch"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 12,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-joe-gibbs-racing-team-2",
    "name": "Joe Gibbs Racing Team 2",
    "shortName": "",
    "carId": "car-2021-nascar-joe-gibbs-racing-team-2",
    "driverIds": [
      "d-2021-nascar-martin-truex-jr",
      "d-2021-nascar-christopher-bell"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 13,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-kaulig-racing-team-1",
    "name": "Kaulig Racing team 1",
    "shortName": "",
    "carId": "car-2021-nascar-kaulig-racing-team-1",
    "driverIds": [
      "d-2021-nascar-kaz-grala",
      "d-2021-nascar-a-j-allmendinger"
    ],
    "budget": 50,
    "reputation": 56,
    "raceOperations": 56,
    "morale": 65,
    "expectedStanding": 14,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-kaulig-racing-team-2",
    "name": "Kaulig Racing team 2",
    "shortName": "",
    "carId": "car-2021-nascar-kaulig-racing-team-2",
    "driverIds": [
      "d-2021-nascar-justin-haley"
    ],
    "budget": 50,
    "reputation": 56,
    "raceOperations": 56,
    "morale": 65,
    "expectedStanding": 15,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-live-fast-motorsports-team-1",
    "name": "Live Fast Motorsports team 1",
    "shortName": "",
    "carId": "car-2021-nascar-live-fast-motorsports-team-1",
    "driverIds": [
      "d-2021-nascar-b-j-mcleod",
      "d-2021-nascar-scott-heckert"
    ],
    "budget": 50,
    "reputation": 59,
    "raceOperations": 59,
    "morale": 65,
    "expectedStanding": 16,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-live-fast-motorsports-team-2",
    "name": "Live Fast Motorsports team 2",
    "shortName": "",
    "carId": "car-2021-nascar-live-fast-motorsports-team-2",
    "driverIds": [
      "d-2021-nascar-shane-golobic",
      "d-2021-nascar-kyle-tilley"
    ],
    "budget": 50,
    "reputation": 59,
    "raceOperations": 59,
    "morale": 65,
    "expectedStanding": 17,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-live-fast-motorsports-team-3",
    "name": "Live Fast Motorsports team 3",
    "shortName": "",
    "carId": "car-2021-nascar-live-fast-motorsports-team-3",
    "driverIds": [
      "d-2021-nascar-andy-lally"
    ],
    "budget": 50,
    "reputation": 59,
    "raceOperations": 59,
    "morale": 65,
    "expectedStanding": 18,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-mbm-motorsports-team-1",
    "name": "MBM Motorsports team 1",
    "shortName": "",
    "carId": "car-2021-nascar-mbm-motorsports-team-1",
    "driverIds": [
      "d-2021-nascar-garrett-smithley",
      "d-2021-nascar-david-starr"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 19,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-mbm-motorsports-team-2",
    "name": "MBM Motorsports team 2",
    "shortName": "",
    "carId": "car-2021-nascar-mbm-motorsports-team-2",
    "driverIds": [
      "d-2021-nascar-timmy-hill",
      "d-2021-nascar-mike-marlar"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 20,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-mbm-motorsports-team-3",
    "name": "MBM Motorsports team 3",
    "shortName": "",
    "carId": "car-2021-nascar-mbm-motorsports-team-3",
    "driverIds": [
      "d-2021-nascar-david-starr",
      "d-2021-nascar-chad-finchum"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 21,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-mbm-motorsports-team-4",
    "name": "MBM Motorsports team 4",
    "shortName": "",
    "carId": "car-2021-nascar-mbm-motorsports-team-4",
    "driverIds": [
      "d-2021-nascar-j-j-yeley",
      "d-2021-nascar-james-davison"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 22,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-petty-ware-racing-team-1",
    "name": "Petty Ware Racing team 1",
    "shortName": "",
    "carId": "car-2021-nascar-petty-ware-racing-team-1",
    "driverIds": [
      "d-2021-nascar-cody-ware",
      "d-2021-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 23,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-petty-ware-racing-team-2",
    "name": "Petty Ware Racing team 2",
    "shortName": "",
    "carId": "car-2021-nascar-petty-ware-racing-team-2",
    "driverIds": [
      "d-2021-nascar-j-j-yeley",
      "d-2021-nascar-james-davison"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 24,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-richard-childress-racing",
    "name": "Richard Childress Racing",
    "shortName": "",
    "carId": "car-2021-nascar-richard-childress-racing",
    "driverIds": [
      "d-2021-nascar-austin-dillon",
      "d-2021-nascar-tyler-reddick"
    ],
    "budget": 50,
    "reputation": 85,
    "raceOperations": 85,
    "morale": 65,
    "expectedStanding": 25,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-richard-petty-motorsports",
    "name": "Richard Petty Motorsports",
    "shortName": "",
    "carId": "car-2021-nascar-richard-petty-motorsports",
    "driverIds": [
      "d-2021-nascar-erik-jones"
    ],
    "budget": 50,
    "reputation": 76,
    "raceOperations": 76,
    "morale": 65,
    "expectedStanding": 26,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-1-team-1",
    "name": "Rick Ware Racing Team 1 team 1",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-1-team-1",
    "driverIds": [
      "d-2021-nascar-josh-bilicki",
      "d-2021-nascar-joey-hand"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 27,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-1-team-2",
    "name": "Rick Ware Racing Team 1 team 2",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-1-team-2",
    "driverIds": [
      "d-2021-nascar-derrike-cope",
      "d-2021-nascar-james-davison"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 28,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-1-team-3",
    "name": "Rick Ware Racing Team 1 team 3",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-1-team-3",
    "driverIds": [
      "d-2021-nascar-joey-gase",
      "d-2021-nascar-chris-windom"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 29,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-1-team-4",
    "name": "Rick Ware Racing Team 1 team 4",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-1-team-4",
    "driverIds": [
      "d-2021-nascar-j-j-yeley",
      "d-2021-nascar-bayley-currey"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 30,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-1-team-5",
    "name": "Rick Ware Racing Team 1 team 5",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-1-team-5",
    "driverIds": [
      "d-2021-nascar-r-c-enerson",
      "d-2021-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 31,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-1-team-6",
    "name": "Rick Ware Racing Team 1 team 6",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-1-team-6",
    "driverIds": [
      "d-2021-nascar-josh-bilicki",
      "d-2021-nascar-ryan-ellis"
    ],
    "budget": 50,
    "reputation": 62,
    "raceOperations": 62,
    "morale": 65,
    "expectedStanding": 32,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-2-team-1",
    "name": "Rick Ware Racing Team 2 team 1",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-2-team-1",
    "driverIds": [
      "d-2021-nascar-joey-gase",
      "d-2021-nascar-garrett-smithley"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 33,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-2-team-2",
    "name": "Rick Ware Racing Team 2 team 2",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-2-team-2",
    "driverIds": [
      "d-2021-nascar-j-j-yeley",
      "d-2021-nascar-cody-ware"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 34,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-rick-ware-racing-team-2-team-3",
    "name": "Rick Ware Racing Team 2 team 3",
    "shortName": "",
    "carId": "car-2021-nascar-rick-ware-racing-team-2-team-3",
    "driverIds": [
      "d-2021-nascar-ryan-eversley",
      "d-2021-nascar-james-davison"
    ],
    "budget": 50,
    "reputation": 60,
    "raceOperations": 60,
    "morale": 65,
    "expectedStanding": 35,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-roush-fenway-racing",
    "name": "Roush Fenway Racing",
    "shortName": "",
    "carId": "car-2021-nascar-roush-fenway-racing",
    "driverIds": [
      "d-2021-nascar-ryan-newman",
      "d-2021-nascar-chris-buescher"
    ],
    "budget": 50,
    "reputation": 77,
    "raceOperations": 77,
    "morale": 65,
    "expectedStanding": 36,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-spire-motorsports-team-1",
    "name": "Spire Motorsports team 1",
    "shortName": "",
    "carId": "car-2021-nascar-spire-motorsports-team-1",
    "driverIds": [
      "d-2021-nascar-corey-lajoie",
      "d-2021-nascar-josh-berry"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 37,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-spire-motorsports-team-2",
    "name": "Spire Motorsports team 2",
    "shortName": "",
    "carId": "car-2021-nascar-spire-motorsports-team-2",
    "driverIds": [
      "d-2021-nascar-jamie-mcmurray",
      "d-2021-nascar-justin-haley"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 38,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-spire-motorsports-team-3",
    "name": "Spire Motorsports team 3",
    "shortName": "",
    "carId": "car-2021-nascar-spire-motorsports-team-3",
    "driverIds": [
      "d-2021-nascar-stewart-friesen",
      "d-2021-nascar-josh-berry"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 39,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-spire-motorsports-team-4",
    "name": "Spire Motorsports team 4",
    "shortName": "",
    "carId": "car-2021-nascar-spire-motorsports-team-4",
    "driverIds": [
      "d-2021-nascar-ben-rhodes",
      "d-2021-nascar-justin-allgaier"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 40,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-starcom-racing",
    "name": "StarCom Racing",
    "shortName": "",
    "carId": "car-2021-nascar-starcom-racing",
    "driverIds": [
      "d-2021-nascar-quin-houff"
    ],
    "budget": 50,
    "reputation": 69,
    "raceOperations": 69,
    "morale": 65,
    "expectedStanding": 41,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-stewart-haas-racing-team-1",
    "name": "Stewart-Haas Racing Team 1",
    "shortName": "",
    "carId": "car-2021-nascar-stewart-haas-racing-team-1",
    "driverIds": [
      "d-2021-nascar-kevin-harvick",
      "d-2021-nascar-aric-almirola"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 42,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-stewart-haas-racing-team-2",
    "name": "Stewart-Haas Racing Team 2",
    "shortName": "",
    "carId": "car-2021-nascar-stewart-haas-racing-team-2",
    "driverIds": [
      "d-2021-nascar-chase-briscoe",
      "d-2021-nascar-cole-custer"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 43,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-team-penske-team-1",
    "name": "Team Penske Team 1",
    "shortName": "",
    "carId": "car-2021-nascar-team-penske-team-1",
    "driverIds": [
      "d-2021-nascar-brad-keselowski",
      "d-2021-nascar-ryan-blaney"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 44,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-team-penske-team-2",
    "name": "Team Penske Team 2",
    "shortName": "",
    "carId": "car-2021-nascar-team-penske-team-2",
    "driverIds": [
      "d-2021-nascar-joey-logano",
      "d-2021-nascar-austin-cindric"
    ],
    "budget": 50,
    "reputation": 73,
    "raceOperations": 73,
    "morale": 65,
    "expectedStanding": 45,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-trackhouse-racing",
    "name": "Trackhouse Racing",
    "shortName": "",
    "carId": "car-2021-nascar-trackhouse-racing",
    "driverIds": [
      "d-2021-nascar-daniel-suarez"
    ],
    "budget": 50,
    "reputation": 75,
    "raceOperations": 75,
    "morale": 65,
    "expectedStanding": 46,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-2021-nascar-wood-brothers-racing",
    "name": "Wood Brothers Racing",
    "shortName": "",
    "carId": "car-2021-nascar-wood-brothers-racing",
    "driverIds": [
      "d-2021-nascar-matt-dibenedetto"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 47,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  }
] as const satisfies Team[];

