// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Team,
} from '../../types/gameTypes';

export const teams1998NASCAR: Team[] = [
  {
    "id": "t-1998-nascar-american-equipment-racing-team-1",
    "name": "American Equipment Racing team 1",
    "shortName": "",
    "carId": "car-1998-nascar-american-equipment-racing-team-1",
    "driverIds": [
      "d-1998-nascar-david-green",
      "d-1998-nascar-kevin-lepage"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 1,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-american-equipment-racing-team-2",
    "name": "American Equipment Racing team 2",
    "shortName": "",
    "carId": "car-1998-nascar-american-equipment-racing-team-2",
    "driverIds": [
      "d-1998-nascar-hut-stricklin",
      "d-1998-nascar-robby-gordon"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 2,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-american-equipment-racing-team-3",
    "name": "American Equipment Racing team 3",
    "shortName": "",
    "carId": "car-1998-nascar-american-equipment-racing-team-3",
    "driverIds": [
      "d-1998-nascar-ron-fellows",
      "d-1998-nascar-ted-musgrave"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 3,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-american-equipment-racing-team-4",
    "name": "American Equipment Racing team 4",
    "shortName": "",
    "carId": "car-1998-nascar-american-equipment-racing-team-4",
    "driverIds": [
      "d-1998-nascar-morgan-shepherd",
      "d-1998-nascar-mike-bliss"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 4,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-american-equipment-racing-team-5",
    "name": "American Equipment Racing team 5",
    "shortName": "",
    "carId": "car-1998-nascar-american-equipment-racing-team-5",
    "driverIds": [
      "d-1998-nascar-steve-grissom"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 5,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-andy-petree-racing",
    "name": "Andy Petree Racing",
    "shortName": "",
    "carId": "car-1998-nascar-andy-petree-racing",
    "driverIds": [
      "d-1998-nascar-ken-schrader",
      "d-1998-nascar-hut-stricklin"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 6,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-bmr-motorsports",
    "name": "BMR Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-bmr-motorsports",
    "driverIds": [
      "d-1998-nascar-jeff-ward"
    ],
    "budget": 50,
    "reputation": 38,
    "raceOperations": 38,
    "morale": 65,
    "expectedStanding": 7,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-bahari-racing",
    "name": "Bahari Racing",
    "shortName": "",
    "carId": "car-1998-nascar-bahari-racing",
    "driverIds": [
      "d-1998-nascar-derrike-cope",
      "d-1998-nascar-jeff-green"
    ],
    "budget": 50,
    "reputation": 81,
    "raceOperations": 81,
    "morale": 65,
    "expectedStanding": 8,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-barkdoll-racing",
    "name": "Barkdoll Racing",
    "shortName": "",
    "carId": "car-1998-nascar-barkdoll-racing",
    "driverIds": [
      "d-1998-nascar-mike-wallace"
    ],
    "budget": 50,
    "reputation": 58,
    "raceOperations": 58,
    "morale": 65,
    "expectedStanding": 9,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-bill-davis-racing",
    "name": "Bill Davis Racing",
    "shortName": "",
    "carId": "car-1998-nascar-bill-davis-racing",
    "driverIds": [
      "d-1998-nascar-ward-burton"
    ],
    "budget": 50,
    "reputation": 91,
    "raceOperations": 91,
    "morale": 65,
    "expectedStanding": 10,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-buckshot-racing",
    "name": "Buckshot Racing",
    "shortName": "",
    "carId": "car-1998-nascar-buckshot-racing",
    "driverIds": [
      "d-1998-nascar-buckshot-jones"
    ],
    "budget": 50,
    "reputation": 67,
    "raceOperations": 67,
    "morale": 65,
    "expectedStanding": 11,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-butch-mock-motorsports",
    "name": "Butch Mock Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-butch-mock-motorsports",
    "driverIds": [
      "d-1998-nascar-rick-mast"
    ],
    "budget": 50,
    "reputation": 84,
    "raceOperations": 84,
    "morale": 65,
    "expectedStanding": 12,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-csg-racing",
    "name": "CSG Racing",
    "shortName": "",
    "carId": "car-1998-nascar-csg-racing",
    "driverIds": [
      "d-1998-nascar-mark-gibson",
      "d-1998-nascar-brian-cunningham"
    ],
    "budget": 50,
    "reputation": 41,
    "raceOperations": 41,
    "morale": 65,
    "expectedStanding": 13,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-cale-yarborough-motorsports",
    "name": "Cale Yarborough Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-cale-yarborough-motorsports",
    "driverIds": [
      "d-1998-nascar-greg-sacks",
      "d-1998-nascar-rich-bickle"
    ],
    "budget": 50,
    "reputation": 78,
    "raceOperations": 78,
    "morale": 65,
    "expectedStanding": 14,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-chris-raudman-racing",
    "name": "Chris Raudman Racing",
    "shortName": "",
    "carId": "car-1998-nascar-chris-raudman-racing",
    "driverIds": [
      "d-1998-nascar-chris-raudman"
    ],
    "budget": 50,
    "reputation": 41,
    "raceOperations": 41,
    "morale": 65,
    "expectedStanding": 15,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-dale-earnhardt-inc-team-1",
    "name": "Dale Earnhardt, Inc. team 1",
    "shortName": "",
    "carId": "car-1998-nascar-dale-earnhardt-inc-team-1",
    "driverIds": [
      "d-1998-nascar-steve-park",
      "d-1998-nascar-phil-parsons"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 16,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-dale-earnhardt-inc-team-2",
    "name": "Dale Earnhardt, Inc. team 2",
    "shortName": "",
    "carId": "car-1998-nascar-dale-earnhardt-inc-team-2",
    "driverIds": [
      "d-1998-nascar-ron-hornaday-jr",
      "d-1998-nascar-darrell-waltrip"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 17,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-darrell-waltrip-motorsports",
    "name": "Darrell Waltrip Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-darrell-waltrip-motorsports",
    "driverIds": [
      "d-1998-nascar-darrell-waltrip"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 18,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-diamond-ridge-motorsports-team-1",
    "name": "Diamond Ridge Motorsports team 1",
    "shortName": "",
    "carId": "car-1998-nascar-diamond-ridge-motorsports-team-1",
    "driverIds": [
      "d-1998-nascar-jeff-green",
      "d-1998-nascar-elliott-sadler"
    ],
    "budget": 50,
    "reputation": 78,
    "raceOperations": 78,
    "morale": 65,
    "expectedStanding": 19,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-diamond-ridge-motorsports-team-2",
    "name": "Diamond Ridge Motorsports team 2",
    "shortName": "",
    "carId": "car-1998-nascar-diamond-ridge-motorsports-team-2",
    "driverIds": [
      "d-1998-nascar-sandy-jones"
    ],
    "budget": 50,
    "reputation": 78,
    "raceOperations": 78,
    "morale": 65,
    "expectedStanding": 20,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-donlavey-racing",
    "name": "Donlavey Racing",
    "shortName": "",
    "carId": "car-1998-nascar-donlavey-racing",
    "driverIds": [
      "d-1998-nascar-dick-trickle"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 21,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-elliott-marino-racing-team-1-team-1",
    "name": "Elliott-Marino Racing Team 1 team 1",
    "shortName": "",
    "carId": "car-1998-nascar-elliott-marino-racing-team-1-team-1",
    "driverIds": [
      "d-1998-nascar-jerry-nadeau",
      "d-1998-nascar-dennis-setzer"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 22,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-elliott-marino-racing-team-1-team-2",
    "name": "Elliott-Marino Racing Team 1 team 2",
    "shortName": "",
    "carId": "car-1998-nascar-elliott-marino-racing-team-1-team-2",
    "driverIds": [
      "d-1998-nascar-wally-dallenbach-jr",
      "d-1998-nascar-tom-hubert"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 23,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-elliott-marino-racing-team-1-team-3",
    "name": "Elliott-Marino Racing Team 1 team 3",
    "shortName": "",
    "carId": "car-1998-nascar-elliott-marino-racing-team-1-team-3",
    "driverIds": [
      "d-1998-nascar-ted-musgrave",
      "d-1998-nascar-bill-elliott"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 24,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-elliott-marino-racing-team-1-team-4",
    "name": "Elliott-Marino Racing Team 1 team 4",
    "shortName": "",
    "carId": "car-1998-nascar-elliott-marino-racing-team-1-team-4",
    "driverIds": [
      "d-1998-nascar-matt-kenseth"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 25,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-elliott-marino-racing-team-2",
    "name": "Elliott-Marino Racing Team 2",
    "shortName": "",
    "carId": "car-1998-nascar-elliott-marino-racing-team-2",
    "driverIds": [
      "d-1998-nascar-dennis-setzer"
    ],
    "budget": 50,
    "reputation": 68,
    "raceOperations": 68,
    "morale": 65,
    "expectedStanding": 26,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-filmar-racing",
    "name": "FILMAR Racing",
    "shortName": "",
    "carId": "car-1998-nascar-filmar-racing",
    "driverIds": [
      "d-1998-nascar-kenny-wallace"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 27,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-gerhart-racing",
    "name": "Gerhart Racing",
    "shortName": "",
    "carId": "car-1998-nascar-gerhart-racing",
    "driverIds": [
      "d-1998-nascar-bobby-gerhart"
    ],
    "budget": 50,
    "reputation": 38,
    "raceOperations": 38,
    "morale": 65,
    "expectedStanding": 28,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-gunselman-racing",
    "name": "Gunselman Racing",
    "shortName": "",
    "carId": "car-1998-nascar-gunselman-racing",
    "driverIds": [
      "d-1998-nascar-larry-gunselman"
    ],
    "budget": 50,
    "reputation": 41,
    "raceOperations": 41,
    "morale": 65,
    "expectedStanding": 29,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-hendrick-motorsports-team-1",
    "name": "Hendrick Motorsports Team 1",
    "shortName": "",
    "carId": "car-1998-nascar-hendrick-motorsports-team-1",
    "driverIds": [
      "d-1998-nascar-terry-labonte",
      "d-1998-nascar-jeff-gordon"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 30,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-hendrick-motorsports-team-2-team-1",
    "name": "Hendrick Motorsports Team 2 team 1",
    "shortName": "",
    "carId": "car-1998-nascar-hendrick-motorsports-team-2-team-1",
    "driverIds": [
      "d-1998-nascar-ricky-craven",
      "d-1998-nascar-randy-lajoie"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 31,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-hendrick-motorsports-team-2-team-2",
    "name": "Hendrick Motorsports Team 2 team 2",
    "shortName": "",
    "carId": "car-1998-nascar-hendrick-motorsports-team-2-team-2",
    "driverIds": [
      "d-1998-nascar-wally-dallenbach-jr"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 32,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-highland-timber-racing",
    "name": "Highland Timber Racing",
    "shortName": "",
    "carId": "car-1998-nascar-highland-timber-racing",
    "driverIds": [
      "d-1998-nascar-harris-devane"
    ],
    "budget": 50,
    "reputation": 37,
    "raceOperations": 37,
    "morale": 65,
    "expectedStanding": 33,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-hilton-racing",
    "name": "Hilton Racing",
    "shortName": "",
    "carId": "car-1998-nascar-hilton-racing",
    "driverIds": [
      "d-1998-nascar-butch-gilliland"
    ],
    "budget": 50,
    "reputation": 58,
    "raceOperations": 58,
    "morale": 65,
    "expectedStanding": 34,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-hover-motorsports",
    "name": "Hover Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-hover-motorsports",
    "driverIds": [
      "d-1998-nascar-mike-ciochetti",
      "d-1998-nascar-andy-hillenburg"
    ],
    "budget": 50,
    "reputation": 64,
    "raceOperations": 64,
    "morale": 65,
    "expectedStanding": 35,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-ism-racing-team-1",
    "name": "ISM Racing team 1",
    "shortName": "",
    "carId": "car-1998-nascar-ism-racing-team-1",
    "driverIds": [
      "d-1998-nascar-todd-bodine",
      "d-1998-nascar-wally-dallenbach-jr"
    ],
    "budget": 50,
    "reputation": 78,
    "raceOperations": 78,
    "morale": 65,
    "expectedStanding": 36,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-ism-racing-team-2",
    "name": "ISM Racing team 2",
    "shortName": "",
    "carId": "car-1998-nascar-ism-racing-team-2",
    "driverIds": [
      "d-1998-nascar-gary-bradberry",
      "d-1998-nascar-jimmy-horton"
    ],
    "budget": 50,
    "reputation": 78,
    "raceOperations": 78,
    "morale": 65,
    "expectedStanding": 37,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-jasper-motorsports-team-1",
    "name": "Jasper Motorsports team 1",
    "shortName": "",
    "carId": "car-1998-nascar-jasper-motorsports-team-1",
    "driverIds": [
      "d-1998-nascar-robert-pressley",
      "d-1998-nascar-hut-stricklin"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 38,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-jasper-motorsports-team-2",
    "name": "Jasper Motorsports team 2",
    "shortName": "",
    "carId": "car-1998-nascar-jasper-motorsports-team-2",
    "driverIds": [
      "d-1998-nascar-ted-musgrave"
    ],
    "budget": 50,
    "reputation": 88,
    "raceOperations": 88,
    "morale": 65,
    "expectedStanding": 39,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-joe-gibbs-racing",
    "name": "Joe Gibbs Racing",
    "shortName": "",
    "carId": "car-1998-nascar-joe-gibbs-racing",
    "driverIds": [
      "d-1998-nascar-bobby-labonte"
    ],
    "budget": 50,
    "reputation": 96,
    "raceOperations": 96,
    "morale": 65,
    "expectedStanding": 40,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-lj-racing-team-1",
    "name": "LJ Racing team 1",
    "shortName": "",
    "carId": "car-1998-nascar-lj-racing-team-1",
    "driverIds": [
      "d-1998-nascar-kevin-lepage",
      "d-1998-nascar-tommy-kendall"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 41,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-lj-racing-team-2",
    "name": "LJ Racing team 2",
    "shortName": "",
    "carId": "car-1998-nascar-lj-racing-team-2",
    "driverIds": [
      "d-1998-nascar-andy-hillenburg",
      "d-1998-nascar-morgan-shepherd"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 42,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-lj-racing-team-3",
    "name": "LJ Racing team 3",
    "shortName": "",
    "carId": "car-1998-nascar-lj-racing-team-3",
    "driverIds": [
      "d-1998-nascar-todd-bodine"
    ],
    "budget": 50,
    "reputation": 79,
    "raceOperations": 79,
    "morale": 65,
    "expectedStanding": 43,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-larry-hedrick-motorsports-team-1",
    "name": "Larry Hedrick Motorsports team 1",
    "shortName": "",
    "carId": "car-1998-nascar-larry-hedrick-motorsports-team-1",
    "driverIds": [
      "d-1998-nascar-steve-grissom",
      "d-1998-nascar-david-green"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 44,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-larry-hedrick-motorsports-team-2",
    "name": "Larry Hedrick Motorsports team 2",
    "shortName": "",
    "carId": "car-1998-nascar-larry-hedrick-motorsports-team-2",
    "driverIds": [
      "d-1998-nascar-rick-wilson"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 45,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-mb2-motorsports",
    "name": "MB2 Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-mb2-motorsports",
    "driverIds": [
      "d-1998-nascar-ernie-irvan",
      "d-1998-nascar-ricky-craven"
    ],
    "budget": 50,
    "reputation": 87,
    "raceOperations": 87,
    "morale": 65,
    "expectedStanding": 46,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-mansion-motorsports-team-1",
    "name": "Mansion Motorsports team 1",
    "shortName": "",
    "carId": "car-1998-nascar-mansion-motorsports-team-1",
    "driverIds": [
      "d-1998-nascar-randy-renfrow",
      "d-1998-nascar-bob-strait"
    ],
    "budget": 50,
    "reputation": 43,
    "raceOperations": 43,
    "morale": 65,
    "expectedStanding": 47,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-mansion-motorsports-team-2",
    "name": "Mansion Motorsports team 2",
    "shortName": "",
    "carId": "car-1998-nascar-mansion-motorsports-team-2",
    "driverIds": [
      "d-1998-nascar-randy-macdonald",
      "d-1998-nascar-ken-bouchard"
    ],
    "budget": 50,
    "reputation": 43,
    "raceOperations": 43,
    "morale": 65,
    "expectedStanding": 48,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-marcis-auto-racing",
    "name": "Marcis Auto Racing",
    "shortName": "",
    "carId": "car-1998-nascar-marcis-auto-racing",
    "driverIds": [
      "d-1998-nascar-dave-marcis"
    ],
    "budget": 50,
    "reputation": 74,
    "raceOperations": 74,
    "morale": 65,
    "expectedStanding": 49,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-mattei-motorsports",
    "name": "Mattei Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-mattei-motorsports",
    "driverIds": [
      "d-1998-nascar-geoff-bodine"
    ],
    "budget": 50,
    "reputation": 89,
    "raceOperations": 89,
    "morale": 65,
    "expectedStanding": 50,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-melling-racing-team-1",
    "name": "Melling Racing team 1",
    "shortName": "",
    "carId": "car-1998-nascar-melling-racing-team-1",
    "driverIds": [
      "d-1998-nascar-lake-speed",
      "d-1998-nascar-butch-gilliland"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 51,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-melling-racing-team-2",
    "name": "Melling Racing team 2",
    "shortName": "",
    "carId": "car-1998-nascar-melling-racing-team-2",
    "driverIds": [
      "d-1998-nascar-jerry-nadeau"
    ],
    "budget": 50,
    "reputation": 80,
    "raceOperations": 80,
    "morale": 65,
    "expectedStanding": 52,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-midwest-transit-racing",
    "name": "Midwest Transit Racing",
    "shortName": "",
    "carId": "car-1998-nascar-midwest-transit-racing",
    "driverIds": [
      "d-1998-nascar-dan-pardus",
      "d-1998-nascar-john-mcqueen"
    ],
    "budget": 50,
    "reputation": 55,
    "raceOperations": 55,
    "morale": 65,
    "expectedStanding": 53,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-moore-robinson-motorsports",
    "name": "Moore-Robinson Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-moore-robinson-motorsports",
    "driverIds": [
      "d-1998-nascar-loy-allen-jr",
      "d-1998-nascar-ted-musgrave"
    ],
    "budget": 50,
    "reputation": 82,
    "raceOperations": 82,
    "morale": 65,
    "expectedStanding": 54,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-morgan-mcclure-motorsports",
    "name": "Morgan-McClure Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-morgan-mcclure-motorsports",
    "driverIds": [
      "d-1998-nascar-bobby-hamilton"
    ],
    "budget": 50,
    "reputation": 94,
    "raceOperations": 94,
    "morale": 65,
    "expectedStanding": 55,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-pe2",
    "name": "PE2",
    "shortName": "",
    "carId": "car-1998-nascar-pe2",
    "driverIds": [
      "d-1998-nascar-kyle-petty"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 56,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-penske-racing-south-penske-kranefuss-racing",
    "name": "Penske Racing South / Penske-Kranefuss Racing",
    "shortName": "",
    "carId": "car-1998-nascar-penske-racing-south-penske-kranefuss-racing",
    "driverIds": [
      "d-1998-nascar-rusty-wallace",
      "d-1998-nascar-jeremy-mayfield"
    ],
    "budget": 50,
    "reputation": 99,
    "raceOperations": 99,
    "morale": 65,
    "expectedStanding": 57,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-petty-enterprises",
    "name": "Petty Enterprises",
    "shortName": "",
    "carId": "car-1998-nascar-petty-enterprises",
    "driverIds": [
      "d-1998-nascar-john-andretti"
    ],
    "budget": 50,
    "reputation": 95,
    "raceOperations": 95,
    "morale": 65,
    "expectedStanding": 58,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-precision-products-racing",
    "name": "Precision Products Racing",
    "shortName": "",
    "carId": "car-1998-nascar-precision-products-racing",
    "driverIds": [
      "d-1998-nascar-loy-allen-jr",
      "d-1998-nascar-lance-hooper"
    ],
    "budget": 50,
    "reputation": 42,
    "raceOperations": 42,
    "morale": 65,
    "expectedStanding": 59,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-richard-childress-racing-team-1-team-1",
    "name": "Richard Childress Racing Team 1 team 1",
    "shortName": "",
    "carId": "car-1998-nascar-richard-childress-racing-team-1-team-1",
    "driverIds": [
      "d-1998-nascar-dale-earnhardt",
      "d-1998-nascar-mike-skinner"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 60,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-richard-childress-racing-team-1-team-2",
    "name": "Richard Childress Racing Team 1 team 2",
    "shortName": "",
    "carId": "car-1998-nascar-richard-childress-racing-team-1-team-2",
    "driverIds": [
      "d-1998-nascar-morgan-shepherd",
      "d-1998-nascar-mike-dillon"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 61,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-robert-yates-racing-team-1",
    "name": "Robert Yates Racing Team 1",
    "shortName": "",
    "carId": "car-1998-nascar-robert-yates-racing-team-1",
    "driverIds": [
      "d-1998-nascar-kenny-irwin-jr",
      "d-1998-nascar-dale-jarrett"
    ],
    "budget": 50,
    "reputation": 97,
    "raceOperations": 97,
    "morale": 65,
    "expectedStanding": 62,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-roehrig-motorsports-team-1",
    "name": "Roehrig Motorsports team 1",
    "shortName": "",
    "carId": "car-1998-nascar-roehrig-motorsports-team-1",
    "driverIds": [
      "d-1998-nascar-tony-raines",
      "d-1998-nascar-tom-hubert"
    ],
    "budget": 50,
    "reputation": 59,
    "raceOperations": 59,
    "morale": 65,
    "expectedStanding": 63,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-roehrig-motorsports-team-2",
    "name": "Roehrig Motorsports team 2",
    "shortName": "",
    "carId": "car-1998-nascar-roehrig-motorsports-team-2",
    "driverIds": [
      "d-1998-nascar-robby-gordon"
    ],
    "budget": 50,
    "reputation": 59,
    "raceOperations": 59,
    "morale": 65,
    "expectedStanding": 64,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-roush-racing-team-1-team-1",
    "name": "Roush Racing Team 1 team 1",
    "shortName": "",
    "carId": "car-1998-nascar-roush-racing-team-1-team-1",
    "driverIds": [
      "d-1998-nascar-mark-martin",
      "d-1998-nascar-ted-musgrave"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 65,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-roush-racing-team-1-team-2",
    "name": "Roush Racing Team 1 team 2",
    "shortName": "",
    "carId": "car-1998-nascar-roush-racing-team-1-team-2",
    "driverIds": [
      "d-1998-nascar-kevin-lepage"
    ],
    "budget": 50,
    "reputation": 98,
    "raceOperations": 98,
    "morale": 65,
    "expectedStanding": 66,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-roush-racing-team-2",
    "name": "Roush Racing Team 2",
    "shortName": "",
    "carId": "car-1998-nascar-roush-racing-team-2",
    "driverIds": [
      "d-1998-nascar-johnny-benson",
      "d-1998-nascar-chad-little"
    ],
    "budget": 50,
    "reputation": 93,
    "raceOperations": 93,
    "morale": 65,
    "expectedStanding": 67,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-roush-racing-team-3",
    "name": "Roush Racing Team 3",
    "shortName": "",
    "carId": "car-1998-nascar-roush-racing-team-3",
    "driverIds": [
      "d-1998-nascar-jeff-burton",
      "d-1998-nascar-matt-kenseth"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 68,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-rudd-performance-motorsports",
    "name": "Rudd Performance Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-rudd-performance-motorsports",
    "driverIds": [
      "d-1998-nascar-ricky-rudd"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 69,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-sbiii-motorsports",
    "name": "SBIII Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-sbiii-motorsports",
    "driverIds": [
      "d-1998-nascar-rick-wilson"
    ],
    "budget": 50,
    "reputation": 37,
    "raceOperations": 37,
    "morale": 65,
    "expectedStanding": 70,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-sadler-brothers-racing",
    "name": "Sadler Brothers Racing",
    "shortName": "",
    "carId": "car-1998-nascar-sadler-brothers-racing",
    "driverIds": [
      "d-1998-nascar-andy-hillenburg",
      "d-1998-nascar-randy-macdonald"
    ],
    "budget": 50,
    "reputation": 63,
    "raceOperations": 63,
    "morale": 65,
    "expectedStanding": 71,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-shepherd-racing",
    "name": "Shepherd Racing",
    "shortName": "",
    "carId": "car-1998-nascar-shepherd-racing",
    "driverIds": [
      "d-1998-nascar-morgan-shepherd"
    ],
    "budget": 50,
    "reputation": 71,
    "raceOperations": 71,
    "morale": 65,
    "expectedStanding": 72,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-standridge-motorsports",
    "name": "Standridge Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-standridge-motorsports",
    "driverIds": [
      "d-1998-nascar-billy-standridge"
    ],
    "budget": 50,
    "reputation": 65,
    "raceOperations": 65,
    "morale": 65,
    "expectedStanding": 73,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-stavola-brothers-racing-team-1",
    "name": "Stavola Brothers Racing team 1",
    "shortName": "",
    "carId": "car-1998-nascar-stavola-brothers-racing-team-1",
    "driverIds": [
      "d-1998-nascar-hut-stricklin",
      "d-1998-nascar-jim-long"
    ],
    "budget": 50,
    "reputation": 73,
    "raceOperations": 73,
    "morale": 65,
    "expectedStanding": 74,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-stavola-brothers-racing-team-2",
    "name": "Stavola Brothers Racing team 2",
    "shortName": "",
    "carId": "car-1998-nascar-stavola-brothers-racing-team-2",
    "driverIds": [
      "d-1998-nascar-buckshot-jones",
      "d-1998-nascar-morgan-shepherd"
    ],
    "budget": 50,
    "reputation": 73,
    "raceOperations": 73,
    "morale": 65,
    "expectedStanding": 75,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-t-r-i-x-racing-team-1",
    "name": "T.R.I.X. Racing team 1",
    "shortName": "",
    "carId": "car-1998-nascar-t-r-i-x-racing-team-1",
    "driverIds": [
      "d-1998-nascar-norm-benning",
      "d-1998-nascar-randy-macdonald"
    ],
    "budget": 50,
    "reputation": 40,
    "raceOperations": 40,
    "morale": 65,
    "expectedStanding": 76,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-t-r-i-x-racing-team-2",
    "name": "T.R.I.X. Racing team 2",
    "shortName": "",
    "carId": "car-1998-nascar-t-r-i-x-racing-team-2",
    "driverIds": [
      "d-1998-nascar-ken-bouchard"
    ],
    "budget": 50,
    "reputation": 40,
    "raceOperations": 40,
    "morale": 65,
    "expectedStanding": 77,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-team-sabco-team-1",
    "name": "Team SABCO Team 1",
    "shortName": "",
    "carId": "car-1998-nascar-team-sabco-team-1",
    "driverIds": [
      "d-1998-nascar-sterling-marlin",
      "d-1998-nascar-joe-nemechek"
    ],
    "budget": 50,
    "reputation": 92,
    "raceOperations": 92,
    "morale": 65,
    "expectedStanding": 78,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-team-sabco-team-2-team-1",
    "name": "Team SABCO Team 2 team 1",
    "shortName": "",
    "carId": "car-1998-nascar-team-sabco-team-2-team-1",
    "driverIds": [
      "d-1998-nascar-wally-dallenbach-jr",
      "d-1998-nascar-morgan-shepherd"
    ],
    "budget": 50,
    "reputation": 77,
    "raceOperations": 77,
    "morale": 65,
    "expectedStanding": 79,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-team-sabco-team-2-team-2",
    "name": "Team SABCO Team 2 team 2",
    "shortName": "",
    "carId": "car-1998-nascar-team-sabco-team-2-team-2",
    "driverIds": [
      "d-1998-nascar-jeff-green",
      "d-1998-nascar-tommy-kendall"
    ],
    "budget": 50,
    "reputation": 77,
    "raceOperations": 77,
    "morale": 65,
    "expectedStanding": 80,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-team-scandia-brett-bodine-racing",
    "name": "Team Scandia / Brett Bodine Racing",
    "shortName": "",
    "carId": "car-1998-nascar-team-scandia-brett-bodine-racing",
    "driverIds": [
      "d-1998-nascar-brett-bodine"
    ],
    "budget": 50,
    "reputation": 87,
    "raceOperations": 87,
    "morale": 65,
    "expectedStanding": 81,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-travis-carter-enterprises-team-1",
    "name": "Travis Carter Enterprises team 1",
    "shortName": "",
    "carId": "car-1998-nascar-travis-carter-enterprises-team-1",
    "driverIds": [
      "d-1998-nascar-jimmy-spencer",
      "d-1998-nascar-frank-kimmel"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 82,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-travis-carter-enterprises-team-2",
    "name": "Travis Carter Enterprises team 2",
    "shortName": "",
    "carId": "car-1998-nascar-travis-carter-enterprises-team-2",
    "driverIds": [
      "d-1998-nascar-ted-musgrave"
    ],
    "budget": 50,
    "reputation": 90,
    "raceOperations": 90,
    "morale": 65,
    "expectedStanding": 83,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-triad-motorsports",
    "name": "Triad Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-triad-motorsports",
    "driverIds": [
      "d-1998-nascar-gary-bradberry"
    ],
    "budget": 50,
    "reputation": 73,
    "raceOperations": 73,
    "morale": 65,
    "expectedStanding": 84,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-tyler-jet-motorsports",
    "name": "Tyler Jet Motorsports",
    "shortName": "",
    "carId": "car-1998-nascar-tyler-jet-motorsports",
    "driverIds": [
      "d-1998-nascar-darrell-waltrip",
      "d-1998-nascar-ron-hornaday-jr"
    ],
    "budget": 50,
    "reputation": 86,
    "raceOperations": 86,
    "morale": 65,
    "expectedStanding": 85,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-ware-racing-enterprises",
    "name": "Ware Racing Enterprises",
    "shortName": "",
    "carId": "car-1998-nascar-ware-racing-enterprises",
    "driverIds": [
      "d-1998-nascar-rick-ware"
    ],
    "budget": 50,
    "reputation": 41,
    "raceOperations": 41,
    "morale": 65,
    "expectedStanding": 86,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  },
  {
    "id": "t-1998-nascar-wood-brothers-racing",
    "name": "Wood Brothers Racing",
    "shortName": "",
    "carId": "car-1998-nascar-wood-brothers-racing",
    "driverIds": [
      "d-1998-nascar-michael-waltrip"
    ],
    "budget": 50,
    "reputation": 92,
    "raceOperations": 92,
    "morale": 65,
    "expectedStanding": 87,
    "difficulty": "Medium",
    "color": "#60a5fa",
    "country": "United States"
  }
] as const satisfies Team[];

