// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Car,
} from '../../types/gameTypes';

export const cars1999NASCAR: Car[] = [
  {
    "id": "car-1999-nascar-ac-motorsports",
    "teamId": "t-1999-nascar-ac-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 28,
      "aeroEfficiency": 31,
      "mechanicalGrip": 30,
      "reliability": 24,
      "pitCrewOperations": 24
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-andy-petree-racing",
    "teamId": "t-1999-nascar-andy-petree-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 87,
      "aeroEfficiency": 86,
      "mechanicalGrip": 85,
      "reliability": 91,
      "pitCrewOperations": 88
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-barkdoll-racing",
    "teamId": "t-1999-nascar-barkdoll-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 30,
      "aeroEfficiency": 33,
      "mechanicalGrip": 31,
      "reliability": 32,
      "pitCrewOperations": 34
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-bill-davis-racing-team-1",
    "teamId": "t-1999-nascar-bill-davis-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 92,
      "aeroEfficiency": 93,
      "mechanicalGrip": 88,
      "reliability": 95,
      "pitCrewOperations": 91
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-bill-davis-racing-team-2",
    "teamId": "t-1999-nascar-bill-davis-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 48,
      "aeroEfficiency": 51,
      "mechanicalGrip": 51,
      "reliability": 43,
      "pitCrewOperations": 51
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-bill-elliott-racing",
    "teamId": "t-1999-nascar-bill-elliott-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 87,
      "aeroEfficiency": 88,
      "mechanicalGrip": 83,
      "reliability": 79,
      "pitCrewOperations": 88
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-brett-bodine-racing",
    "teamId": "t-1999-nascar-brett-bodine-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 75,
      "aeroEfficiency": 73,
      "mechanicalGrip": 79,
      "reliability": 74,
      "pitCrewOperations": 71
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-buckshot-racing",
    "teamId": "t-1999-nascar-buckshot-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 52,
      "aeroEfficiency": 55,
      "mechanicalGrip": 55,
      "reliability": 54,
      "pitCrewOperations": 53
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-csg-racing",
    "teamId": "t-1999-nascar-csg-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 34,
      "aeroEfficiency": 30,
      "mechanicalGrip": 31,
      "reliability": 30,
      "pitCrewOperations": 37
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-dale-earnhardt-inc",
    "teamId": "t-1999-nascar-dale-earnhardt-inc",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 86,
      "aeroEfficiency": 84,
      "mechanicalGrip": 86,
      "reliability": 87,
      "pitCrewOperations": 82
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-donlavey-racing-team-1",
    "teamId": "t-1999-nascar-donlavey-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 54,
      "mechanicalGrip": 54,
      "reliability": 56,
      "pitCrewOperations": 55
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-donlavey-racing-team-2",
    "teamId": "t-1999-nascar-donlavey-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 54,
      "mechanicalGrip": 54,
      "reliability": 56,
      "pitCrewOperations": 55
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-donlavey-racing-team-3",
    "teamId": "t-1999-nascar-donlavey-racing-team-3",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 54,
      "mechanicalGrip": 54,
      "reliability": 56,
      "pitCrewOperations": 55
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-donlavey-racing-team-4",
    "teamId": "t-1999-nascar-donlavey-racing-team-4",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 54,
      "mechanicalGrip": 54,
      "reliability": 56,
      "pitCrewOperations": 55
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-eel-river-racing-team-1",
    "teamId": "t-1999-nascar-eel-river-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 56,
      "aeroEfficiency": 56,
      "mechanicalGrip": 60,
      "reliability": 60,
      "pitCrewOperations": 55
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-eel-river-racing-team-2",
    "teamId": "t-1999-nascar-eel-river-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 56,
      "aeroEfficiency": 56,
      "mechanicalGrip": 60,
      "reliability": 60,
      "pitCrewOperations": 55
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-elliott-marino-racing",
    "teamId": "t-1999-nascar-elliott-marino-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 53,
      "aeroEfficiency": 54,
      "mechanicalGrip": 53,
      "reliability": 50,
      "pitCrewOperations": 49
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-fast-track-racing",
    "teamId": "t-1999-nascar-fast-track-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 33,
      "aeroEfficiency": 33,
      "mechanicalGrip": 36,
      "reliability": 34,
      "pitCrewOperations": 30
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-fenley-moore-motorsports-team-1",
    "teamId": "t-1999-nascar-fenley-moore-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 56,
      "mechanicalGrip": 55,
      "reliability": 53,
      "pitCrewOperations": 57
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-fenley-moore-motorsports-team-2",
    "teamId": "t-1999-nascar-fenley-moore-motorsports-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 56,
      "mechanicalGrip": 55,
      "reliability": 53,
      "pitCrewOperations": 57
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-galaxy-motorsports",
    "teamId": "t-1999-nascar-galaxy-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 80,
      "aeroEfficiency": 78,
      "mechanicalGrip": 73,
      "reliability": 79,
      "pitCrewOperations": 73
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-gerhart-racing",
    "teamId": "t-1999-nascar-gerhart-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 36,
      "aeroEfficiency": 35,
      "mechanicalGrip": 37,
      "reliability": 32,
      "pitCrewOperations": 34
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-golden-gate-racing-team",
    "teamId": "t-1999-nascar-golden-gate-racing-team",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 25,
      "aeroEfficiency": 29,
      "mechanicalGrip": 25,
      "reliability": 30,
      "pitCrewOperations": 29
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-haas-carter-motorsports-team-1",
    "teamId": "t-1999-nascar-haas-carter-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 85,
      "aeroEfficiency": 84,
      "mechanicalGrip": 80,
      "reliability": 82,
      "pitCrewOperations": 88
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-hendrick-motorsports-team-1",
    "teamId": "t-1999-nascar-hendrick-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 95,
      "aeroEfficiency": 91,
      "mechanicalGrip": 92,
      "reliability": 97,
      "pitCrewOperations": 91
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-hendrick-motorsports-team-2",
    "teamId": "t-1999-nascar-hendrick-motorsports-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 87,
      "aeroEfficiency": 86,
      "mechanicalGrip": 87,
      "reliability": 82,
      "pitCrewOperations": 86
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-highland-timber-racing",
    "teamId": "t-1999-nascar-highland-timber-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 35,
      "aeroEfficiency": 40,
      "mechanicalGrip": 34,
      "reliability": 39,
      "pitCrewOperations": 41
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-hover-motorsports",
    "teamId": "t-1999-nascar-hover-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 40,
      "aeroEfficiency": 40,
      "mechanicalGrip": 36,
      "reliability": 38,
      "pitCrewOperations": 38
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-irvan-simo-racing-team-1",
    "teamId": "t-1999-nascar-irvan-simo-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 54,
      "mechanicalGrip": 54,
      "reliability": 57,
      "pitCrewOperations": 58
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-irvan-simo-racing-team-2",
    "teamId": "t-1999-nascar-irvan-simo-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 54,
      "mechanicalGrip": 54,
      "reliability": 57,
      "pitCrewOperations": 58
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-jasper-motorsports",
    "teamId": "t-1999-nascar-jasper-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 70,
      "aeroEfficiency": 75,
      "mechanicalGrip": 67,
      "reliability": 69,
      "pitCrewOperations": 75
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-jenn-west-motorsports",
    "teamId": "t-1999-nascar-jenn-west-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 37,
      "aeroEfficiency": 40,
      "mechanicalGrip": 36,
      "reliability": 40,
      "pitCrewOperations": 35
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-joe-bessey-motorsports",
    "teamId": "t-1999-nascar-joe-bessey-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 82,
      "aeroEfficiency": 85,
      "mechanicalGrip": 85,
      "reliability": 78,
      "pitCrewOperations": 83
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-joe-gibbs-racing",
    "teamId": "t-1999-nascar-joe-gibbs-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 97,
      "aeroEfficiency": 100,
      "mechanicalGrip": 99,
      "reliability": 98,
      "pitCrewOperations": 96
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-joyner-kersee-racing",
    "teamId": "t-1999-nascar-joyner-kersee-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 42,
      "aeroEfficiency": 48,
      "mechanicalGrip": 49,
      "reliability": 46,
      "pitCrewOperations": 50
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-lj-racing-team-1",
    "teamId": "t-1999-nascar-lj-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 71,
      "aeroEfficiency": 71,
      "mechanicalGrip": 69,
      "reliability": 66,
      "pitCrewOperations": 68
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-lj-racing-team-2",
    "teamId": "t-1999-nascar-lj-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 71,
      "aeroEfficiency": 71,
      "mechanicalGrip": 69,
      "reliability": 66,
      "pitCrewOperations": 68
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-lj-racing-team-3",
    "teamId": "t-1999-nascar-lj-racing-team-3",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 71,
      "aeroEfficiency": 71,
      "mechanicalGrip": 69,
      "reliability": 66,
      "pitCrewOperations": 68
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-lj-racing-team-4",
    "teamId": "t-1999-nascar-lj-racing-team-4",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 71,
      "aeroEfficiency": 71,
      "mechanicalGrip": 69,
      "reliability": 66,
      "pitCrewOperations": 68
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-lj-racing-team-5",
    "teamId": "t-1999-nascar-lj-racing-team-5",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 71,
      "aeroEfficiency": 71,
      "mechanicalGrip": 69,
      "reliability": 66,
      "pitCrewOperations": 68
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-larry-hedrick-motorsports-team-1",
    "teamId": "t-1999-nascar-larry-hedrick-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 74,
      "aeroEfficiency": 75,
      "mechanicalGrip": 72,
      "reliability": 72,
      "pitCrewOperations": 76
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-larry-hedrick-motorsports-team-2",
    "teamId": "t-1999-nascar-larry-hedrick-motorsports-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 74,
      "aeroEfficiency": 75,
      "mechanicalGrip": 72,
      "reliability": 72,
      "pitCrewOperations": 76
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-mb2-motorsports-team-1",
    "teamId": "t-1999-nascar-mb2-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 74,
      "aeroEfficiency": 77,
      "mechanicalGrip": 78,
      "reliability": 71,
      "pitCrewOperations": 76
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-mb2-motorsports-team-2",
    "teamId": "t-1999-nascar-mb2-motorsports-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 74,
      "aeroEfficiency": 77,
      "mechanicalGrip": 78,
      "reliability": 71,
      "pitCrewOperations": 76
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-mansion-motorsports",
    "teamId": "t-1999-nascar-mansion-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 29,
      "aeroEfficiency": 26,
      "mechanicalGrip": 32,
      "reliability": 24,
      "pitCrewOperations": 27
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-marcis-auto-racing-team-1",
    "teamId": "t-1999-nascar-marcis-auto-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 63,
      "aeroEfficiency": 56,
      "mechanicalGrip": 63,
      "reliability": 59,
      "pitCrewOperations": 61
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-marcis-auto-racing-team-2",
    "teamId": "t-1999-nascar-marcis-auto-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 63,
      "aeroEfficiency": 56,
      "mechanicalGrip": 63,
      "reliability": 59,
      "pitCrewOperations": 61
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-mattei-motorsports",
    "teamId": "t-1999-nascar-mattei-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 77,
      "aeroEfficiency": 81,
      "mechanicalGrip": 78,
      "reliability": 83,
      "pitCrewOperations": 78
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-meacham-racing",
    "teamId": "t-1999-nascar-meacham-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 41,
      "aeroEfficiency": 35,
      "mechanicalGrip": 33,
      "reliability": 39,
      "pitCrewOperations": 32
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-melling-racing-team-1",
    "teamId": "t-1999-nascar-melling-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 79,
      "aeroEfficiency": 72,
      "mechanicalGrip": 77,
      "reliability": 78,
      "pitCrewOperations": 74
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-melling-racing-team-2",
    "teamId": "t-1999-nascar-melling-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 79,
      "aeroEfficiency": 72,
      "mechanicalGrip": 77,
      "reliability": 78,
      "pitCrewOperations": 74
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-metcalf-motorsports",
    "teamId": "t-1999-nascar-metcalf-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 25,
      "aeroEfficiency": 25,
      "mechanicalGrip": 25,
      "reliability": 23,
      "pitCrewOperations": 32
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-midgley-motorsports",
    "teamId": "t-1999-nascar-midgley-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 30,
      "aeroEfficiency": 30,
      "mechanicalGrip": 28,
      "reliability": 25,
      "pitCrewOperations": 24
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-midwest-transit-racing-team-1",
    "teamId": "t-1999-nascar-midwest-transit-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 66,
      "aeroEfficiency": 58,
      "mechanicalGrip": 59,
      "reliability": 59,
      "pitCrewOperations": 62
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-midwest-transit-racing-team-2",
    "teamId": "t-1999-nascar-midwest-transit-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 66,
      "aeroEfficiency": 58,
      "mechanicalGrip": 59,
      "reliability": 59,
      "pitCrewOperations": 62
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-morgan-mcclure-motorsports",
    "teamId": "t-1999-nascar-morgan-mcclure-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 86,
      "aeroEfficiency": 85,
      "mechanicalGrip": 89,
      "reliability": 89,
      "pitCrewOperations": 91
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-nemco-motorsports",
    "teamId": "t-1999-nascar-nemco-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 43,
      "aeroEfficiency": 42,
      "mechanicalGrip": 42,
      "reliability": 40,
      "pitCrewOperations": 41
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-penske-kranefuss-racing",
    "teamId": "t-1999-nascar-penske-kranefuss-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 97,
      "aeroEfficiency": 96,
      "mechanicalGrip": 94,
      "reliability": 93,
      "pitCrewOperations": 93
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-petty-enterprises",
    "teamId": "t-1999-nascar-petty-enterprises",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 83,
      "aeroEfficiency": 85,
      "mechanicalGrip": 89,
      "reliability": 86,
      "pitCrewOperations": 90
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-petty-huggins-racing",
    "teamId": "t-1999-nascar-petty-huggins-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 46,
      "aeroEfficiency": 41,
      "mechanicalGrip": 44,
      "reliability": 38,
      "pitCrewOperations": 45
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-phoenix-air-racing",
    "teamId": "t-1999-nascar-phoenix-air-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 42,
      "aeroEfficiency": 37,
      "mechanicalGrip": 40,
      "reliability": 39,
      "pitCrewOperations": 36
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-pinnacle-motorsports",
    "teamId": "t-1999-nascar-pinnacle-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 43,
      "aeroEfficiency": 36,
      "mechanicalGrip": 35,
      "reliability": 37,
      "pitCrewOperations": 39
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-richard-childress-racing",
    "teamId": "t-1999-nascar-richard-childress-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 94,
      "aeroEfficiency": 96,
      "mechanicalGrip": 94,
      "reliability": 97,
      "pitCrewOperations": 94
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-robert-yates-racing",
    "teamId": "t-1999-nascar-robert-yates-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 100,
      "aeroEfficiency": 98,
      "mechanicalGrip": 97,
      "reliability": 94,
      "pitCrewOperations": 100
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-roehrig-motorsports",
    "teamId": "t-1999-nascar-roehrig-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 44,
      "aeroEfficiency": 39,
      "mechanicalGrip": 39,
      "reliability": 41,
      "pitCrewOperations": 39
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-ron-burns-racing",
    "teamId": "t-1999-nascar-ron-burns-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 32,
      "aeroEfficiency": 32,
      "mechanicalGrip": 27,
      "reliability": 28,
      "pitCrewOperations": 29
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-roush-racing-team-1",
    "teamId": "t-1999-nascar-roush-racing-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 100,
      "aeroEfficiency": 100,
      "mechanicalGrip": 95,
      "reliability": 100,
      "pitCrewOperations": 93
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-roush-racing-team-2",
    "teamId": "t-1999-nascar-roush-racing-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 84,
      "aeroEfficiency": 88,
      "mechanicalGrip": 80,
      "reliability": 81,
      "pitCrewOperations": 88
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-roush-racing-team-3",
    "teamId": "t-1999-nascar-roush-racing-team-3",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 90,
      "aeroEfficiency": 90,
      "mechanicalGrip": 91,
      "reliability": 91,
      "pitCrewOperations": 94
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-rudd-performance-motorsports",
    "teamId": "t-1999-nascar-rudd-performance-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 85,
      "aeroEfficiency": 84,
      "mechanicalGrip": 77,
      "reliability": 76,
      "pitCrewOperations": 80
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-sbiii-motorsports-team-1",
    "teamId": "t-1999-nascar-sbiii-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 67,
      "aeroEfficiency": 65,
      "mechanicalGrip": 61,
      "reliability": 68,
      "pitCrewOperations": 67
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-sbiii-motorsports-team-2",
    "teamId": "t-1999-nascar-sbiii-motorsports-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 67,
      "aeroEfficiency": 65,
      "mechanicalGrip": 61,
      "reliability": 68,
      "pitCrewOperations": 67
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-shepherd-racing",
    "teamId": "t-1999-nascar-shepherd-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 36,
      "aeroEfficiency": 41,
      "mechanicalGrip": 36,
      "reliability": 35,
      "pitCrewOperations": 36
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-standridge-motorsports",
    "teamId": "t-1999-nascar-standridge-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 29,
      "aeroEfficiency": 33,
      "mechanicalGrip": 28,
      "reliability": 29,
      "pitCrewOperations": 35
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-t-r-i-x-racing",
    "teamId": "t-1999-nascar-t-r-i-x-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 37,
      "aeroEfficiency": 32,
      "mechanicalGrip": 30,
      "reliability": 31,
      "pitCrewOperations": 32
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-team-sabco-team-1",
    "teamId": "t-1999-nascar-team-sabco-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 84,
      "aeroEfficiency": 90,
      "mechanicalGrip": 83,
      "reliability": 87,
      "pitCrewOperations": 90
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-team-sabco-team-2-team-1",
    "teamId": "t-1999-nascar-team-sabco-team-2-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 45,
      "mechanicalGrip": 45,
      "reliability": 46,
      "pitCrewOperations": 45
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-team-sabco-team-2-team-2",
    "teamId": "t-1999-nascar-team-sabco-team-2-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 45,
      "mechanicalGrip": 45,
      "reliability": 46,
      "pitCrewOperations": 45
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-ted-christopher-racing",
    "teamId": "t-1999-nascar-ted-christopher-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 41,
      "aeroEfficiency": 42,
      "mechanicalGrip": 38,
      "reliability": 39,
      "pitCrewOperations": 42
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-triad-motorsports",
    "teamId": "t-1999-nascar-triad-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 39,
      "aeroEfficiency": 36,
      "mechanicalGrip": 34,
      "reliability": 40,
      "pitCrewOperations": 39
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-tyler-jet-motorsports-team-1",
    "teamId": "t-1999-nascar-tyler-jet-motorsports-team-1",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 77,
      "aeroEfficiency": 76,
      "mechanicalGrip": 72,
      "reliability": 77,
      "pitCrewOperations": 75
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-tyler-jet-motorsports-team-2",
    "teamId": "t-1999-nascar-tyler-jet-motorsports-team-2",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 77,
      "aeroEfficiency": 76,
      "mechanicalGrip": 72,
      "reliability": 77,
      "pitCrewOperations": 75
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-ultra-motorsports",
    "teamId": "t-1999-nascar-ultra-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 43,
      "aeroEfficiency": 41,
      "mechanicalGrip": 42,
      "reliability": 48,
      "pitCrewOperations": 47
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-wood-brothers-racing",
    "teamId": "t-1999-nascar-wood-brothers-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 85,
      "aeroEfficiency": 83,
      "mechanicalGrip": 86,
      "reliability": 79,
      "pitCrewOperations": 81
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-yarborough-burdette-motorsports",
    "teamId": "t-1999-nascar-yarborough-burdette-motorsports",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 81,
      "aeroEfficiency": 82,
      "mechanicalGrip": 83,
      "reliability": 76,
      "pitCrewOperations": 76
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-1999-nascar-zali-racing",
    "teamId": "t-1999-nascar-zali-racing",
    "seasonYear": 1999,
    "ratings": {
      "enginePower": 44,
      "aeroEfficiency": 40,
      "mechanicalGrip": 39,
      "reliability": 37,
      "pitCrewOperations": 37
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  }
] as const satisfies Car[];

