// AUTO-GENERATED by scripts/gen_nascar_seasons.py. Do not hand-edit.
import type {
  Car,
} from '../../types/gameTypes';

export const cars2013NASCAR: Car[] = [
  {
    "id": "car-2013-nascar-bk-racing-team-1",
    "teamId": "t-2013-nascar-bk-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 58,
      "aeroEfficiency": 55,
      "mechanicalGrip": 58,
      "reliability": 55,
      "pitCrewOperations": 57
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-brian-keselowski-motorsports-team-1",
    "teamId": "t-2013-nascar-brian-keselowski-motorsports-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 21,
      "aeroEfficiency": 22,
      "mechanicalGrip": 21,
      "reliability": 18,
      "pitCrewOperations": 22
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-circle-sport-team-1-team-1",
    "teamId": "t-2013-nascar-circle-sport-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 35,
      "aeroEfficiency": 37,
      "mechanicalGrip": 34,
      "reliability": 37,
      "pitCrewOperations": 34
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-circle-sport-team-1-team-2",
    "teamId": "t-2013-nascar-circle-sport-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 35,
      "aeroEfficiency": 37,
      "mechanicalGrip": 34,
      "reliability": 37,
      "pitCrewOperations": 34
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-circle-sport-team-1-team-3",
    "teamId": "t-2013-nascar-circle-sport-team-1-team-3",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 35,
      "aeroEfficiency": 37,
      "mechanicalGrip": 34,
      "reliability": 37,
      "pitCrewOperations": 34
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-earnhardt-ganassi-racing-team-1",
    "teamId": "t-2013-nascar-earnhardt-ganassi-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 86,
      "aeroEfficiency": 88,
      "mechanicalGrip": 87,
      "reliability": 86,
      "pitCrewOperations": 88
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-fas-lane-racing-team-1-team-1",
    "teamId": "t-2013-nascar-fas-lane-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 43,
      "aeroEfficiency": 40,
      "mechanicalGrip": 42,
      "reliability": 39,
      "pitCrewOperations": 44
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-fas-lane-racing-team-1-team-2",
    "teamId": "t-2013-nascar-fas-lane-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 43,
      "aeroEfficiency": 40,
      "mechanicalGrip": 42,
      "reliability": 39,
      "pitCrewOperations": 44
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-front-row-motorsports-team-1-team-1",
    "teamId": "t-2013-nascar-front-row-motorsports-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 68,
      "aeroEfficiency": 66,
      "mechanicalGrip": 63,
      "reliability": 63,
      "pitCrewOperations": 65
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-front-row-motorsports-team-1-team-2",
    "teamId": "t-2013-nascar-front-row-motorsports-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 68,
      "aeroEfficiency": 66,
      "mechanicalGrip": 63,
      "reliability": 63,
      "pitCrewOperations": 65
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-front-row-motorsports-team-2",
    "teamId": "t-2013-nascar-front-row-motorsports-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 70,
      "aeroEfficiency": 69,
      "mechanicalGrip": 66,
      "reliability": 70,
      "pitCrewOperations": 71
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-furniture-row-racing-team-1",
    "teamId": "t-2013-nascar-furniture-row-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 89,
      "aeroEfficiency": 89,
      "mechanicalGrip": 89,
      "reliability": 89,
      "pitCrewOperations": 89
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-germain-racing-team-1",
    "teamId": "t-2013-nascar-germain-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 71,
      "aeroEfficiency": 71,
      "mechanicalGrip": 72,
      "reliability": 73,
      "pitCrewOperations": 72
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-go-green-racing-team-1",
    "teamId": "t-2013-nascar-go-green-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 13,
      "aeroEfficiency": 14,
      "mechanicalGrip": 13,
      "reliability": 13,
      "pitCrewOperations": 17
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-hamilton-means-racing-team-1",
    "teamId": "t-2013-nascar-hamilton-means-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 15,
      "aeroEfficiency": 13,
      "mechanicalGrip": 16,
      "reliability": 16,
      "pitCrewOperations": 17
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-hendrick-motorsports-team-1",
    "teamId": "t-2013-nascar-hendrick-motorsports-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 100,
      "aeroEfficiency": 100,
      "mechanicalGrip": 100,
      "reliability": 100,
      "pitCrewOperations": 100
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-hendrick-motorsports-team-2",
    "teamId": "t-2013-nascar-hendrick-motorsports-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 100,
      "aeroEfficiency": 100,
      "mechanicalGrip": 100,
      "reliability": 100,
      "pitCrewOperations": 100
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-humphrey-smith-racing-team-1-team-1",
    "teamId": "t-2013-nascar-humphrey-smith-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 26,
      "aeroEfficiency": 26,
      "mechanicalGrip": 23,
      "reliability": 24,
      "pitCrewOperations": 23
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-humphrey-smith-racing-team-1-team-2",
    "teamId": "t-2013-nascar-humphrey-smith-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 26,
      "aeroEfficiency": 26,
      "mechanicalGrip": 23,
      "reliability": 24,
      "pitCrewOperations": 23
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-jtg-daugherty-racing-team-1",
    "teamId": "t-2013-nascar-jtg-daugherty-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 57,
      "aeroEfficiency": 56,
      "mechanicalGrip": 53,
      "reliability": 52,
      "pitCrewOperations": 56
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-joe-gibbs-racing-team-1-team-1",
    "teamId": "t-2013-nascar-joe-gibbs-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 94,
      "aeroEfficiency": 94,
      "mechanicalGrip": 94,
      "reliability": 92,
      "pitCrewOperations": 95
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-joe-gibbs-racing-team-1-team-2",
    "teamId": "t-2013-nascar-joe-gibbs-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 94,
      "aeroEfficiency": 94,
      "mechanicalGrip": 94,
      "reliability": 92,
      "pitCrewOperations": 95
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-joe-gibbs-racing-team-2",
    "teamId": "t-2013-nascar-joe-gibbs-racing-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 100,
      "aeroEfficiency": 100,
      "mechanicalGrip": 98,
      "reliability": 100,
      "pitCrewOperations": 100
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-leavine-family-racing-team-1-team-1",
    "teamId": "t-2013-nascar-leavine-family-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 36,
      "aeroEfficiency": 34,
      "mechanicalGrip": 34,
      "reliability": 32,
      "pitCrewOperations": 37
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-leavine-family-racing-team-1-team-2",
    "teamId": "t-2013-nascar-leavine-family-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 36,
      "aeroEfficiency": 34,
      "mechanicalGrip": 34,
      "reliability": 32,
      "pitCrewOperations": 37
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-max-q-motorsports-team-1",
    "teamId": "t-2013-nascar-max-q-motorsports-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 19,
      "aeroEfficiency": 18,
      "mechanicalGrip": 16,
      "reliability": 15,
      "pitCrewOperations": 18
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-michael-waltrip-racing-team-1-team-1",
    "teamId": "t-2013-nascar-michael-waltrip-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 78,
      "aeroEfficiency": 77,
      "mechanicalGrip": 75,
      "reliability": 77,
      "pitCrewOperations": 75
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-michael-waltrip-racing-team-1-team-2",
    "teamId": "t-2013-nascar-michael-waltrip-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 78,
      "aeroEfficiency": 77,
      "mechanicalGrip": 75,
      "reliability": 77,
      "pitCrewOperations": 75
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-michael-waltrip-racing-team-1-team-3",
    "teamId": "t-2013-nascar-michael-waltrip-racing-team-1-team-3",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 78,
      "aeroEfficiency": 77,
      "mechanicalGrip": 75,
      "reliability": 77,
      "pitCrewOperations": 75
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-michael-waltrip-racing-team-2",
    "teamId": "t-2013-nascar-michael-waltrip-racing-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 90,
      "aeroEfficiency": 90,
      "mechanicalGrip": 90,
      "reliability": 86,
      "pitCrewOperations": 90
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-nemco-jay-robinson-racing-team-1",
    "teamId": "t-2013-nascar-nemco-jay-robinson-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 20,
      "aeroEfficiency": 24,
      "mechanicalGrip": 22,
      "reliability": 21,
      "pitCrewOperations": 21
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-penske-racing-team-1",
    "teamId": "t-2013-nascar-penske-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 94,
      "aeroEfficiency": 94,
      "mechanicalGrip": 94,
      "reliability": 94,
      "pitCrewOperations": 94
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-penske-racing-team-2",
    "teamId": "t-2013-nascar-penske-racing-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 33,
      "aeroEfficiency": 29,
      "mechanicalGrip": 28,
      "reliability": 32,
      "pitCrewOperations": 31
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phil-parsons-racing-team-1",
    "teamId": "t-2013-nascar-phil-parsons-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 45,
      "aeroEfficiency": 46,
      "mechanicalGrip": 45,
      "reliability": 44,
      "pitCrewOperations": 47
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phoenix-racing-team-1-team-1",
    "teamId": "t-2013-nascar-phoenix-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 27,
      "aeroEfficiency": 26,
      "mechanicalGrip": 22,
      "reliability": 23,
      "pitCrewOperations": 26
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phoenix-racing-team-1-team-2",
    "teamId": "t-2013-nascar-phoenix-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 27,
      "aeroEfficiency": 26,
      "mechanicalGrip": 22,
      "reliability": 23,
      "pitCrewOperations": 26
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phoenix-racing-team-1-team-3",
    "teamId": "t-2013-nascar-phoenix-racing-team-1-team-3",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 27,
      "aeroEfficiency": 26,
      "mechanicalGrip": 22,
      "reliability": 23,
      "pitCrewOperations": 26
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phoenix-racing-team-1-team-4",
    "teamId": "t-2013-nascar-phoenix-racing-team-1-team-4",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 27,
      "aeroEfficiency": 26,
      "mechanicalGrip": 22,
      "reliability": 23,
      "pitCrewOperations": 26
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phoenix-racing-team-1-team-5",
    "teamId": "t-2013-nascar-phoenix-racing-team-1-team-5",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 27,
      "aeroEfficiency": 26,
      "mechanicalGrip": 22,
      "reliability": 23,
      "pitCrewOperations": 26
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-phoenix-racing-team-1-team-6",
    "teamId": "t-2013-nascar-phoenix-racing-team-1-team-6",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 27,
      "aeroEfficiency": 26,
      "mechanicalGrip": 22,
      "reliability": 23,
      "pitCrewOperations": 26
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-richard-childress-racing-team-1",
    "teamId": "t-2013-nascar-richard-childress-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 92,
      "aeroEfficiency": 92,
      "mechanicalGrip": 92,
      "reliability": 92,
      "pitCrewOperations": 92
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-richard-childress-racing-team-2-team-1",
    "teamId": "t-2013-nascar-richard-childress-racing-team-2-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 84,
      "aeroEfficiency": 86,
      "mechanicalGrip": 86,
      "reliability": 86,
      "pitCrewOperations": 87
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-richard-childress-racing-team-2-team-2",
    "teamId": "t-2013-nascar-richard-childress-racing-team-2-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 84,
      "aeroEfficiency": 86,
      "mechanicalGrip": 86,
      "reliability": 86,
      "pitCrewOperations": 87
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-richard-petty-motorsports-team-1",
    "teamId": "t-2013-nascar-richard-petty-motorsports-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 81,
      "aeroEfficiency": 83,
      "mechanicalGrip": 78,
      "reliability": 82,
      "pitCrewOperations": 79
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-roush-fenway-racing-team-1",
    "teamId": "t-2013-nascar-roush-fenway-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 93,
      "aeroEfficiency": 93,
      "mechanicalGrip": 93,
      "reliability": 93,
      "pitCrewOperations": 93
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-roush-fenway-racing-team-2",
    "teamId": "t-2013-nascar-roush-fenway-racing-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 93,
      "aeroEfficiency": 93,
      "mechanicalGrip": 93,
      "reliability": 93,
      "pitCrewOperations": 93
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-stewart-haas-racing-team-1-team-1",
    "teamId": "t-2013-nascar-stewart-haas-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 72,
      "aeroEfficiency": 73,
      "mechanicalGrip": 70,
      "reliability": 72,
      "pitCrewOperations": 71
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-stewart-haas-racing-team-1-team-2",
    "teamId": "t-2013-nascar-stewart-haas-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 72,
      "aeroEfficiency": 73,
      "mechanicalGrip": 70,
      "reliability": 72,
      "pitCrewOperations": 71
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-stewart-haas-racing-team-1-team-3",
    "teamId": "t-2013-nascar-stewart-haas-racing-team-1-team-3",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 72,
      "aeroEfficiency": 73,
      "mechanicalGrip": 70,
      "reliability": 72,
      "pitCrewOperations": 71
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-stewart-haas-racing-team-2",
    "teamId": "t-2013-nascar-stewart-haas-racing-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 91,
      "aeroEfficiency": 91,
      "mechanicalGrip": 89,
      "reliability": 91,
      "pitCrewOperations": 91
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-swan-racing-team-1-team-1",
    "teamId": "t-2013-nascar-swan-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 47,
      "mechanicalGrip": 46,
      "reliability": 48,
      "pitCrewOperations": 50
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-swan-racing-team-1-team-2",
    "teamId": "t-2013-nascar-swan-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 47,
      "mechanicalGrip": 46,
      "reliability": 48,
      "pitCrewOperations": 50
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-swan-racing-team-1-team-3",
    "teamId": "t-2013-nascar-swan-racing-team-1-team-3",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 47,
      "mechanicalGrip": 46,
      "reliability": 48,
      "pitCrewOperations": 50
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-tommy-baldwin-racing-team-1-team-1",
    "teamId": "t-2013-nascar-tommy-baldwin-racing-team-1-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 43,
      "mechanicalGrip": 44,
      "reliability": 46,
      "pitCrewOperations": 44
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-tommy-baldwin-racing-team-1-team-2",
    "teamId": "t-2013-nascar-tommy-baldwin-racing-team-1-team-2",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 47,
      "aeroEfficiency": 43,
      "mechanicalGrip": 44,
      "reliability": 46,
      "pitCrewOperations": 44
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-wood-brothers-racing-team-1",
    "teamId": "t-2013-nascar-wood-brothers-racing-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 25,
      "aeroEfficiency": 25,
      "mechanicalGrip": 26,
      "reliability": 25,
      "pitCrewOperations": 28
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  },
  {
    "id": "car-2013-nascar-xxxtreme-motorsport-team-1",
    "teamId": "t-2013-nascar-xxxtreme-motorsport-team-1",
    "seasonYear": 2013,
    "ratings": {
      "enginePower": 18,
      "aeroEfficiency": 18,
      "mechanicalGrip": 15,
      "reliability": 17,
      "pitCrewOperations": 17
    },
    "condition": 100,
    "developmentLevel": {
      "enginePower": 0,
      "aeroEfficiency": 0,
      "mechanicalGrip": 0,
      "reliability": 0,
      "pitCrewOperations": 0
    }
  }
] as const satisfies Car[];

