#!/usr/bin/env node
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const workbookPath = resolve(root, 'docs/source-data/pit/PIT_DATA_TRANSIT_ONLY_COMPLETED(1).xlsx');
const outPath = resolve(root, 'src/data/pit/pitTransitData.generated.ts');

const TRACK_HEADERS = [
  'TrackId',
  'Track_Name',
  'Series',
  'Era_Start_Year',
  'Era_End_Year',
  'Pit_Lane_Length_m',
  'Pit_Speed_Limit_Override',
  'Pit_Transit_Loss_Sec',
  'Config_Notes',
  'Source',
  'Pit_Loss_Method',
  'Confidence',
  'Uncertainty_PlusMinus_Sec',
  'Stationary_Service_Included',
];

const VALID_SERIES = new Set(['F1', 'IndyCar', 'CART', 'ChampCar', 'Champ Car', 'NASCAR', 'ALL']);
const VALID_CONFIDENCE = new Set(['High', 'Medium', 'Low']);

function normalizeSeries(series) {
  const key = String(series ?? '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '');
  const aliases = {
    f1: 'F1',
    indycar: 'IndyCar',
    cart: 'CART',
    champcar: 'ChampCar',
    nascar: 'NASCAR',
    all: 'ALL',
  };
  return aliases[key] ?? null;
}

function numberOrNull(value) {
  if (value === null || value === undefined || value === '') return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function requiredNumber(value, label, rowNum) {
  const n = numberOrNull(value);
  if (n === null) throw new Error(`${label} must be numeric at row ${rowNum}`);
  return n;
}

function assertHeaders(rows, required, sheetName) {
  const headers = Object.keys(rows[0] ?? {});
  for (const header of required) {
    if (!headers.includes(header)) throw new Error(`${sheetName} missing required header ${header}`);
  }
}

function validateTrackRows(rows) {
  assertHeaders(rows, TRACK_HEADERS, 'Track_Pit_Lane');
  return rows.map((row, index) => {
    const rowNum = index + 2;
    const series = normalizeSeries(row.Series);
    if (!series || !VALID_SERIES.has(String(row.Series).trim())) {
      throw new Error(`Unrecognized series '${row.Series}' at Track_Pit_Lane row ${rowNum}`);
    }
    const transitLossSeconds = requiredNumber(row.Pit_Transit_Loss_Sec, 'Pit_Transit_Loss_Sec', rowNum);
    const stationary = String(row.Stationary_Service_Included ?? '').trim().toUpperCase();
    if (stationary !== 'N') throw new Error(`Stationary_Service_Included must be N at row ${rowNum}`);
    const startYear = numberOrNull(row.Era_Start_Year);
    const endYear = numberOrNull(row.Era_End_Year);
    if (startYear !== null && endYear !== null && startYear > endYear) throw new Error(`Invalid year range at row ${rowNum}`);
    const confidence = String(row.Confidence ?? '').trim();
    if (!VALID_CONFIDENCE.has(confidence)) throw new Error(`Invalid Confidence '${confidence}' at row ${rowNum}`);
    return {
      pitDataTrackId: String(row.TrackId).trim(),
      trackName: String(row.Track_Name).trim(),
      series,
      startYear,
      endYear,
      pitLaneLengthMeters: numberOrNull(row.Pit_Lane_Length_m),
      pitSpeedLimitOverride: numberOrNull(row.Pit_Speed_Limit_Override),
      transitLossSeconds,
      configNotes: String(row.Config_Notes ?? ''),
      source: String(row.Source ?? ''),
      pitLossMethod: String(row.Pit_Loss_Method ?? ''),
      confidence,
      uncertaintyPlusMinusSeconds: numberOrNull(row.Uncertainty_PlusMinus_Sec),
      stationaryServiceIncluded: false,
    };
  });
}

async function main() {
  if (!existsSync(workbookPath)) {
    throw new Error(`Workbook not found at ${workbookPath}. Place PIT_DATA_TRANSIT_ONLY_COMPLETED(1).xlsx there before conversion.`);
  }
  let XLSX;
  try {
    XLSX = await import('xlsx');
  } catch {
    throw new Error('Missing workbook parser dependency: install dev dependency "xlsx" before running this converter.');
  }
  const workbook = XLSX.readFile(workbookPath);
  for (const sheet of ['Track_Pit_Lane', 'Pit_Rules_By_Series_Era', 'Pit_Loss_Methodology']) {
    if (!workbook.SheetNames.includes(sheet)) throw new Error(`Workbook missing sheet ${sheet}`);
  }
  const trackRows = XLSX.utils.sheet_to_json(workbook.Sheets.Track_Pit_Lane, { defval: null });
  const records = validateTrackRows(trackRows);
  if (records.length !== 208) throw new Error(`Expected 208 Track_Pit_Lane rows, found ${records.length}`);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, render(records));
  console.log(`Wrote ${records.length} pit transit records to ${outPath}`);
}

function render(records) {
  return `// AUTO-GENERATED by scripts/convertPitWorkbook.mjs. Do not edit by hand.\nimport type { PitRulesBySeriesEraRecord, PitTransitRecord } from '../../types/pitTypes';\n\nexport const PIT_TRANSIT_DATA = ${JSON.stringify(records, null, 2)} as const satisfies readonly PitTransitRecord[];\n\nexport const PIT_RULES_BY_SERIES_ERA = [] as const satisfies readonly PitRulesBySeriesEraRecord[];\n`;
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
