"""Generate 1990 NASCAR Phase 0 data files.

This one-off script reads the signed-off NASCAR master workbook and emits the
TS modules needed for the 1990 Winston Cup proof-of-concept:
- src/data/phase0/generated/season1990NASCAR.ts
- src/data/phase0/generated/globalNASCAR1990.ts
- src/data/teams/teams1990NASCAR.ts
- src/data/drivers/drivers1990NASCAR.ts
- src/data/cars/cars1990NASCAR.ts
- src/data/market/driverMarket1990NASCAR.ts
- src/data/market/youthProspects1990NASCAR.ts
"""

from __future__ import annotations

import json
import math
import re
import unicodedata
from pathlib import Path
from statistics import mean

import pandas as pd

ROOT = Path("/home/ubuntu/motorsport-sim-manager")
WORKBOOK = Path(
    "/home/ubuntu/attachments/3f26943e-be23-47cf-acb1-a47c949f39d9/"
    "NASCAR_MASTER_ALL_SEASONS_WORKING_PASS5_1990_20261+2.xlsx"
)

OUT_FILES = {
    "season": ROOT / "src" / "data" / "phase0" / "generated" / "season1990NASCAR.ts",
    "global": ROOT / "src" / "data" / "phase0" / "generated" / "globalNASCAR1990.ts",
    "teams": ROOT / "src" / "data" / "teams" / "teams1990NASCAR.ts",
    "drivers": ROOT / "src" / "data" / "drivers" / "drivers1990NASCAR.ts",
    "cars": ROOT / "src" / "data" / "cars" / "cars1990NASCAR.ts",
    "market": ROOT / "src" / "data" / "market" / "driverMarket1990NASCAR.ts",
    "youth": ROOT / "src" / "data" / "market" / "youthProspects1990NASCAR.ts",
}


def fold_ascii(text: str) -> str:
    return (
        unicodedata.normalize("NFKD", str(text))
        .encode("ascii", "ignore")
        .decode("ascii")
    )


def norm(text: str) -> str:
    text = fold_ascii(text).lower()
    text = re.sub(r"[^a-z0-9]+", " ", text).strip()
    return re.sub(r"\s+", " ", text)


def slug(text: str) -> str:
    return norm(text).replace(" ", "-")


def team_id(name: str) -> str:
    return "NASCAR_TEAM_" + slug(name).upper().replace("-", "_")


def legacy_team_id(name: str) -> str:
    return "t-1990-nascar-" + slug(name)


def legacy_car_id(name: str) -> str:
    return "car-1990-nascar-" + slug(name)


def driver_id(name: str) -> str:
    return "driver-nascar-1990-" + slug(name)


def legacy_driver_id(name: str) -> str:
    return "d-1990-nascar-" + slug(name)


def safe_int(value, default: int = 0) -> int:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return default
    try:
        return int(float(value))
    except (ValueError, TypeError):
        return default


def safe_float(value, default: float = 0.0) -> float:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return default
    try:
        return float(value)
    except (ValueError, TypeError):
        return default


def as_int_1_100(value, default: int = 50) -> int:
    v = safe_float(value, None)
    if v is None:
        return default
    if v <= 10:
        v *= 10
    return int(max(1, min(100, round(v))))


def write_ts(path: Path, imports: list[str], from_module: str, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by scripts/gen_nascar_1990.py. Do not hand-edit.\n")
        if imports:
            fh.write("import type {\n")
            for item in imports:
                fh.write(f"  {item},\n")
            fh.write(f"}} from '{from_module}';\n\n")
        fh.write(body)
        fh.write("\n")


def car_overall(row: dict) -> int:
    return int(
        round(
            mean(
                [
                    as_int_1_100(row["enginePower"]),
                    as_int_1_100(row["aeroEfficiency"]),
                    as_int_1_100(row["mechanicalGrip"]),
                    as_int_1_100(row["reliability"]),
                    as_int_1_100(row["pitCrewOperations"]),
                ]
            )
        )
    )


def driver_overall(row: dict) -> int:
    cols = [
        "cornering",
        "braking",
        "straights",
        "tractionAcceleration",
        "elevationBlindCorners",
        "technical",
        "overtakingRacecraft",
        "surfaceGripBumpiness",
        "riskManagement",
        "enduranceConsistency",
        "qualifying",
        "racePace",
        "adaptability",
        "aggression",
        "composure",
    ]
    return int(round(mean([as_int_1_100(row.get(c)) for c in cols])))


def track_type_info(archetype: str) -> dict:
    a = str(archetype).lower()
    if "road" in a:
        return {"type": "road", "category": "Road", "ovalSubtype": None}
    if "street" in a:
        return {"type": "street", "category": "Street", "ovalSubtype": None}
    if "superspeedway" in a:
        return {"type": "oval", "category": "Oval", "ovalSubtype": "Superspeedway"}
    if "short" in a or "short track" in a:
        return {"type": "oval", "category": "Oval", "ovalSubtype": "Short Oval"}
    return {"type": "oval", "category": "Oval", "ovalSubtype": "Speedway"}


def generate() -> None:
    # ------------------------------------------------------------------
    # Load workbook sheets
    # ------------------------------------------------------------------
    calendar_df = pd.read_excel(WORKBOOK, sheet_name="Calendar")
    standings_df = pd.read_excel(WORKBOOK, sheet_name="Standings")
    entries_df = pd.read_excel(WORKBOOK, sheet_name="Team_Entries")
    driver_ratings_df = pd.read_excel(WORKBOOK, sheet_name="Driver_Ratings")
    car_ratings_df = pd.read_excel(WORKBOOK, sheet_name="Car_Ratings")
    track_ratings_df = pd.read_excel(WORKBOOK, sheet_name="Track_Ratings")

    calendar_df = calendar_df[calendar_df["Season"] == 1990].sort_values("Round")
    standings_df = standings_df[standings_df["Season"] == 1990]
    entries_df = entries_df[entries_df["Season"] == 1990]
    driver_ratings_df = driver_ratings_df[driver_ratings_df["Season"] == 1990]
    car_ratings_df = car_ratings_df[car_ratings_df["Season"] == 1990]
    track_ratings_df = track_ratings_df[track_ratings_df["Season"] == 1990]

    # ------------------------------------------------------------------
    # Calendars (race list)
    # ------------------------------------------------------------------
    races: list[dict] = []
    for _, row in calendar_df.iterrows():
        races.append(
            {
                "round": safe_int(row["Round"]),
                "raceName": str(row["Race Name"]).strip(),
                "trackId": str(row["TrackId"]).strip(),
                "trackName": str(row["Track"]).strip(),
                "laps": safe_int(row["Laps"]),
                "distanceKm": round(safe_float(row["DistanceKm"]), 3),
            }
        )

    # ------------------------------------------------------------------
    # Track lengths from calendar
    # ------------------------------------------------------------------
    track_lengths: dict[str, float] = {}
    for _, row in calendar_df.iterrows():
        tid = str(row["TrackId"]).strip()
        laps = safe_int(row["Laps"])
        dist = safe_float(row["DistanceKm"])
        if laps > 0 and tid not in track_lengths:
            track_lengths[tid] = round(dist / laps, 3)

    # ------------------------------------------------------------------
    # Car ratings (teams + cars)
    # ------------------------------------------------------------------
    car_by_team: dict[str, dict] = {}
    for _, row in car_ratings_df.iterrows():
        team_name = str(row["Team"]).strip()
        car_by_team[team_name] = row

    # ------------------------------------------------------------------
    # Driver ratings map
    # ------------------------------------------------------------------
    driver_ratings_by_name: dict[str, dict] = {}
    for _, row in driver_ratings_df.iterrows():
        driver_ratings_by_name[str(row["Driver"]).strip()] = row

    # ------------------------------------------------------------------
    # Primary drivers: one per team / car number (first occurrence)
    # ------------------------------------------------------------------
    primary_driver_entries: list[dict] = []
    seen_team_car: set[tuple[str, str]] = set()
    for _, row in entries_df.iterrows():
        team_name = str(row["Team"]).strip()
        car_num = str(row["Car#"]).strip()
        key = (team_name, car_num)
        if key in seen_team_car:
            continue
        seen_team_car.add(key)
        primary_driver_entries.append(row)

    # roster driver names set
    primary_driver_names = {str(row["Driver"]).strip() for row in primary_driver_entries}

    # ------------------------------------------------------------------
    # Global drivers (all drivers with ratings)
    # ------------------------------------------------------------------
    global_drivers: list[dict] = []
    for _, row in driver_ratings_df.iterrows():
        name = str(row["Driver"]).strip()
        drv_slug = slug(name)
        overall = driver_overall(row)
        team_cell = row.get("Team")
        contract_team = ""
        if pd.notna(team_cell):
            contract_team = team_id(str(team_cell).strip())

        def f(col: str) -> int:
            return as_int_1_100(row.get(col))

        global_drivers.append(
            {
                "driverId": driver_id(name),
                "name": name,
                "traits": [],
                "seriesAffinity": [{"series": "NASCAR", "strength": 100}],
                "careerTimeline": [],
                "cornering": f("cornering"),
                "braking": f("braking"),
                "straights": f("straights"),
                "tractionAcceleration": f("tractionAcceleration"),
                "elevationBlindCorners": f("elevationBlindCorners"),
                "technical": f("technical"),
                "overtakingRacecraft": f("overtakingRacecraft"),
                "surfaceGripBumpiness": f("surfaceGripBumpiness"),
                "riskManagement": f("riskManagement"),
                "enduranceConsistency": f("enduranceConsistency"),
                "qualifying": f("qualifying"),
                "racePace": f("racePace"),
                "adaptability": f("adaptability"),
                "aggression": f("aggression"),
                "composure": f("composure"),
                "startsRestarts": overall,
                "wetWeather": overall,
                "tireManagement": overall,
                "pressureHandling": overall,
                "feedbackQuality": overall,
                "technicalUnderstanding": overall,
                "mechanicalSympathy": overall,
                "overall": overall,
                "potential": min(99, overall + 5),
                "developmentPotential": max(10, 100 - overall),
                "morale": overall,
                "trust": overall,
                "reputation": overall,
                "marketValue": overall,
                "contract": {
                    "teamId": contract_team,
                    "yearsLeft": 1,
                    "salary": round(overall * 0.5),
                    "options": [],
                },
            }
        )

    # ------------------------------------------------------------------
    # Global teams and global cars
    # ------------------------------------------------------------------
    global_teams: list[dict] = []
    global_cars: list[dict] = []
    for _, row in car_ratings_df.iterrows():
        team_name = str(row["Team"]).strip()
        t_slug = slug(team_name)
        overall = car_overall(row)

        global_teams.append(
            {
                "teamLineageId": team_id(team_name),
                "series": "NASCAR",
                "canonicalName": team_name,
                "namePerPeriod": [
                    {"fromYear": 1990, "toYear": 1990, "name": team_name}
                ],
                "nameChangeEvents": [
                    {
                        "year": 1990,
                        "newName": team_name,
                        "note": "First season this lineage appears in uploaded source data.",
                    }
                ],
                "reputation": overall,
                "raceOperations": overall,
                "pitCrewOperations": as_int_1_100(row["pitCrewOperations"]),
                "developmentRate": 50,
                "facilities": overall,
                "sponsorStrength": overall,
                "commercialStrength": overall,
                "politicalInfluence": overall,
                "financeHealth": overall,
                "budget": int(overall * 1_000_000),
            }
        )

        def c(col: str) -> int:
            return as_int_1_100(row.get(col))

        global_cars.append(
            {
                "carId": legacy_car_id(team_name),
                "teamId": team_id(team_name),
                "seasonYear": 1990,
                "series": "NASCAR",
                "enginePower": c("enginePower"),
                "fuelEnergyEfficiency": 50,
                "drag": max(1, min(100, 100 - c("aeroEfficiency"))),
                "downforce": c("aeroEfficiency"),
                "chassisBalance": overall,
                "cooling": c("reliability"),
                "weightEfficiency": overall,
                "mechanicalGrip": c("mechanicalGrip"),
                "brakingStability": round((c("enginePower") + c("mechanicalGrip")) / 2),
                "acceleration": round((c("enginePower") + c("mechanicalGrip")) / 2),
                "topSpeed": round((c("enginePower") * 0.6 + c("aeroEfficiency") * 0.4)),
                "tireWear": max(
                    1, min(100, 100 - round((c("mechanicalGrip") + c("reliability")) / 2))
                ),
                "tireWarmup": 50,
                "tempControl": c("reliability"),
                "wetPerformance": round((c("mechanicalGrip") + c("reliability")) / 2),
                "reliability": c("reliability"),
                "setupWindow": c("pitCrewOperations"),
                "upgradeCompatibility": 50,
                "carOverall": overall,
            }
        )

    # ------------------------------------------------------------------
    # Global tracks
    # ------------------------------------------------------------------
    global_tracks: list[dict] = []
    for _, row in track_ratings_df.iterrows():
        track_name = str(row["Track"]).strip()
        track_id = str(row["TrackId"]).strip()
        archetype = str(row["Archetype"]).strip()
        info = track_type_info(archetype)

        def t(col: str) -> int:
            return as_int_1_100(row.get(col))

        corners = t("corners")
        technical = t("technical")
        risk_wall = t("riskWallProximity")

        track_obj: dict = {
            "trackId": track_id,
            "name": track_name,
            "facility": track_name,
            "configNote": "NASCAR configuration",
            "type": info["type"],
            "category": info["category"],
            "subcategory": archetype,
            "location": track_name,
            "city": "",
            "stateProvinceRegion": "",
            "country": "United States",
            "locationDisplay": f"{track_name}, United States",
            "locationConfidence": "Source-Derived",
            "locationSource": "NASCAR master workbook",
            "lengthKm": track_lengths.get(track_id, 2.5),
            "seasonsUsed": [{"year": 1990, "series": "NASCAR"}],
            "aliases": [track_id],
            "attributes": {
                "corners": corners,
                "braking": t("braking"),
                "straights": t("straights"),
                "tractionAcceleration": t("tractionAcceleration"),
                "elevationBlindCorners": t("elevationBlindCorners"),
                "technical": technical,
                "overtakingRacecraft": t("overtakingRacecraft"),
                "surfaceGripBumpiness": t("surfaceGripBumpiness"),
                "riskWallProximity": risk_wall,
                "enduranceConsistency": t("enduranceConsistency"),
            },
            "demandProfile": {
                "downforceDemand": corners,
                "powerDemand": t("straights"),
                "mechanicalDemand": technical,
                "brakeDemand": t("braking"),
                "tireDemand": t("surfaceGripBumpiness"),
                "coolingDemand": 50,
                "riskDemand": risk_wall,
                "tractionDemand": t("tractionAcceleration"),
                "overtakingDifficulty": max(1, min(100, 100 - t("overtakingRacecraft"))),
                "tireWearSeverity": t("surfaceGripBumpiness"),
                "reliabilityStress": t("enduranceConsistency"),
                "setupComplexity": technical,
                "pitStrategySensitivity": 50,
                "safetyCarCautionRisk": 50,
                "overallTrackDifficulty": round((corners + technical + risk_wall) / 3),
                "winnerBaseline": 50,
            },
        }
        if info["ovalSubtype"]:
            track_obj["ovalSubtype"] = info["ovalSubtype"]
        global_tracks.append(track_obj)

    # ------------------------------------------------------------------
    # Legacy teams / drivers / cars
    # ------------------------------------------------------------------
    legacy_teams: list[dict] = []
    legacy_drivers: list[dict] = []
    legacy_cars: list[dict] = []

    # Group primary drivers by team
    team_primary_drivers: dict[str, list[dict]] = {}
    for row in primary_driver_entries:
        team_name = str(row["Team"]).strip()
        team_primary_drivers.setdefault(team_name, []).append(row)

    for idx, (_, row) in enumerate(car_ratings_df.iterrows()):
        team_name = str(row["Team"]).strip()
        t_slug = slug(team_name)
        overall = car_overall(row)
        primary = team_primary_drivers.get(team_name, [])
        driver_ids = [legacy_driver_id(str(r["Driver"]).strip()) for r in primary]

        legacy_teams.append(
            {
                "id": legacy_team_id(team_name),
                "name": team_name,
                "shortName": "",
                "carId": legacy_car_id(team_name),
                "driverIds": driver_ids,
                "budget": 50,
                "reputation": overall,
                "raceOperations": overall,
                "morale": 65,
                "expectedStanding": idx + 1,
                "difficulty": "Medium",
                "color": "#60a5fa",
                "country": "United States",
            }
        )

        legacy_cars.append(
            {
                "id": legacy_car_id(team_name),
                "teamId": legacy_team_id(team_name),
                "seasonYear": 1990,
                "ratings": {
                    "enginePower": as_int_1_100(row["enginePower"]),
                    "aeroEfficiency": as_int_1_100(row["aeroEfficiency"]),
                    "mechanicalGrip": as_int_1_100(row["mechanicalGrip"]),
                    "reliability": as_int_1_100(row["reliability"]),
                    "pitCrewOperations": as_int_1_100(row["pitCrewOperations"]),
                },
                "condition": 100,
                "developmentLevel": {
                    "enginePower": 0,
                    "aeroEfficiency": 0,
                    "mechanicalGrip": 0,
                    "reliability": 0,
                    "pitCrewOperations": 0,
                },
            }
        )

    for row in primary_driver_entries:
        driver_name = str(row["Driver"]).strip()
        team_name = str(row["Team"]).strip()
        legacy_drivers.append(
            {
                "id": legacy_driver_id(driver_name),
                "name": driver_name,
                "number": safe_int(row["Car#"]),
                "teamId": legacy_team_id(team_name),
                "ratings": {
                    "cornering": 50,
                    "braking": 50,
                    "straights": 50,
                    "tractionAcceleration": 50,
                    "elevationBlindCorners": 50,
                    "technical": 50,
                    "overtakingRacecraft": 50,
                    "surfaceGripBumpiness": 50,
                    "riskManagement": 50,
                    "enduranceConsistency": 50,
                    "qualifying": 50,
                    "racePace": 50,
                    "adaptability": 50,
                    "aggression": 50,
                    "composure": 50,
                    "overall": 50,
                },
                "morale": 65,
                "confidence": 65,
                "traits": [],
            }
        )

    # ------------------------------------------------------------------
    # Season bundle
    # ------------------------------------------------------------------
    team_entries: list[dict] = []
    for row in primary_driver_entries:
        team_entries.append(
            {
                "teamId": team_id(str(row["Team"]).strip()),
                "carNumber": str(row["Car#"]).strip(),
                "driverId": driver_id(str(row["Driver"]).strip()),
                "chassis": str(row["Chassis"]).strip(),
                "engine": str(row["Engine"]).strip(),
            }
        )

    standings: list[dict] = []
    for _, row in standings_df.iterrows():
        name = str(row["Driver"]).strip()
        team_cell = row.get("Team")
        team_id_val = ""
        if pd.notna(team_cell):
            team_id_val = team_id(str(team_cell).strip())
        standings.append(
            {
                "driverId": driver_id(name),
                "teamId": team_id_val,
                "position": safe_int(row["Championship Position"]),
                "points": round(safe_float(row["Points"]), 1),
            }
        )

    driver_assignments = [
        {
            "entityId": driver_id(str(row["Driver"]).strip()),
            "label": str(row["Driver"]).strip(),
            "sourceSheet": "Driver_Ratings",
        }
        for _, row in driver_ratings_df.iterrows()
    ]
    team_assignments = [
        {
            "entityId": team_id(str(row["Team"]).strip()),
            "label": str(row["Team"]).strip(),
            "sourceSheet": "Car_Ratings",
        }
        for _, row in car_ratings_df.iterrows()
    ]
    track_assignments = [
        {
            "entityId": str(row["TrackId"]).strip(),
            "label": str(row["Track"]).strip(),
            "sourceSheet": "Track_Ratings",
        }
        for _, row in track_ratings_df.iterrows()
    ]

    season_bundle = {
        "season": 1990,
        "series": "NASCAR",
        "seasonId": "1990-NASCAR",
        "calendar": races,
        "standings": standings,
        "teamEntries": team_entries,
        "driverAssignments": driver_assignments,
        "teamAssignments": team_assignments,
        "trackAssignments": track_assignments,
        "supplierAssignments": [],
        "tireAssignments": [],
        "principalAssignments": [],
        "youthAssignments": [],
    }

    # ------------------------------------------------------------------
    # Market drivers (extra drivers not in the primary roster)
    # ------------------------------------------------------------------
    market_drivers: list[dict] = []
    for _, row in driver_ratings_df.iterrows():
        name = str(row["Driver"]).strip()
        if name in primary_driver_names:
            continue
        overall = driver_overall(row)

        def mk(col: str) -> int:
            return as_int_1_100(row.get(col))

        market_drivers.append(
            {
                "id": driver_id(name),
                "name": name,
                "age": 30,
                "nationality": "United States",
                "context": "NASCAR",
                "marketPool": "NASCAR",
                "marketStatus": "Free Agent",
                "primaryRole": "Driver",
                "immediateF1Eligible": False,
                "skills": {
                    "cornering": mk("cornering"),
                    "braking": mk("braking"),
                    "straights": mk("straights"),
                    "tractionAcceleration": mk("tractionAcceleration"),
                    "elevationBlindCorners": mk("elevationBlindCorners"),
                    "technical": mk("technical"),
                    "overtakingRacecraft": mk("overtakingRacecraft"),
                    "surfaceGripBumpiness": mk("surfaceGripBumpiness"),
                    "riskManagement": mk("riskManagement"),
                    "enduranceConsistency": mk("enduranceConsistency"),
                },
                "overall": overall,
                "potential": min(99, overall + 10),
                "potentialDelta": 10,
                "developmentRate": 50,
                "f1Readiness": 0,
                "salary": round(overall * 0.01, 2),
                "sponsorValue": round(overall * 0.005, 2),
                "buyoutCost": 0.0,
                "negotiationDifficulty": "Medium",
                "suggestedUse": "Stand-in / reserve",
                "notes": "",
            }
        )

    # ------------------------------------------------------------------
    # Youth prospects
    # ------------------------------------------------------------------
    youth_names = [
        "Bobby Hamilton Jr.",
        "Casey Atwood",
        "Jason Keller",
        "Hank Parker Jr.",
        "David Green",
    ]
    youth_prospects: list[dict] = []
    for i, name in enumerate(youth_names):
        potential = 55 + i * 5
        skills = {
            "cornering": 45 + i * 3,
            "braking": 46 + i * 2,
            "straights": 48 + i * 2,
            "tractionAcceleration": 45 + i * 2,
            "elevationBlindCorners": 42 + i * 3,
            "technical": 44 + i * 2,
            "overtakingRacecraft": 43 + i * 3,
            "surfaceGripBumpiness": 41 + i * 2,
            "riskManagement": 40 + i * 3,
            "enduranceConsistency": 47 + i * 2,
        }
        youth_prospects.append(
            {
                "id": f"youth-nascar-1990-{i + 1}",
                "name": name,
                "age": 17,
                "birthYear": 1973,
                "nationality": "United States",
                "currentLevel": "Late Model",
                "marketPool": "NASCAR",
                "marketStatus": "Academy Prospect",
                "academyEligibleNow": True,
                "earliestFullAcademyYear": 1990,
                "skills": skills,
                "overall": 50,
                "potential": potential,
                "potentialDelta": potential - 50,
                "developmentRate": 50,
                "yearsUntilF1Ready": 5,
                "signingCost": 0.05,
                "yearlyAcademyCost": 0.03,
                "riskLevel": "Medium",
                "suggestedPath": "NASCAR Truck development",
                "notes": "",
            }
        )

    # ------------------------------------------------------------------
    # Emit TS modules
    # ------------------------------------------------------------------
    def to_json(data) -> str:
        return json.dumps(data, ensure_ascii=False, indent=2)

    write_ts(
        OUT_FILES["global"],
        ["GlobalDriver", "GlobalTeam", "GlobalCar", "GlobalTrack"],
        "../../../types/gameTypes",
        "export const nascar1990Drivers: GlobalDriver[] = "
        + to_json(global_drivers)
        + " as const satisfies GlobalDriver[];\n\n"
        "export const nascar1990Teams: GlobalTeam[] = "
        + to_json(global_teams)
        + " as const satisfies GlobalTeam[];\n\n"
        "export const nascar1990Cars: GlobalCar[] = "
        + to_json(global_cars)
        + " as const satisfies GlobalCar[];\n\n"
        "export const nascar1990Tracks: GlobalTrack[] = "
        + to_json(global_tracks)
        + " as const satisfies GlobalTrack[];\n",
    )

    write_ts(
        OUT_FILES["season"],
        ["Phase0SeasonBundle"],
        "../../../types/gameTypes",
        "export const season1990NASCARPhase0: Phase0SeasonBundle = "
        + to_json(season_bundle)
        + " as const satisfies Phase0SeasonBundle;\n",
    )

    write_ts(
        OUT_FILES["teams"],
        ["Team"],
        "../../types/gameTypes",
        "export const teams1990NASCAR: Team[] = "
        + to_json(legacy_teams)
        + " as const satisfies Team[];\n",
    )

    write_ts(
        OUT_FILES["drivers"],
        ["Driver"],
        "../../types/gameTypes",
        "export const drivers1990NASCAR: Driver[] = "
        + to_json(legacy_drivers)
        + " as const satisfies Driver[];\n",
    )

    write_ts(
        OUT_FILES["cars"],
        ["Car"],
        "../../types/gameTypes",
        "export const cars1990NASCAR: Car[] = "
        + to_json(legacy_cars)
        + " as const satisfies Car[];\n",
    )

    write_ts(
        OUT_FILES["market"],
        ["MarketDriver"],
        "../../types/marketTypes",
        "export const driverMarket1990NASCAR: MarketDriver[] = "
        + to_json(market_drivers)
        + " as const satisfies MarketDriver[];\n",
    )

    write_ts(
        OUT_FILES["youth"],
        ["YouthProspect"],
        "../../types/marketTypes",
        "export const youthProspects1990NASCAR: YouthProspect[] = "
        + to_json(youth_prospects)
        + " as const satisfies YouthProspect[];\n",
    )

    print("Generated 1990 NASCAR files:")
    for path in OUT_FILES.values():
        print(f"  - {path}")


if __name__ == "__main__":
    generate()
