// AUTO-GENERATED by scripts/gen_aow_seasons.py.
// Shared AOW imports/registries for 1990–2007 CART + IRL seasons.

import type { Track } from '../types/gameTypes';
import type { MarketDriver, YouthProspect } from '../types/marketTypes';
import type { SeasonBundle } from './seasonCatalog';
import { season1990CART } from './seasons/season1990CART';
import { teams1990CART } from './teams/teams1990CART';
import { drivers1990CART } from './drivers/drivers1990CART';
import { cars1990CART } from './cars/cars1990CART';
import { season1991CART } from './seasons/season1991CART';
import { teams1991CART } from './teams/teams1991CART';
import { drivers1991CART } from './drivers/drivers1991CART';
import { cars1991CART } from './cars/cars1991CART';
import { season1992CART } from './seasons/season1992CART';
import { teams1992CART } from './teams/teams1992CART';
import { drivers1992CART } from './drivers/drivers1992CART';
import { cars1992CART } from './cars/cars1992CART';
import { season1993CART } from './seasons/season1993CART';
import { teams1993CART } from './teams/teams1993CART';
import { drivers1993CART } from './drivers/drivers1993CART';
import { cars1993CART } from './cars/cars1993CART';
import { season1994CART } from './seasons/season1994CART';
import { teams1994CART } from './teams/teams1994CART';
import { drivers1994CART } from './drivers/drivers1994CART';
import { cars1994CART } from './cars/cars1994CART';
import { season1995CART } from './seasons/season1995CART';
import { teams1995CART } from './teams/teams1995CART';
import { drivers1995CART } from './drivers/drivers1995CART';
import { cars1995CART } from './cars/cars1995CART';
import { season1996CART } from './seasons/season1996CART';
import { teams1996CART } from './teams/teams1996CART';
import { drivers1996CART } from './drivers/drivers1996CART';
import { cars1996CART } from './cars/cars1996CART';
import { season1997CART } from './seasons/season1997CART';
import { teams1997CART } from './teams/teams1997CART';
import { drivers1997CART } from './drivers/drivers1997CART';
import { cars1997CART } from './cars/cars1997CART';
import { season1998CART } from './seasons/season1998CART';
import { teams1998CART } from './teams/teams1998CART';
import { drivers1998CART } from './drivers/drivers1998CART';
import { cars1998CART } from './cars/cars1998CART';
import { season1999CART } from './seasons/season1999CART';
import { teams1999CART } from './teams/teams1999CART';
import { drivers1999CART } from './drivers/drivers1999CART';
import { cars1999CART } from './cars/cars1999CART';
import { season2000CART } from './seasons/season2000CART';
import { teams2000CART } from './teams/teams2000CART';
import { drivers2000CART } from './drivers/drivers2000CART';
import { cars2000CART } from './cars/cars2000CART';
import { season2001CART } from './seasons/season2001CART';
import { teams2001CART } from './teams/teams2001CART';
import { drivers2001CART } from './drivers/drivers2001CART';
import { cars2001CART } from './cars/cars2001CART';
import { season2002CART } from './seasons/season2002CART';
import { teams2002CART } from './teams/teams2002CART';
import { drivers2002CART } from './drivers/drivers2002CART';
import { cars2002CART } from './cars/cars2002CART';
import { season2003CART } from './seasons/season2003CART';
import { teams2003CART } from './teams/teams2003CART';
import { drivers2003CART } from './drivers/drivers2003CART';
import { cars2003CART } from './cars/cars2003CART';
import { season2004CART } from './seasons/season2004CART';
import { teams2004CART } from './teams/teams2004CART';
import { drivers2004CART } from './drivers/drivers2004CART';
import { cars2004CART } from './cars/cars2004CART';
import { season2005CART } from './seasons/season2005CART';
import { teams2005CART } from './teams/teams2005CART';
import { drivers2005CART } from './drivers/drivers2005CART';
import { cars2005CART } from './cars/cars2005CART';
import { season2006CART } from './seasons/season2006CART';
import { teams2006CART } from './teams/teams2006CART';
import { drivers2006CART } from './drivers/drivers2006CART';
import { cars2006CART } from './cars/cars2006CART';
import { season2007CART } from './seasons/season2007CART';
import { teams2007CART } from './teams/teams2007CART';
import { drivers2007CART } from './drivers/drivers2007CART';
import { cars2007CART } from './cars/cars2007CART';
import { season1996IndyCar } from './seasons/season1996IndyCar';
import { teams1996IndyCar } from './teams/teams1996IndyCar';
import { drivers1996IndyCar } from './drivers/drivers1996IndyCar';
import { cars1996IndyCar } from './cars/cars1996IndyCar';
import { season1997IndyCar } from './seasons/season1997IndyCar';
import { teams1997IndyCar } from './teams/teams1997IndyCar';
import { drivers1997IndyCar } from './drivers/drivers1997IndyCar';
import { cars1997IndyCar } from './cars/cars1997IndyCar';
import { season1998IndyCar } from './seasons/season1998IndyCar';
import { teams1998IndyCar } from './teams/teams1998IndyCar';
import { drivers1998IndyCar } from './drivers/drivers1998IndyCar';
import { cars1998IndyCar } from './cars/cars1998IndyCar';
import { season1999IndyCar } from './seasons/season1999IndyCar';
import { teams1999IndyCar } from './teams/teams1999IndyCar';
import { drivers1999IndyCar } from './drivers/drivers1999IndyCar';
import { cars1999IndyCar } from './cars/cars1999IndyCar';
import { season2000IndyCar } from './seasons/season2000IndyCar';
import { teams2000IndyCar } from './teams/teams2000IndyCar';
import { drivers2000IndyCar } from './drivers/drivers2000IndyCar';
import { cars2000IndyCar } from './cars/cars2000IndyCar';
import { season2001IndyCar } from './seasons/season2001IndyCar';
import { teams2001IndyCar } from './teams/teams2001IndyCar';
import { drivers2001IndyCar } from './drivers/drivers2001IndyCar';
import { cars2001IndyCar } from './cars/cars2001IndyCar';
import { season2002IndyCar } from './seasons/season2002IndyCar';
import { teams2002IndyCar } from './teams/teams2002IndyCar';
import { drivers2002IndyCar } from './drivers/drivers2002IndyCar';
import { cars2002IndyCar } from './cars/cars2002IndyCar';
import { season2003IndyCar } from './seasons/season2003IndyCar';
import { teams2003IndyCar } from './teams/teams2003IndyCar';
import { drivers2003IndyCar } from './drivers/drivers2003IndyCar';
import { cars2003IndyCar } from './cars/cars2003IndyCar';
import { season2004IndyCar } from './seasons/season2004IndyCar';
import { teams2004IndyCar } from './teams/teams2004IndyCar';
import { drivers2004IndyCar } from './drivers/drivers2004IndyCar';
import { cars2004IndyCar } from './cars/cars2004IndyCar';
import { season2005IndyCar } from './seasons/season2005IndyCar';
import { teams2005IndyCar } from './teams/teams2005IndyCar';
import { drivers2005IndyCar } from './drivers/drivers2005IndyCar';
import { cars2005IndyCar } from './cars/cars2005IndyCar';
import { season2006IndyCar } from './seasons/season2006IndyCar';
import { teams2006IndyCar } from './teams/teams2006IndyCar';
import { drivers2006IndyCar } from './drivers/drivers2006IndyCar';
import { cars2006IndyCar } from './cars/cars2006IndyCar';
import { season2007IndyCar } from './seasons/season2007IndyCar';
import { teams2007IndyCar } from './teams/teams2007IndyCar';
import { drivers2007IndyCar } from './drivers/drivers2007IndyCar';
import { cars2007IndyCar } from './cars/cars2007IndyCar';
import { driverMarket1990CART } from './market/driverMarket1990CART';
import { youthProspects1990CART } from './market/youthProspects1990CART';
import { driverMarket1991CART } from './market/driverMarket1991CART';
import { youthProspects1991CART } from './market/youthProspects1991CART';
import { driverMarket1992CART } from './market/driverMarket1992CART';
import { youthProspects1992CART } from './market/youthProspects1992CART';
import { driverMarket1993CART } from './market/driverMarket1993CART';
import { youthProspects1993CART } from './market/youthProspects1993CART';
import { driverMarket1994CART } from './market/driverMarket1994CART';
import { youthProspects1994CART } from './market/youthProspects1994CART';
import { driverMarket1995CART } from './market/driverMarket1995CART';
import { youthProspects1995CART } from './market/youthProspects1995CART';
import { driverMarket1996CART } from './market/driverMarket1996CART';
import { youthProspects1996CART } from './market/youthProspects1996CART';
import { driverMarket1997CART } from './market/driverMarket1997CART';
import { youthProspects1997CART } from './market/youthProspects1997CART';
import { driverMarket1998CART } from './market/driverMarket1998CART';
import { youthProspects1998CART } from './market/youthProspects1998CART';
import { driverMarket1999CART } from './market/driverMarket1999CART';
import { youthProspects1999CART } from './market/youthProspects1999CART';
import { driverMarket2000CART } from './market/driverMarket2000CART';
import { youthProspects2000CART } from './market/youthProspects2000CART';
import { driverMarket2001CART } from './market/driverMarket2001CART';
import { youthProspects2001CART } from './market/youthProspects2001CART';
import { driverMarket2002CART } from './market/driverMarket2002CART';
import { youthProspects2002CART } from './market/youthProspects2002CART';
import { driverMarket2003CART } from './market/driverMarket2003CART';
import { youthProspects2003CART } from './market/youthProspects2003CART';
import { driverMarket2004CART } from './market/driverMarket2004CART';
import { youthProspects2004CART } from './market/youthProspects2004CART';
import { driverMarket2005CART } from './market/driverMarket2005CART';
import { youthProspects2005CART } from './market/youthProspects2005CART';
import { driverMarket2006CART } from './market/driverMarket2006CART';
import { youthProspects2006CART } from './market/youthProspects2006CART';
import { driverMarket2007CART } from './market/driverMarket2007CART';
import { youthProspects2007CART } from './market/youthProspects2007CART';
import { driverMarket1996IndyCar } from './market/driverMarket1996IndyCar';
import { youthProspects1996IndyCar } from './market/youthProspects1996IndyCar';
import { driverMarket1997IndyCar } from './market/driverMarket1997IndyCar';
import { youthProspects1997IndyCar } from './market/youthProspects1997IndyCar';
import { driverMarket1998IndyCar } from './market/driverMarket1998IndyCar';
import { youthProspects1998IndyCar } from './market/youthProspects1998IndyCar';
import { driverMarket1999IndyCar } from './market/driverMarket1999IndyCar';
import { youthProspects1999IndyCar } from './market/youthProspects1999IndyCar';
import { driverMarket2000IndyCar } from './market/driverMarket2000IndyCar';
import { youthProspects2000IndyCar } from './market/youthProspects2000IndyCar';
import { driverMarket2001IndyCar } from './market/driverMarket2001IndyCar';
import { youthProspects2001IndyCar } from './market/youthProspects2001IndyCar';
import { driverMarket2002IndyCar } from './market/driverMarket2002IndyCar';
import { youthProspects2002IndyCar } from './market/youthProspects2002IndyCar';
import { driverMarket2003IndyCar } from './market/driverMarket2003IndyCar';
import { youthProspects2003IndyCar } from './market/youthProspects2003IndyCar';
import { driverMarket2004IndyCar } from './market/driverMarket2004IndyCar';
import { youthProspects2004IndyCar } from './market/youthProspects2004IndyCar';
import { driverMarket2005IndyCar } from './market/driverMarket2005IndyCar';
import { youthProspects2005IndyCar } from './market/youthProspects2005IndyCar';
import { driverMarket2006IndyCar } from './market/driverMarket2006IndyCar';
import { youthProspects2006IndyCar } from './market/youthProspects2006IndyCar';
import { driverMarket2007IndyCar } from './market/driverMarket2007IndyCar';
import { youthProspects2007IndyCar } from './market/youthProspects2007IndyCar';
import { tracks1990CART } from './tracks/tracks1990CART';
import { tracks1991CART } from './tracks/tracks1991CART';
import { tracks1992CART } from './tracks/tracks1992CART';
import { tracks1993CART } from './tracks/tracks1993CART';
import { tracks1994CART } from './tracks/tracks1994CART';
import { tracks1995CART } from './tracks/tracks1995CART';
import { tracks1996CART } from './tracks/tracks1996CART';
import { tracks1997CART } from './tracks/tracks1997CART';
import { tracks1998CART } from './tracks/tracks1998CART';
import { tracks1999CART } from './tracks/tracks1999CART';
import { tracks2000CART } from './tracks/tracks2000CART';
import { tracks2001CART } from './tracks/tracks2001CART';
import { tracks2002CART } from './tracks/tracks2002CART';
import { tracks2003CART } from './tracks/tracks2003CART';
import { tracks2004CART } from './tracks/tracks2004CART';
import { tracks2005CART } from './tracks/tracks2005CART';
import { tracks2006CART } from './tracks/tracks2006CART';
import { tracks2007CART } from './tracks/tracks2007CART';
import { tracks1996IndyCar } from './tracks/tracks1996IndyCar';
import { tracks1997IndyCar } from './tracks/tracks1997IndyCar';
import { tracks1998IndyCar } from './tracks/tracks1998IndyCar';
import { tracks1999IndyCar } from './tracks/tracks1999IndyCar';
import { tracks2000IndyCar } from './tracks/tracks2000IndyCar';
import { tracks2001IndyCar } from './tracks/tracks2001IndyCar';
import { tracks2002IndyCar } from './tracks/tracks2002IndyCar';
import { tracks2003IndyCar } from './tracks/tracks2003IndyCar';
import { tracks2004IndyCar } from './tracks/tracks2004IndyCar';
import { tracks2005IndyCar } from './tracks/tracks2005IndyCar';
import { tracks2006IndyCar } from './tracks/tracks2006IndyCar';
import { tracks2007IndyCar } from './tracks/tracks2007IndyCar';

export const aowAvailableSeasons: { year: number; series: 'CART' | 'Champ Car' | 'IndyCar'; label: string }[] = [
  { year: 1990, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1990 CART PPG Indy Car World Series' },
  { year: 1991, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1991 CART PPG Indy Car World Series' },
  { year: 1992, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1992 CART PPG Indy Car World Series' },
  { year: 1993, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1993 CART PPG Indy Car World Series' },
  { year: 1994, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1994 CART PPG Indy Car World Series' },
  { year: 1995, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1995 CART PPG Indy Car World Series' },
  { year: 1996, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1996 CART PPG Indy Car World Series' },
  { year: 1997, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1997 CART PPG Indy Car World Series' },
  { year: 1998, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1998 CART PPG Indy Car World Series' },
  { year: 1999, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '1999 CART PPG Indy Car World Series' },
  { year: 2000, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '2000 CART PPG Indy Car World Series' },
  { year: 2001, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '2001 CART PPG Indy Car World Series' },
  { year: 2002, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '2002 CART PPG Indy Car World Series' },
  { year: 2003, series: 'CART' as 'CART' | 'Champ Car' | 'IndyCar', label: '2003 CART PPG Indy Car World Series' },
  { year: 2004, series: 'Champ Car' as 'CART' | 'Champ Car' | 'IndyCar', label: '2004 Champ Car World Series' },
  { year: 2005, series: 'Champ Car' as 'CART' | 'Champ Car' | 'IndyCar', label: '2005 Champ Car World Series' },
  { year: 2006, series: 'Champ Car' as 'CART' | 'Champ Car' | 'IndyCar', label: '2006 Champ Car World Series' },
  { year: 2007, series: 'Champ Car' as 'CART' | 'Champ Car' | 'IndyCar', label: '2007 Champ Car World Series' },
  { year: 1996, series: 'IndyCar' as 'CART' | 'IndyCar', label: '1996 Indy Racing League' },
  { year: 1997, series: 'IndyCar' as 'CART' | 'IndyCar', label: '1997 Indy Racing League' },
  { year: 1998, series: 'IndyCar' as 'CART' | 'IndyCar', label: '1998 Indy Racing League' },
  { year: 1999, series: 'IndyCar' as 'CART' | 'IndyCar', label: '1999 Indy Racing League' },
  { year: 2000, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2000 Indy Racing League' },
  { year: 2001, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2001 Indy Racing League' },
  { year: 2002, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2002 Indy Racing League' },
  { year: 2003, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2003 Indy Racing League' },
  { year: 2004, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2004 Indy Racing League' },
  { year: 2005, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2005 Indy Racing League' },
  { year: 2006, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2006 Indy Racing League' },
  { year: 2007, series: 'IndyCar' as 'CART' | 'IndyCar', label: '2007 Indy Racing League' },
];

export const aowSeasonBundles: Record<string, SeasonBundle> = {
  '1990-CART': { season: season1990CART, teams: teams1990CART, drivers: drivers1990CART, cars: cars1990CART },
  '1991-CART': { season: season1991CART, teams: teams1991CART, drivers: drivers1991CART, cars: cars1991CART },
  '1992-CART': { season: season1992CART, teams: teams1992CART, drivers: drivers1992CART, cars: cars1992CART },
  '1993-CART': { season: season1993CART, teams: teams1993CART, drivers: drivers1993CART, cars: cars1993CART },
  '1994-CART': { season: season1994CART, teams: teams1994CART, drivers: drivers1994CART, cars: cars1994CART },
  '1995-CART': { season: season1995CART, teams: teams1995CART, drivers: drivers1995CART, cars: cars1995CART },
  '1996-CART': { season: season1996CART, teams: teams1996CART, drivers: drivers1996CART, cars: cars1996CART },
  '1997-CART': { season: season1997CART, teams: teams1997CART, drivers: drivers1997CART, cars: cars1997CART },
  '1998-CART': { season: season1998CART, teams: teams1998CART, drivers: drivers1998CART, cars: cars1998CART },
  '1999-CART': { season: season1999CART, teams: teams1999CART, drivers: drivers1999CART, cars: cars1999CART },
  '2000-CART': { season: season2000CART, teams: teams2000CART, drivers: drivers2000CART, cars: cars2000CART },
  '2001-CART': { season: season2001CART, teams: teams2001CART, drivers: drivers2001CART, cars: cars2001CART },
  '2002-CART': { season: season2002CART, teams: teams2002CART, drivers: drivers2002CART, cars: cars2002CART },
  '2003-CART': { season: season2003CART, teams: teams2003CART, drivers: drivers2003CART, cars: cars2003CART },
  '2004-Champ Car': { season: season2004CART, teams: teams2004CART, drivers: drivers2004CART, cars: cars2004CART },
  '2005-Champ Car': { season: season2005CART, teams: teams2005CART, drivers: drivers2005CART, cars: cars2005CART },
  '2006-Champ Car': { season: season2006CART, teams: teams2006CART, drivers: drivers2006CART, cars: cars2006CART },
  '2007-Champ Car': { season: season2007CART, teams: teams2007CART, drivers: drivers2007CART, cars: cars2007CART },
  '1996-IndyCar': { season: season1996IndyCar, teams: teams1996IndyCar, drivers: drivers1996IndyCar, cars: cars1996IndyCar },
  '1997-IndyCar': { season: season1997IndyCar, teams: teams1997IndyCar, drivers: drivers1997IndyCar, cars: cars1997IndyCar },
  '1998-IndyCar': { season: season1998IndyCar, teams: teams1998IndyCar, drivers: drivers1998IndyCar, cars: cars1998IndyCar },
  '1999-IndyCar': { season: season1999IndyCar, teams: teams1999IndyCar, drivers: drivers1999IndyCar, cars: cars1999IndyCar },
  '2000-IndyCar': { season: season2000IndyCar, teams: teams2000IndyCar, drivers: drivers2000IndyCar, cars: cars2000IndyCar },
  '2001-IndyCar': { season: season2001IndyCar, teams: teams2001IndyCar, drivers: drivers2001IndyCar, cars: cars2001IndyCar },
  '2002-IndyCar': { season: season2002IndyCar, teams: teams2002IndyCar, drivers: drivers2002IndyCar, cars: cars2002IndyCar },
  '2003-IndyCar': { season: season2003IndyCar, teams: teams2003IndyCar, drivers: drivers2003IndyCar, cars: cars2003IndyCar },
  '2004-IndyCar': { season: season2004IndyCar, teams: teams2004IndyCar, drivers: drivers2004IndyCar, cars: cars2004IndyCar },
  '2005-IndyCar': { season: season2005IndyCar, teams: teams2005IndyCar, drivers: drivers2005IndyCar, cars: cars2005IndyCar },
  '2006-IndyCar': { season: season2006IndyCar, teams: teams2006IndyCar, drivers: drivers2006IndyCar, cars: cars2006IndyCar },
  '2007-IndyCar': { season: season2007IndyCar, teams: teams2007IndyCar, drivers: drivers2007IndyCar, cars: cars2007IndyCar },
};

export const aowMarketBundles: Record<string, { drivers: MarketDriver[]; youth: YouthProspect[] }> = {
  '1990-CART': { drivers: driverMarket1990CART, youth: youthProspects1990CART },
  '1991-CART': { drivers: driverMarket1991CART, youth: youthProspects1991CART },
  '1992-CART': { drivers: driverMarket1992CART, youth: youthProspects1992CART },
  '1993-CART': { drivers: driverMarket1993CART, youth: youthProspects1993CART },
  '1994-CART': { drivers: driverMarket1994CART, youth: youthProspects1994CART },
  '1995-CART': { drivers: driverMarket1995CART, youth: youthProspects1995CART },
  '1996-CART': { drivers: driverMarket1996CART, youth: youthProspects1996CART },
  '1997-CART': { drivers: driverMarket1997CART, youth: youthProspects1997CART },
  '1998-CART': { drivers: driverMarket1998CART, youth: youthProspects1998CART },
  '1999-CART': { drivers: driverMarket1999CART, youth: youthProspects1999CART },
  '2000-CART': { drivers: driverMarket2000CART, youth: youthProspects2000CART },
  '2001-CART': { drivers: driverMarket2001CART, youth: youthProspects2001CART },
  '2002-CART': { drivers: driverMarket2002CART, youth: youthProspects2002CART },
  '2003-CART': { drivers: driverMarket2003CART, youth: youthProspects2003CART },
  '2004-Champ Car': { drivers: driverMarket2004CART, youth: youthProspects2004CART },
  '2005-Champ Car': { drivers: driverMarket2005CART, youth: youthProspects2005CART },
  '2006-Champ Car': { drivers: driverMarket2006CART, youth: youthProspects2006CART },
  '2007-Champ Car': { drivers: driverMarket2007CART, youth: youthProspects2007CART },
  '1996-IndyCar': { drivers: driverMarket1996IndyCar, youth: youthProspects1996IndyCar },
  '1997-IndyCar': { drivers: driverMarket1997IndyCar, youth: youthProspects1997IndyCar },
  '1998-IndyCar': { drivers: driverMarket1998IndyCar, youth: youthProspects1998IndyCar },
  '1999-IndyCar': { drivers: driverMarket1999IndyCar, youth: youthProspects1999IndyCar },
  '2000-IndyCar': { drivers: driverMarket2000IndyCar, youth: youthProspects2000IndyCar },
  '2001-IndyCar': { drivers: driverMarket2001IndyCar, youth: youthProspects2001IndyCar },
  '2002-IndyCar': { drivers: driverMarket2002IndyCar, youth: youthProspects2002IndyCar },
  '2003-IndyCar': { drivers: driverMarket2003IndyCar, youth: youthProspects2003IndyCar },
  '2004-IndyCar': { drivers: driverMarket2004IndyCar, youth: youthProspects2004IndyCar },
  '2005-IndyCar': { drivers: driverMarket2005IndyCar, youth: youthProspects2005IndyCar },
  '2006-IndyCar': { drivers: driverMarket2006IndyCar, youth: youthProspects2006IndyCar },
  '2007-IndyCar': { drivers: driverMarket2007IndyCar, youth: youthProspects2007IndyCar },
};

export const aowTracks: Track[] = [
  ...tracks1990CART,
  ...tracks1991CART,
  ...tracks1992CART,
  ...tracks1993CART,
  ...tracks1994CART,
  ...tracks1995CART,
  ...tracks1996CART,
  ...tracks1997CART,
  ...tracks1998CART,
  ...tracks1999CART,
  ...tracks2000CART,
  ...tracks2001CART,
  ...tracks2002CART,
  ...tracks2003CART,
  ...tracks2004CART,
  ...tracks2005CART,
  ...tracks2006CART,
  ...tracks2007CART,
  ...tracks1996IndyCar,
  ...tracks1997IndyCar,
  ...tracks1998IndyCar,
  ...tracks1999IndyCar,
  ...tracks2000IndyCar,
  ...tracks2001IndyCar,
  ...tracks2002IndyCar,
  ...tracks2003IndyCar,
  ...tracks2004IndyCar,
  ...tracks2005IndyCar,
  ...tracks2006IndyCar,
  ...tracks2007IndyCar,
];
